from __future__ import annotations

from .catalysts import build_catalysts_summary
from .confidence import build_confidence_profile, score_confidence
from .contracts import MarketIntelligenceContract, STANDARD_REPORT_FIELDS, build_market_intelligence_contract
from .crypto import build_crypto_intelligence_report
from .flow import build_flow_summary
from .futures import build_futures_intelligence_report
from .impact import build_impact_report
from .liquidity import build_liquidity_zones
from .manifold import (
    FEATURE_VECTOR_VERSION,
    build_manifold_feature_vector,
    build_manifold_review_queue,
    compact_manifold_review_response,
    infer_asset_type,
    infer_graph_asset_type,
    map_cross_asset_item,
    build_market_state_graph,
    map_market_state,
    map_prediction_market,
    nearest_historical_neighbors,
    relationship_templates_for_item,
    route_cross_asset_embedding,
)
from .no_trade import evaluate_no_trade
from .options import (
    build_options_intelligence_report,
    classify_dte_bucket,
    compute_gex,
    compute_net_gex,
    compute_vanna,
    compute_vanna_exposure,
    floor_time_to_expiry,
)
from .positioning import build_positioning_summary
from .prediction_markets import build_prediction_market_intelligence_report
from .regime import classify_regime
from .report import (
    build_market_intelligence_report,
    build_standard_market_intelligence_report,
    summarize_market_intelligence_report,
    validate_market_intelligence_report,
)
from .risk import build_no_trade_reason, build_risk_profile, evaluate_market_risk
from .scoring import score_signal
from .sports import (
    SUPPORTED_SPORTS,
    build_sports_confidence,
    build_sports_flow,
    build_sports_intelligence_report,
    build_sports_liquidity,
    build_sports_no_trade,
    build_sports_positioning,
    build_sports_risk,
    build_sports_targets,
    finalize_sports_response,
    normalize_market,
    normalize_role,
    normalize_sport,
    safe_flags,
)
from .targets import build_market_targets, build_targets
from .market_profiles import (
    DEFAULT_MARKET_PROFILE_CATALOG,
    NFL_AS_SPORTS_PROFILE_INSTANCE,
    OPTIONS_0DTE_PROFILE,
    PREDICTION_MARKET_PROFILE,
    SPORTS_PROFILE,
    build_market_profile_catalog,
    get_market_profile_catalog_entry,
    register_default_market_profiles,
    validate_market_profile_catalog,
)
from .research_asset_coverage_planner import (
    DEFAULT_RESEARCH_ASSET_COVERAGE_PLANNER_DATASET_NAME,
    DEFAULT_RESEARCH_ASSET_COVERAGE_PLANNER_OWNER,
    DEFAULT_RESEARCH_ASSET_COVERAGE_PLANNER_PROFILE_ID,
    DEFAULT_RESEARCH_ASSET_COVERAGE_PLANNER_STORAGE_PATH,
    RESEARCH_ASSET_COVERAGE_PLANNER_SCHEMA_VERSION,
    ResearchAssetCoveragePlannerRuntime,
    build_acquisition_plan,
    build_coverage_gap_engine,
    build_provider_coverage_registry,
    build_research_asset_coverage_planner_dashboard_snapshot,
    build_research_asset_coverage_planner_snapshot,
    build_research_asset_coverage_registry,
    build_worldview_query_surface,
    get_research_asset_coverage_planner_snapshot_for_dashboard,
)
from .research_intelligence import (
    DEFAULT_RESEARCH_INTELLIGENCE_DATASET_ID,
    DEFAULT_RESEARCH_INTELLIGENCE_DATASET_NAME,
    DEFAULT_RESEARCH_INTELLIGENCE_STORAGE_PATH,
    RESEARCH_INTELLIGENCE_RUNTIME_VERSION,
    RESEARCH_INTELLIGENCE_SCHEMA_VERSION,
    build_research_intelligence_snapshot,
    get_research_intelligence_snapshot_for_dashboard,
)
from .universal_market_framework import (
    DEFAULT_UNIVERSAL_MARKET_FRAMEWORK_ARTIFACT_ROOT,
    NFL_REFERENCE_PROFILE_ID,
    UNIVERSAL_MARKET_FRAMEWORK_RUNTIME_VERSION,
    UNIVERSAL_MARKET_FRAMEWORK_SCHEMA_VERSION,
    build_universal_market_framework_snapshot,
    get_universal_market_framework_snapshot_for_dashboard,
)

__all__ = [
    "STANDARD_REPORT_FIELDS",
    "MarketIntelligenceContract",
    "build_market_intelligence_contract",
    "build_market_intelligence_report",
    "build_standard_market_intelligence_report",
    "summarize_market_intelligence_report",
    "validate_market_intelligence_report",
    "build_confidence_profile",
    "score_confidence",
    "build_risk_profile",
    "evaluate_market_risk",
    "build_no_trade_reason",
    "build_targets",
    "build_market_targets",
    "build_positioning_summary",
    "build_flow_summary",
    "build_liquidity_zones",
    "build_catalysts_summary",
    "classify_regime",
    "score_signal",
    "evaluate_no_trade",
    "compute_gex",
    "compute_net_gex",
    "compute_vanna",
    "compute_vanna_exposure",
    "floor_time_to_expiry",
    "classify_dte_bucket",
    "build_options_intelligence_report",
    "build_sports_intelligence_report",
    "build_sports_confidence",
    "build_sports_targets",
    "build_sports_positioning",
    "build_sports_flow",
    "build_sports_liquidity",
    "build_sports_risk",
    "build_sports_no_trade",
    "finalize_sports_response",
    "normalize_sport",
    "normalize_market",
    "normalize_role",
    "safe_flags",
    "SUPPORTED_SPORTS",
    "build_prediction_market_intelligence_report",
    "build_futures_intelligence_report",
    "build_crypto_intelligence_report",
    "build_manifold_feature_vector",
    "build_manifold_review_queue",
    "compact_manifold_review_response",
    "infer_asset_type",
    "infer_graph_asset_type",
    "map_cross_asset_item",
    "build_market_state_graph",
    "map_prediction_market",
    "map_market_state",
    "nearest_historical_neighbors",
    "relationship_templates_for_item",
    "route_cross_asset_embedding",
    "FEATURE_VECTOR_VERSION",
    "build_impact_report",
    "DEFAULT_RESEARCH_ASSET_COVERAGE_PLANNER_DATASET_NAME",
    "DEFAULT_RESEARCH_ASSET_COVERAGE_PLANNER_OWNER",
    "DEFAULT_RESEARCH_ASSET_COVERAGE_PLANNER_PROFILE_ID",
    "DEFAULT_RESEARCH_ASSET_COVERAGE_PLANNER_STORAGE_PATH",
    "RESEARCH_ASSET_COVERAGE_PLANNER_SCHEMA_VERSION",
    "ResearchAssetCoveragePlannerRuntime",
    "build_acquisition_plan",
    "build_coverage_gap_engine",
    "build_provider_coverage_registry",
    "build_research_asset_coverage_planner_dashboard_snapshot",
    "build_research_asset_coverage_planner_snapshot",
    "build_research_asset_coverage_registry",
    "build_worldview_query_surface",
    "get_research_asset_coverage_planner_snapshot_for_dashboard",
    "DEFAULT_RESEARCH_INTELLIGENCE_DATASET_ID",
    "DEFAULT_RESEARCH_INTELLIGENCE_DATASET_NAME",
    "DEFAULT_RESEARCH_INTELLIGENCE_STORAGE_PATH",
    "RESEARCH_INTELLIGENCE_RUNTIME_VERSION",
    "RESEARCH_INTELLIGENCE_SCHEMA_VERSION",
    "build_research_intelligence_snapshot",
    "get_research_intelligence_snapshot_for_dashboard",
    "DEFAULT_UNIVERSAL_MARKET_FRAMEWORK_ARTIFACT_ROOT",
    "NFL_REFERENCE_PROFILE_ID",
    "UNIVERSAL_MARKET_FRAMEWORK_RUNTIME_VERSION",
    "UNIVERSAL_MARKET_FRAMEWORK_SCHEMA_VERSION",
    "build_universal_market_framework_snapshot",
    "get_universal_market_framework_snapshot_for_dashboard",
    "DEFAULT_MARKET_PROFILE_CATALOG",
    "NFL_AS_SPORTS_PROFILE_INSTANCE",
    "OPTIONS_0DTE_PROFILE",
    "PREDICTION_MARKET_PROFILE",
    "SPORTS_PROFILE",
    "build_market_profile_catalog",
    "get_market_profile_catalog_entry",
    "register_default_market_profiles",
    "validate_market_profile_catalog",
]
