from __future__ import annotations

from typing import Any

from .activation_tiers import tier_allows_active_scoring, tier_allows_review_queue, tier_allows_stake_sizing


def _make_item(
    *,
    model_id: str,
    model_name: str,
    model_family: str,
    model_purpose: str,
    market_type: str,
    time_horizon: str,
    activation_tier: str,
    owner: str,
    inputs_required: list[str],
    outputs_produced: list[str],
    assumptions: list[str],
    limitations: list[str],
    evidence_score: float,
    input_quality_score: float,
    calibration_score: float,
    backtest_score: float,
    walk_forward_score: float,
    drift_score: float,
    risk_score: float,
    governance_score: float,
) -> dict[str, Any]:
    return {
        "model_id": model_id,
        "model_name": model_name,
        "model_family": model_family,
        "model_purpose": model_purpose,
        "market_type": market_type,
        "time_horizon": time_horizon,
        "activation_tier": activation_tier,
        "owner": owner,
        "inputs_required": inputs_required,
        "outputs_produced": outputs_produced,
        "assumptions": assumptions,
        "limitations": limitations,
        "evidence_score": evidence_score,
        "input_quality_score": input_quality_score,
        "calibration_score": calibration_score,
        "backtest_score": backtest_score,
        "walk_forward_score": walk_forward_score,
        "drift_score": drift_score,
        "risk_score": risk_score,
        "governance_score": governance_score,
        "can_affect_review_queue": tier_allows_review_queue(activation_tier),
        "can_affect_stake_sizing": tier_allows_stake_sizing(activation_tier),
        "can_affect_alerts": tier_allows_review_queue(activation_tier),
        "can_affect_final_decision": tier_allows_stake_sizing(activation_tier),
        "human_approval_required": True,
    }


_INVENTORY: list[dict[str, Any]] = [
    _make_item(
        model_id="sportsbook_side_total",
        model_name="Sportsbook Side Total Model",
        model_family="sportsbook_models",
        model_purpose="probability_estimation",
        market_type="sportsbook",
        time_horizon="same_day",
        activation_tier="active_scoring_ready",
        owner="sports_research",
        inputs_required=["market", "selection", "odds_american", "player", "opponent"],
        outputs_produced=["true_probability", "edge", "confidence"],
        assumptions=["Market features are present.", "Odds do not set true probability directly."],
        limitations=["Cannot bypass review gates.", "Needs fresh pricing inputs."],
        evidence_score=86,
        input_quality_score=85,
        calibration_score=84,
        backtest_score=83,
        walk_forward_score=81,
        drift_score=80,
        risk_score=82,
        governance_score=85,
    ),
    _make_item(
        model_id="sportsbook_player_props",
        model_name="Sportsbook Player Props Model",
        model_family="sportsbook_models",
        model_purpose="prop_projection",
        market_type="sportsbook",
        time_horizon="same_day",
        activation_tier="review_queue_ready",
        owner="sports_research",
        inputs_required=["market", "selection", "player_prop_line", "odds_american"],
        outputs_produced=["projection", "edge", "confidence"],
        assumptions=["Projection inputs are complete."],
        limitations=["Prop data quality can be unstable."],
        evidence_score=80,
        input_quality_score=79,
        calibration_score=78,
        backtest_score=77,
        walk_forward_score=76,
        drift_score=75,
        risk_score=79,
        governance_score=80,
    ),
    _make_item(
        model_id="stock_event_alpha",
        model_name="Stock Event Alpha Model",
        model_family="stock_models",
        model_purpose="event_alpha",
        market_type="stocks",
        time_horizon="swing",
        activation_tier="paper_trade_ready",
        owner="market_research",
        inputs_required=["symbol", "price", "volume", "event_severity"],
        outputs_produced=["directional_score", "risk_adjusted_return"],
        assumptions=["Event metadata is timely."],
        limitations=["Event drift can invalidate prior patterns."],
        evidence_score=78,
        input_quality_score=77,
        calibration_score=74,
        backtest_score=75,
        walk_forward_score=72,
        drift_score=73,
        risk_score=74,
        governance_score=76,
    ),
    _make_item(
        model_id="stock_execution_cost",
        model_name="Stock Execution Cost Model",
        model_family="stock_models",
        model_purpose="execution_cost",
        market_type="stocks",
        time_horizon="intraday",
        activation_tier="review_queue_ready",
        owner="market_research",
        inputs_required=["order_size", "average_daily_volume", "bid_ask_spread", "volatility"],
        outputs_produced=["estimated_cost", "execution_risk"],
        assumptions=["Liquidity metrics are representative."],
        limitations=["Stress conditions can widen costs."],
        evidence_score=82,
        input_quality_score=81,
        calibration_score=80,
        backtest_score=81,
        walk_forward_score=78,
        drift_score=79,
        risk_score=83,
        governance_score=84,
    ),
    _make_item(
        model_id="prediction_market_pricing",
        model_name="Prediction Market Pricing Model",
        model_family="prediction_market_models",
        model_purpose="pricing_dislocation",
        market_type="prediction_markets",
        time_horizon="same_day",
        activation_tier="review_queue_ready",
        owner="prediction_research",
        inputs_required=["market_price", "sportsbook_price", "resolution_rules"],
        outputs_produced=["fair_value_gap", "settlement_risk"],
        assumptions=["Resolution rules are known."],
        limitations=["Rule mismatches can dominate the edge."],
        evidence_score=81,
        input_quality_score=80,
        calibration_score=78,
        backtest_score=79,
        walk_forward_score=77,
        drift_score=76,
        risk_score=80,
        governance_score=82,
    ),
    _make_item(
        model_id="prediction_market_settlement",
        model_name="Prediction Market Settlement Monitor",
        model_family="prediction_market_models",
        model_purpose="settlement_validation",
        market_type="prediction_markets",
        time_horizon="event",
        activation_tier="paper_trade_ready",
        owner="prediction_research",
        inputs_required=["resolution_rules", "market_identity_confidence", "timestamp"],
        outputs_produced=["settlement_confidence", "mismatch_flag"],
        assumptions=["Rules text is current."],
        limitations=["Ambiguous resolutions need human review."],
        evidence_score=79,
        input_quality_score=78,
        calibration_score=75,
        backtest_score=74,
        walk_forward_score=73,
        drift_score=74,
        risk_score=80,
        governance_score=81,
    ),
    _make_item(
        model_id="institutional_portfolio_construction",
        model_name="Institutional Portfolio Construction Library",
        model_family="institutional_investment_models",
        model_purpose="allocation",
        market_type="stocks",
        time_horizon="long_term",
        activation_tier="research_only",
        owner="institutional_research",
        inputs_required=["expected_returns", "volatility_estimates", "constraints", "asset_universe"],
        outputs_produced=["portfolio_weights", "expected_return", "expected_volatility"],
        assumptions=["Long-horizon estimates are documented."],
        limitations=["Not suitable for short-term trade recommendations."],
        evidence_score=88,
        input_quality_score=72,
        calibration_score=0,
        backtest_score=0,
        walk_forward_score=0,
        drift_score=0,
        risk_score=75,
        governance_score=70,
    ),
    _make_item(
        model_id="institutional_factor_risk",
        model_name="Institutional Factor Risk Library",
        model_family="institutional_investment_models",
        model_purpose="risk_attribution",
        market_type="stocks",
        time_horizon="long_term",
        activation_tier="research_only",
        owner="institutional_research",
        inputs_required=["factor_loadings", "factor_returns", "portfolio_weights", "benchmark_weights"],
        outputs_produced=["factor_exposures", "tracking_error", "concentration_risk"],
        assumptions=["Factor mappings are coherent."],
        limitations=["Does not create trade recommendations."],
        evidence_score=86,
        input_quality_score=74,
        calibration_score=0,
        backtest_score=0,
        walk_forward_score=0,
        drift_score=0,
        risk_score=78,
        governance_score=72,
    ),
    _make_item(
        model_id="institutional_liability",
        model_name="Institutional Liability Library",
        model_family="institutional_investment_models",
        model_purpose="liability_alignment",
        market_type="retirement_portfolio",
        time_horizon="retirement",
        activation_tier="research_only",
        owner="institutional_research",
        inputs_required=["asset_value", "liability_value", "duration_gap", "withdrawal_rate"],
        outputs_produced=["funding_ratio", "liability_match_score", "retirement_survival_score"],
        assumptions=["Liabilities are measurable."],
        limitations=["Cannot create short-term trading outputs."],
        evidence_score=85,
        input_quality_score=73,
        calibration_score=0,
        backtest_score=0,
        walk_forward_score=0,
        drift_score=0,
        risk_score=79,
        governance_score=74,
    ),
    _make_item(
        model_id="cross_book_ev_engine",
        model_name="Cross-Book EV Engine",
        model_family="cross_book_models",
        model_purpose="positive_ev",
        market_type="sportsbook",
        time_horizon="same_day",
        activation_tier="active_scoring_ready",
        owner="pricing_research",
        inputs_required=["books_compared", "best_odds", "model_probability", "market_identity_confidence"],
        outputs_produced=["ev_percent", "best_book", "book_disagreement_score"],
        assumptions=["Line mapping is correct."],
        limitations=["Stale prices can invalidate the signal."],
        evidence_score=84,
        input_quality_score=83,
        calibration_score=82,
        backtest_score=81,
        walk_forward_score=80,
        drift_score=78,
        risk_score=81,
        governance_score=84,
    ),
    _make_item(
        model_id="cross_book_arbitrage_engine",
        model_name="Cross-Book Arbitrage Engine",
        model_family="cross_book_models",
        model_purpose="arbitrage_detection",
        market_type="sportsbook",
        time_horizon="same_day",
        activation_tier="review_queue_ready",
        owner="pricing_research",
        inputs_required=["books_compared", "best_odds", "worst_odds", "settlement_rules"],
        outputs_produced=["arbitrage_implied_sum", "stake_plan", "settlement_risk"],
        assumptions=["Settlement rules are aligned."],
        limitations=["Execution and timing risk remain material."],
        evidence_score=82,
        input_quality_score=81,
        calibration_score=79,
        backtest_score=80,
        walk_forward_score=78,
        drift_score=77,
        risk_score=80,
        governance_score=83,
    ),
    _make_item(
        model_id="cross_book_middle_engine",
        model_name="Cross-Book Middle Engine",
        model_family="cross_book_models",
        model_purpose="middle_detection",
        market_type="sportsbook",
        time_horizon="same_day",
        activation_tier="review_queue_ready",
        owner="pricing_research",
        inputs_required=["books_compared", "best_line", "worst_line", "break_even_probability"],
        outputs_produced=["middle_width", "estimated_ev", "max_loss"],
        assumptions=["Line identity is correct."],
        limitations=["Middle probability estimates can be noisy."],
        evidence_score=80,
        input_quality_score=79,
        calibration_score=78,
        backtest_score=76,
        walk_forward_score=75,
        drift_score=74,
        risk_score=79,
        governance_score=82,
    ),
    _make_item(
        model_id="kelly_primary_staking",
        model_name="Kelly Primary Staking Model",
        model_family="kelly_models",
        model_purpose="stake_sizing",
        market_type="multi_market",
        time_horizon="same_day",
        activation_tier="production_candidate",
        owner="risk_research",
        inputs_required=["edge", "odds_decimal", "confidence", "drawdown_risk"],
        outputs_produced=["operating_full_kelly_fraction", "fractional_fallback_fraction", "recommended_kelly_mode"],
        assumptions=["Edge is governed upstream."],
        limitations=["Never implies auto-execution."],
        evidence_score=88,
        input_quality_score=87,
        calibration_score=85,
        backtest_score=84,
        walk_forward_score=83,
        drift_score=82,
        risk_score=86,
        governance_score=88,
    ),
    _make_item(
        model_id="kelly_fractional_safety",
        model_name="Kelly Fractional Safety Model",
        model_family="kelly_models",
        model_purpose="stake_sizing",
        market_type="multi_market",
        time_horizon="same_day",
        activation_tier="active_scoring_ready",
        owner="risk_research",
        inputs_required=["edge", "odds_decimal", "confidence"],
        outputs_produced=["fractional_fallback_fraction", "recommended_kelly_mode"],
        assumptions=["Confidence is bounded."],
        limitations=["Requires human approval."],
        evidence_score=86,
        input_quality_score=85,
        calibration_score=82,
        backtest_score=81,
        walk_forward_score=80,
        drift_score=79,
        risk_score=85,
        governance_score=87,
    ),
    _make_item(
        model_id="automation_scheduler_monitors",
        model_name="Automation Scheduler Monitor Suite",
        model_family="automation_models",
        model_purpose="monitoring",
        market_type="multi_market",
        time_horizon="continuous",
        activation_tier="paper_trade_ready",
        owner="platform_ops",
        inputs_required=["provider_snapshots", "market_type", "timestamp"],
        outputs_produced=["candidates", "health_status", "review_queue_items"],
        assumptions=["Placeholder feeds are injected cleanly."],
        limitations=["Does not place bets or trades."],
        evidence_score=76,
        input_quality_score=78,
        calibration_score=72,
        backtest_score=71,
        walk_forward_score=70,
        drift_score=74,
        risk_score=80,
        governance_score=82,
    ),
    _make_item(
        model_id="automation_model_recheck_runner",
        model_name="Automation Model Recheck Runner",
        model_family="automation_models",
        model_purpose="model_recheck",
        market_type="multi_market",
        time_horizon="continuous",
        activation_tier="backtest_ready",
        owner="platform_ops",
        inputs_required=["model_inputs", "market_type", "required_fields"],
        outputs_produced=["recheck_status", "missing_inputs", "quality_summary"],
        assumptions=["Required inputs are known."],
        limitations=["Cannot confirm from enrichment-only data."],
        evidence_score=74,
        input_quality_score=77,
        calibration_score=70,
        backtest_score=70,
        walk_forward_score=0,
        drift_score=0,
        risk_score=79,
        governance_score=80,
    ),
]


def get_model_inventory() -> list[dict[str, Any]]:
    return [dict(item) for item in _INVENTORY]


def get_model_inventory_map() -> dict[str, dict[str, Any]]:
    return {item["model_id"]: dict(item) for item in _INVENTORY}


def get_model_by_id(model_id: str) -> dict[str, Any]:
    return get_model_inventory_map()[model_id]


def inventory_counts() -> dict[str, int]:
    counts = {
        "model_inventory_count": len(_INVENTORY),
        "research_only_count": 0,
        "backtest_ready_count": 0,
        "paper_trade_ready_count": 0,
        "review_queue_ready_count": 0,
        "active_scoring_ready_count": 0,
        "production_candidate_count": 0,
    }
    for item in _INVENTORY:
        counts[f"{item['activation_tier']}_count"] += 1
    return counts
