"""Canonical provider landing zone for future migration batches.

This package is intentionally scaffold-only for now. It defines stable
provider contracts, registry, health, normalization, validation, and policy
interfaces without depending on legacy provider ownership.
"""

from .base import ProviderAdapterBase, ProviderAdapterProtocol
from .contracts import (
    ProviderAdapterContract,
    PROVIDER_CONTRACT_SCHEMA_VERSION,
    PROVIDER_SCHEMA_VERSION,
    PROVIDER_TYPES,
    ProviderContract,
    ReadOnlyProviderContract,
    build_provider_contract,
    build_scaffold_provider_contract,
    ensure_provider_runtime_directories,
    get_default_provider_contracts,
    write_provider_contract_snapshot,
)
from .errors import ProviderConfigurationError, ProviderError, ProviderResponseError, ProviderUnavailableError
from .health import ProviderHealthStatus, build_scaffold_health_status, compact_provider_health, summarize_provider_health, write_provider_health_snapshot
from .normalization import NORMALIZED_SCHEMAS, get_normalized_schema, normalize_provider_payload
from .policy import (
    ALLOWED_AI_PROVIDERS,
    BROKER_PROVIDER_HINTS,
    CRYPTO_EXCHANGE_HINTS,
    DEFAULT_AI_PROVIDER,
    FORBIDDEN_AI_PROVIDER_TYPES,
    MARKET_ORDER_PROVIDER_HINTS,
    SPORTSBOOK_PROVIDER_HINTS,
    ProviderWriteFirewallPolicy,
    ProviderWritePolicy,
    assert_no_secret_leak,
    build_scaffold_provider_write_policy,
    build_scaffold_write_firewall_policy,
    classify_provider,
    credential_status_from_env,
    is_allowed_ai_provider_name,
    is_internal_deterministic_provider,
    list_required_secret_names,
    normalize_provider_name,
    provider_allowlist_response,
    redact_http_diagnostic,
    redact_mapping,
    redact_secret,
)
from .prediction_markets import (
    ADAPTER_PREDICTION_MARKET_PROVIDER_TYPE,
    PREDICTION_MARKET_PROVIDER_TYPE,
    PredictionMarketEventQuote,
    PredictionMarketProviderAdapter,
    PredictionMarketProviderContract,
    PredictionMarketQuote,
    build_prediction_market_event_quote,
    build_prediction_market_provider_contract,
    build_prediction_market_quote,
    build_prediction_market_snapshot,
    normalize_prediction_market_event,
    normalize_prediction_market_payload,
    normalize_prediction_market_quote,
    normalize_prediction_market_snapshot,
    validate_prediction_market_payload,
)
from .registry import ProviderRegistry, create_provider_registry, get_provider, get_provider_registry, provider_min_interval_seconds
from .sportsbooks import (
    ADAPTER_SPORTSBOOK_PROVIDER_TYPE,
    SPORTSBOOK_PROVIDER_TYPE,
    SAMPLE_DRY_RUN_PAYLOAD as SPORTSBOOK_SAMPLE_DRY_RUN_PAYLOAD,
    SportsbookEventQuote,
    SportsbookProviderAdapter,
    SportsbookProviderContract,
    SportsbookQuote,
    build_sportsbook_event_quote,
    build_sportsbook_provider_contract,
    build_sportsbook_quote,
    normalize_sportsbook_event,
    normalize_sportsbook_payload,
    normalize_sportsbook_odds,
    normalize_sportsbook_quote,
    validate_sportsbook_payload,
)
from .validation import validate_provider_payload
from .validation import ProviderPayloadValidator
from .zero_dte_stocks import (
    ADAPTER_ZERO_DTE_STOCK_PROVIDER_TYPE,
    SAMPLE_DRY_RUN_PAYLOAD as ZERO_DTE_STOCK_SAMPLE_DRY_RUN_PAYLOAD,
    ZERO_DTE_STOCK_PROVIDER_TYPE,
    ZeroDteStockProviderAdapter,
    ZeroDteStockProviderContract,
    ZeroDteStockQuote,
    build_zero_dte_stock_quote,
    build_zero_dte_stock_provider_contract,
    normalize_zero_dte_stock_payload,
    normalize_zero_dte_stock_quote,
    validate_zero_dte_stock_payload,
)

__all__ = [
    "ALLOWED_AI_PROVIDERS",
    "BROKER_PROVIDER_HINTS",
    "CRYPTO_EXCHANGE_HINTS",
    "DEFAULT_AI_PROVIDER",
    "FORBIDDEN_AI_PROVIDER_TYPES",
    "NORMALIZED_SCHEMAS",
    "PROVIDER_SCHEMA_VERSION",
    "PROVIDER_CONTRACT_SCHEMA_VERSION",
    "PROVIDER_TYPES",
    "ProviderAdapterBase",
    "ProviderAdapterProtocol",
    "ProviderAdapterContract",
    "ProviderConfigurationError",
    "ProviderContract",
    "ProviderError",
    "ProviderHealthStatus",
    "ProviderPayloadValidator",
    "ProviderRegistry",
    "ProviderResponseError",
    "ProviderUnavailableError",
    "ProviderWriteFirewallPolicy",
    "ProviderWritePolicy",
    "MARKET_ORDER_PROVIDER_HINTS",
    "build_scaffold_health_status",
    "build_scaffold_provider_contract",
    "build_scaffold_provider_write_policy",
    "build_scaffold_write_firewall_policy",
    "build_provider_contract",
    "classify_provider",
    "compact_provider_health",
    "create_provider_registry",
    "credential_status_from_env",
    "ensure_provider_runtime_directories",
    "get_default_provider_contracts",
    "get_normalized_schema",
    "get_provider",
    "get_provider_registry",
    "is_allowed_ai_provider_name",
    "is_internal_deterministic_provider",
    "list_required_secret_names",
    "normalize_provider_name",
    "normalize_provider_payload",
    "PREDICTION_MARKET_PROVIDER_TYPE",
    "PredictionMarketProviderContract",
    "provider_allowlist_response",
    "provider_min_interval_seconds",
    "redact_http_diagnostic",
    "redact_mapping",
    "redact_secret",
    "summarize_provider_health",
    "validate_provider_payload",
    "write_provider_contract_snapshot",
    "write_provider_health_snapshot",
    "SPORTSBOOK_PROVIDER_TYPE",
    "SportsbookProviderContract",
    "build_prediction_market_provider_contract",
    "build_sportsbook_provider_contract",
    "normalize_prediction_market_payload",
    "normalize_sportsbook_payload",
    "validate_prediction_market_payload",
    "validate_sportsbook_payload",
    "ZERO_DTE_STOCK_PROVIDER_TYPE",
    "ZeroDteStockProviderContract",
    "build_zero_dte_stock_provider_contract",
    "normalize_zero_dte_stock_payload",
    "validate_zero_dte_stock_payload",
    "SPORTSBOOK_SAMPLE_DRY_RUN_PAYLOAD",
    "ZERO_DTE_STOCK_SAMPLE_DRY_RUN_PAYLOAD",
    "ADAPTER_PREDICTION_MARKET_PROVIDER_TYPE",
    "PredictionMarketEventQuote",
    "PredictionMarketProviderAdapter",
    "PredictionMarketQuote",
    "build_prediction_market_event_quote",
    "build_prediction_market_quote",
    "build_prediction_market_snapshot",
    "normalize_prediction_market_event",
    "normalize_prediction_market_quote",
    "normalize_prediction_market_snapshot",
    "ADAPTER_SPORTSBOOK_PROVIDER_TYPE",
    "SportsbookEventQuote",
    "SportsbookProviderAdapter",
    "SportsbookQuote",
    "build_sportsbook_event_quote",
    "build_sportsbook_quote",
    "normalize_sportsbook_event",
    "normalize_sportsbook_odds",
    "normalize_sportsbook_quote",
    "ADAPTER_ZERO_DTE_STOCK_PROVIDER_TYPE",
    "ZeroDteStockProviderAdapter",
    "ZeroDteStockQuote",
    "build_zero_dte_stock_quote",
    "normalize_zero_dte_stock_quote",
]
