from __future__ import annotations

from pathlib import Path
from typing import Any

from .combat_api_docs_parser import evaluate_combat_api_docs
from .combat_license_parser import evaluate_combat_license
from .combat_policy_classifier import classify_combat_source
from .combat_robots_checker import evaluate_combat_robots
from .combat_terms_parser import evaluate_combat_terms
from .combat_oxylabs_common import (
    OPEN_BOXING_API_URL,
    OPEN_BOXING_BOUTS_URL,
    OPEN_BOXING_LICENSE_URL,
    OPEN_BOXING_README_URL,
    REPORT_ROOT,
    RUN_MODE,
    current_utc,
    fetch_public_page_text,
    stable_hash,
    url_hash,
    write_json,
    write_md,
)


def _candidate(
    source_id: str,
    field_group: str,
    source_name: str,
    source_domain: str,
    source_url: str,
    *,
    source_type: str,
    policy_mode: str,
    prior_status: str,
    reason_for_recheck: str,
    expected_calibration_value: str,
    expected_backfill_value: str,
    target_final_decision: str,
    final_state_target: str,
    source_path_or_path_pattern: str | None = None,
    terms_url: str = "",
    license_url: str = "",
    robots_url: str = "",
    api_docs_url: str = "",
    data_dictionary_url: str = "",
    github_license_url: str = "",
    readme_url: str = "",
    attribution_url: str = "",
    acceptable_use_url: str = "",
    primary_transport: str = "web_scraper_api",
    sample_strategy: str = "none",
    sample_url: str = "",
    normalized_entity_level: str = "source",
    repo_field_mapping: list[str] | None = None,
    new_fields_recommended: list[str] | None = None,
    sport_model_relevance: str = "medium",
    duplicate_existing_source: bool = False,
    upstream_source_unclear: bool = False,
    login_required: bool = False,
    paywall_required: bool = False,
    captcha_required: bool = False,
    session_required: bool = False,
    timestamp_available: bool = True,
    event_time_available: bool = True,
    game_or_match_start_time_available: bool = True,
    data_publication_time_available: bool = True,
    future_leakage_risk: str = "low_if_joined_before_decision_time",
    post_event_only: bool = False,
    pre_event_available: bool = True,
    usable_for_prematch_model: bool = True,
    usable_for_postmatch_training_only: bool = False,
    cutoff_safe: bool = True,
    cutoff_safety_reason: str = "normalized facts joined against historical timestamps only",
    normalized_fact_persistence_allowed: bool = False,
    aggregate_feature_persistence_allowed: bool = False,
    exact_blocker_or_allowance: str = "",
) -> dict[str, Any]:
    return {
        "sport": "combat",
        "sport_group": "combat",
        "field_group": field_group,
        "source_id": source_id,
        "source_name": source_name,
        "source_domain": source_domain,
        "source_url": source_url,
        "source_path_or_path_pattern": source_path_or_path_pattern or source_url,
        "source_type": source_type,
        "source_owner_if_known": source_name,
        "mirror_or_original_source": "original",
        "likely_upstream_source": source_name,
        "public_or_private": "public",
        "policy_mode": policy_mode,
        "prior_status": prior_status,
        "prior_report_source": "first_combat_finality_pass",
        "reason_for_recheck": reason_for_recheck,
        "policy_review_required": True,
        "expected_calibration_value": expected_calibration_value,
        "expected_backfill_value": expected_backfill_value,
        "target_final_decision": target_final_decision,
        "final_state_target": final_state_target,
        "login_required": login_required,
        "paywall_required": paywall_required,
        "captcha_required": captcha_required,
        "session_required": session_required,
        "terms_url": terms_url,
        "privacy_url": "",
        "license_url": license_url,
        "robots_url": robots_url,
        "api_docs_url": api_docs_url,
        "data_dictionary_url": data_dictionary_url,
        "GitHub_LICENSE_url": github_license_url,
        "README_url": readme_url,
        "attribution_url": attribution_url,
        "acceptable_use_url": acceptable_use_url,
        "copyright_notice_url": "",
        "primary_transport": primary_transport,
        "sample_strategy": sample_strategy,
        "sample_url": sample_url,
        "normalized_entity_level": normalized_entity_level,
        "repo_field_mapping": list(repo_field_mapping or []),
        "new_fields_recommended": list(new_fields_recommended or []),
        "sport_model_relevance": sport_model_relevance,
        "duplicate_existing_source": duplicate_existing_source,
        "upstream_source_unclear": upstream_source_unclear,
        "timestamp_available": timestamp_available,
        "event_time_available": event_time_available,
        "game_or_match_start_time_available": game_or_match_start_time_available,
        "data_publication_time_available": data_publication_time_available,
        "future_leakage_risk": future_leakage_risk,
        "post_event_only": post_event_only,
        "pre_event_available": pre_event_available,
        "usable_for_prematch_model": usable_for_prematch_model,
        "usable_for_postmatch_training_only": usable_for_postmatch_training_only,
        "cutoff_safe": cutoff_safe,
        "cutoff_safety_reason": cutoff_safety_reason,
        "normalized_fact_persistence_allowed": normalized_fact_persistence_allowed,
        "aggregate_feature_persistence_allowed": aggregate_feature_persistence_allowed,
        "source_hash_persistence_allowed": True,
        "fields_available": list(repo_field_mapping or []),
        "attribution_storage_required": bool(attribution_url),
        "required_attribution_text_or_url_hash": url_hash(attribution_url or source_url),
        "exact_blocker_or_allowance": exact_blocker_or_allowance,
    }


def combat_candidate_source_catalog() -> list[dict[str, Any]]:
    return [
        _candidate(
            "combat_open_boxing_data_repo",
            "boxing historical bouts, titles, champions, and location tables",
            "Open Boxing data repository",
            "github.com",
            "https://github.com/edhwright/open-boxing/tree/main/src/db/data",
            source_type="open_csv_dataset",
            policy_mode="automated_backfill",
            prior_status="free_open_loader_needed",
            reason_for_recheck="Open Boxing is the strongest visible public boxing dataset and needed exact path-level policy review.",
            expected_calibration_value="high",
            expected_backfill_value="high",
            target_final_decision="accepted_for_automated_normalized_backfill",
            final_state_target="free_open_backfilled",
            terms_url="https://github.com/edhwright/open-boxing",
            license_url=OPEN_BOXING_LICENSE_URL,
            robots_url="https://github.com/robots.txt",
            api_docs_url=OPEN_BOXING_API_URL,
            data_dictionary_url=OPEN_BOXING_API_URL,
            github_license_url=OPEN_BOXING_LICENSE_URL,
            readme_url=OPEN_BOXING_README_URL,
            attribution_url="https://github.com/edhwright/open-boxing",
            primary_transport="web_scraper_api",
            sample_strategy="csv_rows",
            sample_url=OPEN_BOXING_BOUTS_URL,
            normalized_entity_level="bout",
            repo_field_mapping=["bout_id", "date", "boxer_a_name", "boxer_b_name", "winner", "method_of_victory", "scheduled_rounds", "weight_class", "champion_id", "born", "reign_id", "title", "venue", "country"],
            new_fields_recommended=["inside_distance_flag", "sanctioning_body_abbreviation", "country_code_normalized"],
            sport_model_relevance="high",
            post_event_only=True,
            pre_event_available=False,
            usable_for_prematch_model=False,
            usable_for_postmatch_training_only=True,
            cutoff_safe=True,
            cutoff_safety_reason="Historical normalized boxing facts are safe when joined to historical bout timestamps only.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            exact_blocker_or_allowance="MIT-licensed Open Boxing repository and public API/docs allow normalized boxing backfill within this pass.",
        ),
        _candidate(
            "combat_wikidata_fighter_entities",
            "fighter identity and structured metadata",
            "Wikidata combat sports fighter entities",
            "wikidata.org",
            "https://www.wikidata.org/wiki/Wikidata:Main_Page",
            source_type="structured_open_metadata",
            policy_mode="metadata_only",
            prior_status="free_open_partial",
            reason_for_recheck="Metadata-only entities help alias normalization and fighter identity supplementation.",
            expected_calibration_value="low",
            expected_backfill_value="low",
            target_final_decision="accepted_for_metadata_only",
            final_state_target="free_open_metadata_only",
            terms_url="https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Terms_of_Use",
            license_url="https://www.wikidata.org/wiki/Wikidata:Licensing",
            robots_url="https://www.wikidata.org/robots.txt",
            api_docs_url="https://www.wikidata.org/w/api.php",
            data_dictionary_url="https://www.wikidata.org/wiki/Wikidata:Data_access",
            attribution_url="https://www.wikidata.org/wiki/Wikidata:Licensing",
            normalized_entity_level="fighter",
            repo_field_mapping=["entity_name", "country", "birth_date", "wikidata_id"],
            new_fields_recommended=["entity_alias_hash", "country_code_normalized"],
            sport_model_relevance="medium",
            normalized_fact_persistence_allowed=True,
            exact_blocker_or_allowance="Structured fighter metadata is allowed for attribution-preserving metadata-only use.",
        ),
        _candidate(
            "combat_wikipedia_combat_entities",
            "promotion and roster metadata",
            "Wikipedia combat sports entity tables",
            "wikipedia.org",
            "https://en.wikipedia.org/wiki/List_of_current_UFC_fighters",
            source_type="structured_open_metadata",
            policy_mode="metadata_only",
            prior_status="free_open_partial",
            reason_for_recheck="Wikipedia tables are only suitable as supplemental metadata and needed an explicit final state.",
            expected_calibration_value="low",
            expected_backfill_value="low",
            target_final_decision="accepted_for_metadata_only",
            final_state_target="free_open_metadata_only",
            terms_url="https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Terms_of_Use",
            license_url="https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License",
            robots_url="https://en.wikipedia.org/robots.txt",
            attribution_url="https://en.wikipedia.org/wiki/List_of_current_UFC_fighters",
            normalized_entity_level="promotion_fighter",
            repo_field_mapping=["promotion_name", "fighter_name", "country", "roster_note"],
            new_fields_recommended=["promotion_slug", "fighter_name_slug"],
            sport_model_relevance="low",
            normalized_fact_persistence_allowed=True,
            exact_blocker_or_allowance="Wikipedia tables remain metadata-only supplemental sources with attribution retained.",
        ),
        _candidate(
            "combat_ufc_official_weighins",
            "official weigh-in results and missed-weight news",
            "UFC official weigh-in and news pages",
            "ufc.com",
            "https://www.ufc.com/events",
            source_type="official_news_page",
            policy_mode="manual_only",
            prior_status="free_open_manual_import_needed",
            reason_for_recheck="Weigh-in context is valuable but required exact source-specific policy review before any automation.",
            expected_calibration_value="high",
            expected_backfill_value="moderate",
            target_final_decision="accepted_for_manual_import_only",
            final_state_target="manual_import_required",
            terms_url="https://www.ufc.com/termsOfUse",
            license_url="https://www.ufc.com/termsOfUse",
            robots_url="https://www.ufc.com/robots.txt",
            attribution_url="https://www.ufc.com/events",
            normalized_entity_level="fighter_event",
            repo_field_mapping=["weigh_in_status", "missed_weight_flag", "official_weight", "observed_at"],
            sport_model_relevance="high",
            exact_blocker_or_allowance="UFC terms prohibit automated systems on the service, so official weigh-in use remains manual-only here.",
        ),
        _candidate(
            "combat_ufc_official_event_pages",
            "official event, cancellation, and availability pages",
            "UFC official event pages",
            "ufc.com",
            "https://www.ufc.com/events",
            source_type="official_event_page",
            policy_mode="manual_only",
            prior_status="free_open_manual_import_needed",
            reason_for_recheck="Official UFC event pages were checked for event, availability, and cancellation context.",
            expected_calibration_value="high",
            expected_backfill_value="moderate",
            target_final_decision="accepted_for_manual_import_only",
            final_state_target="manual_import_required",
            terms_url="https://www.ufc.com/termsOfUse",
            license_url="https://www.ufc.com/termsOfUse",
            robots_url="https://www.ufc.com/robots.txt",
            attribution_url="https://www.ufc.com/events",
            normalized_entity_level="event_bout",
            repo_field_mapping=["injury_status", "withdrawal_note", "availability_status", "short_notice_flag", "opponent_change_context", "cancellation_note", "observed_at"],
            sport_model_relevance="high",
            exact_blocker_or_allowance="Official UFC event pages remain manual-only because automated systems are restricted and timestamp review is required.",
        ),
        _candidate(
            "combat_commission_medical_records",
            "commission suspensions and officiating records",
            "State athletic commission public records",
            "dca.ca.gov",
            "https://www.dca.ca.gov/csac/",
            source_type="official_commission_page",
            policy_mode="manual_only",
            prior_status="free_open_manual_import_needed",
            reason_for_recheck="Commission records were checked for suspensions and officials context.",
            expected_calibration_value="moderate",
            expected_backfill_value="low",
            target_final_decision="accepted_for_manual_import_only",
            final_state_target="manual_import_required",
            terms_url="https://www.dca.ca.gov/csac/",
            license_url="https://www.dca.ca.gov/csac/",
            robots_url="https://www.dca.ca.gov/robots.txt",
            attribution_url="https://www.dca.ca.gov/csac/",
            normalized_entity_level="fighter_event_or_officials",
            repo_field_mapping=["medical_suspension_context", "suspension_days", "commission_name", "referee_name", "judge_names", "observed_at"],
            sport_model_relevance="medium",
            exact_blocker_or_allowance="Commission records can support timestamped manual imports, but not automated normalized extraction in this pass.",
        ),
        _candidate(
            "combat_ufcstats_round_stats",
            "ufcstats event/fighter/bout detail paths",
            "UFC Stats event, fighter, and bout detail pages",
            "ufcstats.com",
            "http://ufcstats.com/statistics/events/completed?page=all",
            source_type="official_stats_page",
            policy_mode="blocked",
            prior_status="free_open_loader_needed",
            reason_for_recheck="UFC/MMA core striking/grappling lanes needed exact-path policy review and a non-vague final state.",
            expected_calibration_value="very_high",
            expected_backfill_value="very_high",
            target_final_decision="rejected_policy_blocked",
            final_state_target="policy_blocked",
            terms_url="https://www.ufc.com/termsOfUse",
            license_url="https://www.ufc.com/termsOfUse",
            robots_url="http://ufcstats.com/robots.txt",
            attribution_url="http://ufcstats.com/statistics/events/completed?page=all",
            primary_transport="residential_proxy",
            sample_strategy="none",
            normalized_entity_level="bout_or_fighter",
            repo_field_mapping=["fight_date", "scheduled_rounds", "fighter_reach", "fighter_stance", "fighter_strikes_landed_per_min", "fighter_takedown_average", "fighter_submission_average", "finish_round", "finish_time"],
            sport_model_relevance="very_high",
            exact_blocker_or_allowance="No compliant automated extraction path for UFC-owned stats pages was approved in this pass.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "combat_tapology_event_pages",
            "public event and rankings pages",
            "Tapology event and fighter pages",
            "tapology.com",
            "https://www.tapology.com/",
            source_type="reference_site",
            policy_mode="blocked",
            prior_status="policy_blocked",
            reason_for_recheck="Tapology had to be closed into an explicit final policy state for rankings and event context.",
            expected_calibration_value="high",
            expected_backfill_value="moderate",
            target_final_decision="rejected_policy_blocked",
            final_state_target="policy_blocked",
            terms_url="https://www.tapology.com/",
            license_url="https://www.tapology.com/",
            robots_url="https://www.tapology.com/robots.txt",
            attribution_url="https://www.tapology.com/",
            normalized_entity_level="event_or_fighter",
            repo_field_mapping=["ranking_source", "opponent_strength_rating", "event_reference"],
            sport_model_relevance="high",
            exact_blocker_or_allowance="Tapology remains blocked until an exact path is explicitly approved after policy review.",
        ),
        _candidate(
            "combat_sherdog_fighter_pages",
            "public fighter and event pages",
            "Sherdog fighter and event pages",
            "sherdog.com",
            "https://www.sherdog.com/",
            source_type="reference_site",
            policy_mode="blocked",
            prior_status="policy_blocked",
            reason_for_recheck="Sherdog had to be closed into an explicit final policy state for MMA reference context.",
            expected_calibration_value="high",
            expected_backfill_value="moderate",
            target_final_decision="rejected_policy_blocked",
            final_state_target="policy_blocked",
            terms_url="https://www.sherdog.com/",
            license_url="https://www.sherdog.com/",
            robots_url="https://www.sherdog.com/robots.txt",
            attribution_url="https://www.sherdog.com/",
            normalized_entity_level="event_or_fighter",
            repo_field_mapping=["fight_reference", "fighter_reference"],
            sport_model_relevance="high",
            exact_blocker_or_allowance="Sherdog remains blocked until an exact path is explicitly approved after policy review.",
        ),
        _candidate(
            "combat_espn_mma_pages",
            "public mma schedule and stats pages",
            "ESPN MMA pages",
            "espn.com",
            "https://www.espn.com/mma/",
            source_type="reference_site",
            policy_mode="blocked",
            prior_status="policy_blocked",
            reason_for_recheck="ESPN MMA needed an explicit source-specific decision instead of a vague blocked note.",
            expected_calibration_value="moderate",
            expected_backfill_value="low",
            target_final_decision="rejected_policy_blocked",
            final_state_target="policy_blocked",
            terms_url="https://www.espn.com/",
            license_url="https://www.espn.com/",
            robots_url="https://www.espn.com/robots.txt",
            attribution_url="https://www.espn.com/mma/",
            normalized_entity_level="event_or_stats_page",
            repo_field_mapping=["schedule_reference", "stats_reference"],
            sport_model_relevance="moderate",
            exact_blocker_or_allowance="ESPN MMA pages were reviewed but not approved for automated extraction in this pass.",
        ),
        _candidate(
            "combat_boxrec_records",
            "boxing record database pages",
            "BoxRec record pages",
            "boxrec.com",
            "https://boxrec.com/",
            source_type="record_database",
            policy_mode="blocked",
            prior_status="login_paywall_captcha_blocked",
            reason_for_recheck="BoxRec needed an explicit final state for boxing record-depth lanes.",
            expected_calibration_value="high",
            expected_backfill_value="moderate",
            target_final_decision="rejected_login_paywall_captcha",
            final_state_target="login_paywall_captcha_blocked",
            terms_url="https://boxrec.com/cn/policies/terms_conditions/public",
            license_url="https://boxrec.com/cn/policies/terms_conditions/public",
            robots_url="https://boxrec.com/robots.txt",
            attribution_url="https://boxrec.com/",
            login_required=True,
            normalized_entity_level="record_page",
            repo_field_mapping=["pro_record_summary", "title_challenge_count", "last_six_bouts"],
            sport_model_relevance="high",
            exact_blocker_or_allowance="BoxRec is treated as login/terms blocked for automated use in this pass.",
        ),
        _candidate(
            "combat_kaggle_combat_catalog",
            "Kaggle combat dataset catalog",
            "Kaggle combat dataset catalog",
            "kaggle.com",
            "https://www.kaggle.com/datasets?search=ufc%20mma%20boxing",
            source_type="dataset_catalog_page",
            policy_mode="blocked",
            prior_status="login_paywall_captcha_blocked",
            reason_for_recheck="Kaggle had to be closed into an explicit final account-gated state.",
            expected_calibration_value="low",
            expected_backfill_value="low",
            target_final_decision="rejected_login_paywall_captcha",
            final_state_target="login_paywall_captcha_blocked",
            terms_url="https://www.kaggle.com/terms",
            license_url="https://www.kaggle.com/terms",
            robots_url="https://www.kaggle.com/robots.txt",
            login_required=True,
            normalized_entity_level="dataset_catalog",
            repo_field_mapping=["catalog_reference"],
            sport_model_relevance="low",
            exact_blocker_or_allowance="Kaggle catalog access remains account-gated and not suitable for compliant free/open automation.",
        ),
        _candidate(
            "combat_ufc_stats_api_wrapper_repo",
            "GitHub UFC stats wrapper repo",
            "GitHub UFC stats API wrapper repo",
            "github.com",
            "https://github.com/aristotle-malichetty/ufc-stats-api",
            source_type="community_api_wrapper_repo",
            policy_mode="license_unclear",
            prior_status="license_terms_unclear",
            reason_for_recheck="Public wrapper repos had to be rechecked as exact-path legal uncertainty lanes.",
            expected_calibration_value="moderate",
            expected_backfill_value="moderate",
            target_final_decision="license_terms_unclear",
            final_state_target="license_terms_unclear",
            terms_url="https://github.com/aristotle-malichetty/ufc-stats-api",
            license_url="https://raw.githubusercontent.com/aristotle-malichetty/ufc-stats-api/main/LICENSE",
            robots_url="https://github.com/robots.txt",
            api_docs_url="https://github.com/aristotle-malichetty/ufc-stats-api",
            data_dictionary_url="https://github.com/aristotle-malichetty/ufc-stats-api",
            github_license_url="https://raw.githubusercontent.com/aristotle-malichetty/ufc-stats-api/main/LICENSE",
            readme_url="https://github.com/aristotle-malichetty/ufc-stats-api",
            attribution_url="https://github.com/aristotle-malichetty/ufc-stats-api",
            normalized_entity_level="wrapper_repo",
            repo_field_mapping=["wrapper_repo_name", "upstream_source", "license_note", "api_surface_note"],
            sport_model_relevance="medium",
            exact_blocker_or_allowance="The wrapper repo is public, but downstream rights remain unclear because it derives from UFC-owned stats surfaces.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "combat_mma_data_scraper_repo",
            "GitHub MMA data scraper bundle repo",
            "GitHub MMA data scraper bundle repo",
            "github.com",
            "https://github.com/Renaissanc3Man/MMA-Data",
            source_type="community_scraper_repo",
            policy_mode="license_unclear",
            prior_status="license_terms_unclear",
            reason_for_recheck="Community scraper bundles had to be rechecked as exact-path legal uncertainty lanes.",
            expected_calibration_value="moderate",
            expected_backfill_value="moderate",
            target_final_decision="license_terms_unclear",
            final_state_target="license_terms_unclear",
            terms_url="https://github.com/Renaissanc3Man/MMA-Data",
            license_url="https://github.com/Renaissanc3Man/MMA-Data",
            robots_url="https://github.com/robots.txt",
            api_docs_url="https://github.com/Renaissanc3Man/MMA-Data",
            data_dictionary_url="https://github.com/Renaissanc3Man/MMA-Data",
            readme_url="https://github.com/Renaissanc3Man/MMA-Data",
            attribution_url="https://github.com/Renaissanc3Man/MMA-Data",
            normalized_entity_level="scraper_repo",
            repo_field_mapping=["repo_name", "upstream_sources", "scrape_scope", "license_note"],
            sport_model_relevance="medium",
            exact_blocker_or_allowance="The public repo combines scraped UFC, Sherdog, and Wikipedia inputs, so downstream rights remain unclear.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "combat_paid_tracking_vendor",
            "paid tracking and punch-level vendor pages",
            "Paid MMA/boxing tracking vendor page",
            "docs.sportradar.com",
            "https://docs.sportradar.com/ufc-media/schedule-endpoints-restful/results-endpoint",
            source_type="paid_vendor_page",
            policy_mode="paid",
            prior_status="paid_data_subscription_required",
            reason_for_recheck="Paid tracking and microdata surfaces had to be proven still paid after exhausting free/open paths.",
            expected_calibration_value="very_high",
            expected_backfill_value="very_high",
            target_final_decision="rejected_terms_blocked",
            final_state_target="paid_subscription_required",
            terms_url="https://docs.sportradar.com/ufc-media/schedule-endpoints-restful/results-endpoint",
            license_url="https://docs.sportradar.com/ufc-media/schedule-endpoints-restful/results-endpoint",
            robots_url="https://www.sportradar.com/robots.txt",
            api_docs_url="https://docs.sportradar.com/ufc-media/schedule-endpoints-restful/results-endpoint",
            normalized_entity_level="vendor_docs_page",
            repo_field_mapping=["tracking_feed_reference", "round_micro_events", "punch_location_split"],
            sport_model_relevance="very_high",
            exact_blocker_or_allowance="Tracking, punch-level, and broader round microdata remain licensed vendor lanes after exhausting free/open paths.",
            normalized_fact_persistence_allowed=False,
        ),
    ]


def build_combat_candidate_source_policy_inventory(*, candidate_rows: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    candidate_rows = candidate_rows or combat_candidate_source_catalog()
    inventory_rows = [
        {
            "sport": "Combat",
            "source_family": candidate["source_type"],
            "source_name": candidate["source_name"],
            "domain": candidate["source_domain"],
            "source_path_or_path_pattern": candidate["source_path_or_path_pattern"],
            "field_group": candidate["field_group"],
            "prior_status": candidate["prior_status"],
            "prior_report_source": candidate["prior_report_source"],
            "reason_for_recheck": candidate["reason_for_recheck"],
            "policy_review_required": candidate["policy_review_required"],
            "expected_calibration_value": candidate["expected_calibration_value"],
            "expected_backfill_value": candidate["expected_backfill_value"],
            "target_final_decision": candidate["target_final_decision"],
            "source_id": candidate["source_id"],
        }
        for candidate in candidate_rows
    ]
    return {
        "ok": True,
        "status": "ok",
        "report_name": "COMBAT_CANDIDATE_SOURCE_POLICY_INVENTORY",
        "schema_version": "combat_candidate_source_policy_inventory_v1",
        "created_at": current_utc(),
        "run_mode": RUN_MODE,
        "candidate_source_rows": inventory_rows,
        "candidate_source_count": len(inventory_rows),
        "provider_write": False,
        "execution_allowed": False,
        "raw_payload_included": False,
        "raw_html_persisted": False,
        "secrets_included": False,
        "paid_source_enabled_count": 1,
    }


def write_combat_candidate_source_policy_inventory(report: dict[str, Any], *, output_dir: str | Path | None = None) -> dict[str, str]:
    root = Path(output_dir or REPORT_ROOT)
    json_path = root / "COMBAT_CANDIDATE_SOURCE_POLICY_INVENTORY.json"
    md_path = root / "COMBAT_CANDIDATE_SOURCE_POLICY_INVENTORY.md"
    write_json(json_path, report)
    lines = [
        "# Combat Candidate Source Policy Inventory",
        "",
        f"1. candidate_source_count: {report.get('candidate_source_count')}",
        "",
        "## Sources",
    ]
    for row in report.get("candidate_source_rows") or []:
        lines.append(f"- {row.get('source_name')} -> {row.get('target_final_decision')}")
    write_md(md_path, "\n".join(lines) + "\n")
    return {"latest_json_path": str(json_path).replace("\\", "/"), "latest_markdown_path": str(md_path).replace("\\", "/")}


def build_combat_source_policy_matrix(*, candidate_rows: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    candidate_rows = candidate_rows or combat_candidate_source_catalog()
    rows: list[dict[str, Any]] = []
    for candidate in candidate_rows:
        source_page = fetch_public_page_text(
            source_id=candidate["source_id"],
            domain=candidate["source_domain"],
            url=candidate["source_url"],
            transport=str(candidate.get("primary_transport") or "web_scraper_api"),
            timeout=45,
        )
        robots_review = evaluate_combat_robots(candidate)
        terms_review = evaluate_combat_terms(candidate)
        license_review = evaluate_combat_license(candidate)
        api_docs_review = evaluate_combat_api_docs(candidate)
        matrix_row = classify_combat_source(
            candidate,
            source_page=source_page,
            robots_review=robots_review,
            terms_review=terms_review,
            license_review=license_review,
            api_docs_review=api_docs_review,
        )
        transports = {
            str(source_page.get("transport") or ""),
            str(robots_review.get("oxylabs_transport_used") or ""),
            str(terms_review.get("oxylabs_transport_used") or ""),
            str(license_review.get("oxylabs_transport_used") or ""),
            str(api_docs_review.get("oxylabs_transport_used") or ""),
        }
        transports.discard("")
        transports.discard("hard_blocked")
        if transports == {"residential_proxy", "web_scraper_api"}:
            matrix_row["oxylabs_transport_used"] = "both"
        elif transports:
            matrix_row["oxylabs_transport_used"] = sorted(transports)[0]
        matrix_row.update(
            {
                "source_id": candidate["source_id"],
                "field_group": candidate["field_group"],
                "prior_status": candidate["prior_status"],
                "reason_for_recheck": candidate["reason_for_recheck"],
                "expected_calibration_value": candidate["expected_calibration_value"],
                "expected_backfill_value": candidate["expected_backfill_value"],
                "target_final_decision": candidate["target_final_decision"],
                "source_path_hash": stable_hash(candidate["source_path_or_path_pattern"]),
                "normalized_records_found": 0,
                "normalized_records_added": 0,
            }
        )
        rows.append(matrix_row)
    return {
        "ok": True,
        "status": "ok",
        "report_name": "COMBAT_SOURCE_POLICY_MATRIX",
        "schema_version": "combat_source_policy_matrix_v1",
        "created_at": current_utc(),
        "run_mode": RUN_MODE,
        "policy_matrix_rows": rows,
        "policy_matrix_row_count": len(rows),
        "candidate_paths_policy_reviewed_count": len(rows),
        "policy_pages_checked": len(rows),
        "robots_checked": sum(1 for row in rows if row.get("robots_checked")),
        "terms_checked": sum(1 for row in rows if row.get("terms_checked")),
        "licenses_checked": sum(1 for row in rows if row.get("license_checked")),
        "api_docs_checked": sum(1 for row in rows if row.get("api_docs_checked")),
        "data_dictionaries_checked": sum(1 for row in rows if row.get("data_dictionary_checked")),
        "accepted_for_automated_normalized_backfill_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_automated_normalized_backfill"),
        "accepted_for_postmatch_training_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_postmatch_training_only"),
        "accepted_for_manual_import_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_manual_import_only"),
        "accepted_for_metadata_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_metadata_only"),
        "rejected_policy_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_policy_blocked"),
        "rejected_robots_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_robots_blocked"),
        "rejected_terms_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_terms_blocked"),
        "rejected_login_paywall_captcha_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_login_paywall_captcha"),
        "license_terms_unclear_count": sum(1 for row in rows if row["path_level_decision"] == "license_terms_unclear"),
        "unavailable_after_exhaustive_search_count": sum(1 for row in rows if row["path_level_decision"] == "unavailable_after_exhaustive_search"),
        "obsolete_or_duplicate_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_duplicate_source"),
        "provider_write": False,
        "execution_allowed": False,
        "raw_payload_included": False,
        "raw_html_persisted": False,
        "raw_screenshot_persisted": False,
        "secrets_included": False,
        "paid_source_enabled_count": 1,
    }


def write_combat_source_policy_matrix(report: dict[str, Any], *, output_dir: str | Path | None = None) -> dict[str, str]:
    root = Path(output_dir or REPORT_ROOT)
    json_path = root / "COMBAT_SOURCE_POLICY_MATRIX.json"
    md_path = root / "COMBAT_SOURCE_POLICY_MATRIX.md"
    write_json(json_path, report)
    lines = [
        "# Combat Source Policy Matrix",
        "",
        f"1. policy_matrix_row_count: {report.get('policy_matrix_row_count')}",
        f"2. accepted_for_automated_normalized_backfill_count: {report.get('accepted_for_automated_normalized_backfill_count')}",
        f"3. accepted_for_manual_import_only_count: {report.get('accepted_for_manual_import_only_count')}",
        f"4. rejected_policy_blocked_count: {report.get('rejected_policy_blocked_count')}",
        f"5. license_terms_unclear_count: {report.get('license_terms_unclear_count')}",
        "",
        "## Sources",
    ]
    for row in report.get("policy_matrix_rows") or []:
        lines.append(f"- {row.get('source_name')} final={row.get('final_state')} decision={row.get('path_level_decision')}")
    write_md(md_path, "\n".join(lines) + "\n")
    return {"latest_json_path": str(json_path).replace("\\", "/"), "latest_markdown_path": str(md_path).replace("\\", "/")}


def write_combat_source_policy_review_docs(report: dict[str, Any], *, docs_dir: str | Path | None = None) -> dict[str, str]:
    root = Path(docs_dir or "docs")
    path = root / "COMBAT_SOURCE_POLICY_REVIEW.md"
    lines = [
        "# Combat Source Policy Review",
        "",
        "This document records the final source-policy state for the Combat Sports free/open exhaustion pass.",
        "",
        "## Final Source States",
        "",
    ]
    for row in report.get("policy_matrix_rows") or []:
        lines.append(
            f"- {row.get('source_name')}: final_state={row.get('final_state')} decision={row.get('path_level_decision')} blocker_or_allowance={row.get('exact_blocker_or_allowance')}"
        )
    write_md(path, "\n".join(lines) + "\n")
    return {"source_policy_review_docs_path": str(path).replace("\\", "/")}
