from __future__ import annotations

from pathlib import Path
from typing import Any

from .golf_api_docs_parser import evaluate_golf_api_docs
from .golf_license_parser import evaluate_golf_license
from .golf_policy_classifier import classify_golf_source
from .golf_robots_checker import evaluate_golf_robots
from .golf_terms_parser import evaluate_golf_terms
from .golf_oxylabs_common import OPEN_GOLF_API_URL, OPEN_GOLF_SCHEMA_URL, OPEN_GOLF_TERMS_URL, REPORT_ROOT, RUN_MODE, current_utc, fetch_public_page_text, stable_hash, url_hash, write_json, write_md


def _candidate(source_id: str, field_group: str, source_name: str, source_domain: str, source_url: str, *, source_type: str, policy_mode: str, target_final_decision: str, final_state_target: str, prior_status: str, expected_calibration_value: str, expected_backfill_value: str, terms_url: str = "", license_url: str = "", robots_url: str = "", api_docs_url: str = "", data_dictionary_url: str = "", repo_field_mapping: list[str] | None = None, sample_strategy: str = "none", normalized_entity_level: str = "source", login_required: bool = False, exact_blocker_or_allowance: str = "", primary_transport: str = "web_scraper_api", normalized_fact_persistence_allowed: bool = False) -> dict[str, Any]:
    return {
        "sport": "golf", "sport_group": "golf", "field_group": field_group, "source_id": source_id, "source_name": source_name,
        "source_domain": source_domain, "source_url": source_url, "source_path_or_path_pattern": source_url, "source_type": source_type,
        "source_owner_if_known": source_name, "mirror_or_original_source": "original", "likely_upstream_source": source_name,
        "public_or_private": "public", "policy_mode": policy_mode, "prior_status": prior_status, "prior_report_source": "first_golf_finality_pass",
        "reason_for_recheck": f"{source_name} required exact Golf source-policy finality.", "policy_review_required": True,
        "expected_calibration_value": expected_calibration_value, "expected_backfill_value": expected_backfill_value,
        "target_final_decision": target_final_decision, "final_state_target": final_state_target, "login_required": login_required,
        "paywall_required": False, "captcha_required": False, "session_required": False, "terms_url": terms_url, "privacy_url": "",
        "license_url": license_url, "robots_url": robots_url, "api_docs_url": api_docs_url, "data_dictionary_url": data_dictionary_url,
        "GitHub_LICENSE_url": license_url, "README_url": source_url, "attribution_url": source_url, "acceptable_use_url": terms_url,
        "copyright_notice_url": "", "primary_transport": primary_transport, "sample_strategy": sample_strategy,
        "sample_url": source_url, "normalized_entity_level": normalized_entity_level, "repo_field_mapping": list(repo_field_mapping or []),
        "new_fields_recommended": [], "sport_model_relevance": expected_calibration_value, "duplicate_existing_source": False,
        "upstream_source_unclear": policy_mode == "license_unclear", "timestamp_available": True, "event_time_available": True,
        "game_or_match_start_time_available": True, "data_publication_time_available": True, "future_leakage_risk": "low_if_joined_before_tournament_start",
        "post_event_only": False, "pre_event_available": True, "usable_for_prematch_model": policy_mode in {"automated_backfill", "manual_only", "metadata_only"},
        "usable_for_postevent_training_only": policy_mode == "postevent_only", "cutoff_safe": True,
        "cutoff_safety_reason": "normalized facts are joined to tournament or course timestamps only",
        "normalized_fact_persistence_allowed": normalized_fact_persistence_allowed, "aggregate_feature_persistence_allowed": normalized_fact_persistence_allowed,
        "source_hash_persistence_allowed": True, "fields_available": list(repo_field_mapping or []), "attribution_storage_required": True,
        "required_attribution_text_or_url_hash": url_hash(source_url), "exact_blocker_or_allowance": exact_blocker_or_allowance,
    }


def golf_candidate_source_catalog() -> list[dict[str, Any]]:
    return [
        _candidate("golf_open_course_data", "open course identity, par, yardage, and scorecards", "OpenGolfAPI course dataset", "courses.opengolfapi.org", OPEN_GOLF_API_URL, source_type="open_course_dataset", policy_mode="automated_backfill", target_final_decision="accepted_for_automated_normalized_backfill", final_state_target="free_open_backfilled", prior_status="free_open_loader_needed", expected_calibration_value="high", expected_backfill_value="high", terms_url=OPEN_GOLF_TERMS_URL, license_url=OPEN_GOLF_TERMS_URL, robots_url="https://courses.opengolfapi.org/robots.txt", api_docs_url=OPEN_GOLF_API_URL, data_dictionary_url=OPEN_GOLF_SCHEMA_URL, repo_field_mapping=["course_id", "course_name", "city", "region", "country", "par", "yardage", "hole", "hole_par", "hole_yardage"], sample_strategy="static_open_course_rows", normalized_entity_level="course", exact_blocker_or_allowance="OpenGolfAPI/Open Course data is accepted for normalized course and scorecard backfill with attribution.", primary_transport="residential_proxy", normalized_fact_persistence_allowed=True),
        _candidate("golf_wikidata_player_entities", "golfer metadata entities", "Wikidata golfer entities", "wikidata.org", "https://www.wikidata.org/wiki/Wikidata:Main_Page", source_type="structured_open_metadata", policy_mode="metadata_only", target_final_decision="accepted_for_metadata_only", final_state_target="free_open_metadata_only", prior_status="free_open_partial", expected_calibration_value="low", expected_backfill_value="low", terms_url="https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Terms_of_Use", license_url="https://www.wikidata.org/wiki/Wikidata:Licensing", robots_url="https://www.wikidata.org/robots.txt", api_docs_url="https://www.wikidata.org/w/api.php", data_dictionary_url="https://www.wikidata.org/wiki/Wikidata:Data_access", repo_field_mapping=["player_name", "country", "birth_date", "wikidata_id"], normalized_entity_level="player", exact_blocker_or_allowance="Wikidata is accepted for attribution-preserving metadata-only use."),
        _candidate("golf_wikipedia_tournament_tables", "major tournament metadata", "Wikipedia golf tournament tables", "wikipedia.org", "https://en.wikipedia.org/wiki/Men%27s_major_golf_championships", source_type="structured_open_metadata", policy_mode="metadata_only", target_final_decision="accepted_for_metadata_only", final_state_target="free_open_metadata_only", prior_status="free_open_partial", expected_calibration_value="low", expected_backfill_value="low", terms_url="https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Terms_of_Use", license_url="https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License", robots_url="https://en.wikipedia.org/robots.txt", repo_field_mapping=["tournament_name", "major_name", "founded", "host_course_note"], normalized_entity_level="tournament", exact_blocker_or_allowance="Wikipedia major tables are accepted as metadata-only supplemental context."),
        _candidate("golf_pga_tour_official_pages", "PGA results, fields, tee times", "PGA Tour official pages", "pgatour.com", "https://www.pgatour.com/", source_type="official_tour_page", policy_mode="manual_only", target_final_decision="accepted_for_manual_import_only", final_state_target="manual_import_required", prior_status="free_open_manual_import_needed", expected_calibration_value="very_high", expected_backfill_value="high", terms_url="https://www.pgatour.com/company/terms-of-use", license_url="https://www.pgatour.com/company/terms-of-use", robots_url="https://www.pgatour.com/robots.txt", repo_field_mapping=["round_scores", "total_score", "finish_position", "cut_status"], exact_blocker_or_allowance="PGA Tour official pages remain manual-only until exact automated rights are approved."),
        _candidate("golf_dp_world_tour_official_pages", "DP World Tour results", "DP World Tour official pages", "europeantour.com", "https://www.europeantour.com/dpworld-tour/", source_type="official_tour_page", policy_mode="manual_only", target_final_decision="accepted_for_manual_import_only", final_state_target="manual_import_required", prior_status="free_open_manual_import_needed", expected_calibration_value="high", expected_backfill_value="moderate", terms_url="https://www.europeantour.com/terms-and-conditions/", license_url="https://www.europeantour.com/terms-and-conditions/", robots_url="https://www.europeantour.com/robots.txt", repo_field_mapping=["round_scores", "total_score", "finish_position"], exact_blocker_or_allowance="DP World Tour pages remain manual-only in this pass."),
        _candidate("golf_lpga_official_pages", "LPGA results", "LPGA official pages", "lpga.com", "https://www.lpga.com/", source_type="official_tour_page", policy_mode="manual_only", target_final_decision="accepted_for_manual_import_only", final_state_target="manual_import_required", prior_status="free_open_manual_import_needed", expected_calibration_value="medium", expected_backfill_value="moderate", terms_url="https://www.lpga.com/terms-of-use", license_url="https://www.lpga.com/terms-of-use", robots_url="https://www.lpga.com/robots.txt", repo_field_mapping=["round_scores", "total_score", "finish_position"], exact_blocker_or_allowance="LPGA pages remain manual-only in this pass."),
        _candidate("golf_major_championship_pages", "major fields and tee times", "Major championship official pages", "masters.com", "https://www.masters.com/", source_type="official_major_page", policy_mode="manual_only", target_final_decision="accepted_for_manual_import_only", final_state_target="manual_import_required", prior_status="free_open_manual_import_needed", expected_calibration_value="high", expected_backfill_value="moderate", terms_url="https://www.masters.com/en_US/about/terms.html", license_url="https://www.masters.com/en_US/about/terms.html", robots_url="https://www.masters.com/robots.txt", repo_field_mapping=["field_player_name", "tee_time", "wave", "starting_hole"], exact_blocker_or_allowance="Major fields and tee times remain manual-only with timestamp review."),
        _candidate("golf_owgr_rankings", "world ranking pages", "Official World Golf Ranking pages", "owgr.com", "https://www.owgr.com/", source_type="ranking_page", policy_mode="blocked", target_final_decision="rejected_policy_blocked", final_state_target="policy_blocked", prior_status="policy_blocked", expected_calibration_value="high", expected_backfill_value="moderate", terms_url="https://www.owgr.com/", license_url="https://www.owgr.com/", robots_url="https://www.owgr.com/robots.txt", repo_field_mapping=["world_rank", "ranking_date", "ranking_points"], exact_blocker_or_allowance="OWGR automated extraction is not approved in this pass."),
        _candidate("golf_datagolf_public_pages", "Data Golf analytics pages", "Data Golf public pages", "datagolf.com", "https://datagolf.com/", source_type="analytics_page", policy_mode="license_unclear", target_final_decision="license_terms_unclear", final_state_target="license_terms_unclear", prior_status="license_terms_unclear", expected_calibration_value="high", expected_backfill_value="high", terms_url="https://datagolf.com/", license_url="https://datagolf.com/", robots_url="https://datagolf.com/robots.txt", repo_field_mapping=["datagolf_skill_estimate", "course_fit_estimate"], exact_blocker_or_allowance="Data Golf requires exact licensed/API terms before automated use."),
        _candidate("golf_pgatour_shotlink", "ShotLink and PGA stat pages", "PGA Tour ShotLink", "pgatour.com", "https://www.pgatour.com/stats", source_type="shotlink_stats", policy_mode="paid", target_final_decision="rejected_terms_blocked", final_state_target="paid_subscription_required", prior_status="paid_data_subscription_required", expected_calibration_value="very_high", expected_backfill_value="very_high", terms_url="https://www.pgatour.com/company/terms-of-use", license_url="https://www.pgatour.com/company/terms-of-use", robots_url="https://www.pgatour.com/robots.txt", repo_field_mapping=["sg_total", "sg_off_tee", "sg_approach", "sg_putting"], exact_blocker_or_allowance="ShotLink/strokes-gained production data remains paid/licensed."),
        _candidate("golf_espn_golf_pages", "ESPN Golf result pages", "ESPN Golf pages", "espn.com", "https://www.espn.com/golf/", source_type="reference_site", policy_mode="blocked", target_final_decision="rejected_policy_blocked", final_state_target="policy_blocked", prior_status="policy_blocked", expected_calibration_value="medium", expected_backfill_value="low", terms_url="https://www.espn.com/", license_url="https://www.espn.com/", robots_url="https://www.espn.com/robots.txt", repo_field_mapping=["leaderboard_reference"], exact_blocker_or_allowance="ESPN Golf pages were reviewed but not approved for automated extraction."),
        _candidate("golf_kaggle_catalog", "Kaggle golf data catalog", "Kaggle golf dataset catalog", "kaggle.com", "https://www.kaggle.com/datasets?search=golf", source_type="dataset_catalog", policy_mode="blocked", target_final_decision="rejected_login_paywall_captcha", final_state_target="login_paywall_captcha_blocked", prior_status="login_paywall_captcha_blocked", expected_calibration_value="low", expected_backfill_value="low", terms_url="https://www.kaggle.com/terms", license_url="https://www.kaggle.com/terms", robots_url="https://www.kaggle.com/robots.txt", repo_field_mapping=["dataset_name", "license_note"], login_required=True, exact_blocker_or_allowance="Kaggle catalog access remains account-gated."),
        _candidate("golf_golfastr_repo", "golfastr wrapper repo", "golfastr GitHub repository", "github.com", "https://github.com/cran/golfastr", source_type="community_wrapper_repo", policy_mode="license_unclear", target_final_decision="license_terms_unclear", final_state_target="license_terms_unclear", prior_status="license_terms_unclear", expected_calibration_value="medium", expected_backfill_value="moderate", terms_url="https://github.com/cran/golfastr", license_url="https://raw.githubusercontent.com/cran/golfastr/master/LICENSE", robots_url="https://github.com/robots.txt", api_docs_url="https://cran.r-universe.dev/golfastr/doc/manual.html", data_dictionary_url="https://cran.r-universe.dev/golfastr/doc/manual.html", repo_field_mapping=["wrapper_name", "upstream_source", "license_note"], exact_blocker_or_allowance="golfastr is public, but ESPN/PGA upstream rights remain unclear."),
        _candidate("golf_pgatour_api_wrapper_repo", "pgatouR wrapper docs", "pgatouR GitHub/docs", "github.com", "https://walrusquant.github.io/pgatouR/", source_type="community_api_wrapper_repo", policy_mode="license_unclear", target_final_decision="license_terms_unclear", final_state_target="license_terms_unclear", prior_status="license_terms_unclear", expected_calibration_value="medium", expected_backfill_value="moderate", terms_url="https://walrusquant.github.io/pgatouR/", license_url="https://walrusquant.github.io/pgatouR/", robots_url="https://github.com/robots.txt", api_docs_url="https://walrusquant.github.io/pgatouR/", data_dictionary_url="https://walrusquant.github.io/pgatouR/", repo_field_mapping=["wrapper_name", "upstream_source", "stat_surface_note"], exact_blocker_or_allowance="pgatouR wrappers require legal review before automated use."),
        _candidate("golf_paid_tracking_vendor", "licensed golf data vendor", "Licensed golf data vendor", "sportsdata.io", "https://sportsdata.io/developers/data-dictionary/golf", source_type="paid_vendor_page", policy_mode="paid", target_final_decision="rejected_terms_blocked", final_state_target="paid_subscription_required", prior_status="paid_data_subscription_required", expected_calibration_value="very_high", expected_backfill_value="very_high", terms_url="https://sportsdata.io/developers/data-dictionary/golf", license_url="https://sportsdata.io/developers/data-dictionary/golf", robots_url="https://sportsdata.io/robots.txt", api_docs_url="https://sportsdata.io/developers/data-dictionary/golf", data_dictionary_url="https://sportsdata.io/developers/data-dictionary/golf", repo_field_mapping=["weather_date", "wind_speed", "player_stats", "rankings"], exact_blocker_or_allowance="Production golf weather/stat feeds remain paid/licensed."),
    ]


def build_golf_candidate_source_policy_inventory(*, candidate_rows: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    candidate_rows = candidate_rows or golf_candidate_source_catalog()
    rows = [{"sport": "Golf", "source_family": row["source_type"], "source_name": row["source_name"], "domain": row["source_domain"], "source_path_or_path_pattern": row["source_path_or_path_pattern"], "field_group": row["field_group"], "prior_status": row["prior_status"], "policy_review_required": True, "expected_calibration_value": row["expected_calibration_value"], "target_final_decision": row["target_final_decision"], "source_id": row["source_id"]} for row in candidate_rows]
    return {"ok": True, "status": "ok", "report_name": "GOLF_CANDIDATE_SOURCE_POLICY_INVENTORY", "schema_version": "golf_candidate_source_policy_inventory_v1", "created_at": current_utc(), "run_mode": RUN_MODE, "candidate_source_rows": rows, "candidate_source_count": len(rows), "provider_write": False, "execution_allowed": False, "raw_payload_included": False, "raw_html_persisted": False, "secrets_included": False, "paid_source_enabled_count": 1}


def write_golf_candidate_source_policy_inventory(report: dict[str, Any], *, output_dir: str | Path | None = None) -> dict[str, str]:
    root = Path(output_dir or REPORT_ROOT)
    json_path = root / "GOLF_CANDIDATE_SOURCE_POLICY_INVENTORY.json"
    md_path = root / "GOLF_CANDIDATE_SOURCE_POLICY_INVENTORY.md"
    write_json(json_path, report)
    write_md(md_path, "# Golf Candidate Source Policy Inventory\n\n" + "\n".join(f"- {row['source_name']} -> {row['target_final_decision']}" for row in report.get("candidate_source_rows") or []) + "\n")
    return {"latest_json_path": str(json_path).replace("\\", "/"), "latest_markdown_path": str(md_path).replace("\\", "/")}


def build_golf_source_policy_matrix(*, candidate_rows: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    candidate_rows = candidate_rows or golf_candidate_source_catalog()
    rows = []
    for candidate in candidate_rows:
        source_page = fetch_public_page_text(source_id=candidate["source_id"], domain=candidate["source_domain"], url=candidate["source_url"], transport=candidate.get("primary_transport") or "web_scraper_api")
        robots = evaluate_golf_robots(candidate)
        terms = evaluate_golf_terms(candidate)
        license_review = evaluate_golf_license(candidate)
        api_docs = evaluate_golf_api_docs(candidate)
        row = classify_golf_source(candidate, source_page=source_page, robots_review=robots, terms_review=terms, license_review=license_review, api_docs_review=api_docs)
        row.update({"source_id": candidate["source_id"], "field_group": candidate["field_group"], "prior_status": candidate["prior_status"], "target_final_decision": candidate["target_final_decision"], "source_path_hash": stable_hash(candidate["source_path_or_path_pattern"]), "normalized_records_found": 0, "normalized_records_added": 0})
        rows.append(row)
    return {"ok": True, "status": "ok", "report_name": "GOLF_SOURCE_POLICY_MATRIX", "schema_version": "golf_source_policy_matrix_v1", "created_at": current_utc(), "run_mode": RUN_MODE, "policy_matrix_rows": rows, "policy_matrix_row_count": len(rows), "candidate_paths_policy_reviewed_count": len(rows), "policy_pages_checked": len(rows), "robots_checked": sum(1 for row in rows if row.get("robots_checked")), "terms_checked": sum(1 for row in rows if row.get("terms_checked")), "licenses_checked": sum(1 for row in rows if row.get("license_checked")), "api_docs_checked": sum(1 for row in rows if row.get("api_docs_checked")), "data_dictionaries_checked": sum(1 for row in rows if row.get("data_dictionary_checked")), "accepted_for_automated_normalized_backfill_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_automated_normalized_backfill"), "accepted_for_postevent_training_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_postevent_training_only"), "accepted_for_manual_import_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_manual_import_only"), "accepted_for_metadata_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_metadata_only"), "rejected_policy_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_policy_blocked"), "rejected_robots_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_robots_blocked"), "rejected_terms_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_terms_blocked"), "rejected_login_paywall_captcha_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_login_paywall_captcha"), "license_terms_unclear_count": sum(1 for row in rows if row["path_level_decision"] == "license_terms_unclear"), "unavailable_after_exhaustive_search_count": sum(1 for row in rows if row["path_level_decision"] == "unavailable_after_exhaustive_search"), "obsolete_or_duplicate_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_duplicate_source"), "provider_write": False, "execution_allowed": False, "raw_payload_included": False, "raw_html_persisted": False, "raw_screenshot_persisted": False, "secrets_included": False, "paid_source_enabled_count": 1}


def write_golf_source_policy_matrix(report: dict[str, Any], *, output_dir: str | Path | None = None) -> dict[str, str]:
    root = Path(output_dir or REPORT_ROOT)
    json_path = root / "GOLF_SOURCE_POLICY_MATRIX.json"
    md_path = root / "GOLF_SOURCE_POLICY_MATRIX.md"
    write_json(json_path, report)
    write_md(md_path, "# Golf Source Policy Matrix\n\n" + "\n".join(f"- {row['source_name']} final={row['final_state']} decision={row['path_level_decision']}" for row in report.get("policy_matrix_rows") or []) + "\n")
    return {"latest_json_path": str(json_path).replace("\\", "/"), "latest_markdown_path": str(md_path).replace("\\", "/")}


def write_golf_source_policy_review_docs(report: dict[str, Any], *, docs_dir: str | Path | None = None) -> dict[str, str]:
    path = Path(docs_dir or "docs") / "GOLF_SOURCE_POLICY_REVIEW.md"
    write_md(path, "# Golf Source Policy Review\n\n" + "\n".join(f"- {row['source_name']}: final_state={row['final_state']} decision={row['path_level_decision']} reason={row['exact_blocker_or_allowance']}" for row in report.get("policy_matrix_rows") or []) + "\n")
    return {"source_policy_review_docs_path": str(path).replace("\\", "/")}
