from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any
from uuid import uuid4

from .mlb_open_data_common import MLB_MODULE, mlb_atomic_write_json, mlb_atomic_write_text, mlb_read_json, mlb_rel, mlb_report_root, mlb_safe_payload
from .open_sports_history_sources import SAFETY_FIELDS
from .scheduler_config import sanitize_filename, utc_now_iso


MLB_OPEN_DATA_SOURCE_SCHEMA_VERSION = "mlb_open_data_sources_v1"

REQUIRED_DATA_CATEGORIES = [
    "schedules_results",
    "game_logs",
    "play_by_play_events",
    "pitch_by_pitch",
    "batting_stats",
    "pitching_stats",
    "fielding_stats",
    "team_stats",
    "player_master",
    "rosters",
    "transactions",
    "injuries",
    "lineups",
    "probable_pitchers",
    "starting_pitchers",
    "bullpen_usage",
    "defensive_positions",
    "park_factors",
    "stadiums",
    "weather",
    "umpires_officials",
    "postseason_labels",
    "standings",
    "awards_allstar",
    "draft",
    "minor_league_links",
    "statcast_batted_ball",
    "market_odds",
    "managers_coaches",
    "franchises",
    "people_identifiers",
    "structured_wiki_seed",
    "official_public_web_research",
    "manual_csv_import",
]

BLOCKED_FEATURE_FAMILIES = [
    "pitch_by_pitch",
    "statcast_quality",
    "market_odds",
    "official_public_web_research",
]


def _source(
    *,
    source_id: str,
    source_name: str,
    source_family: str,
    data_category: str,
    source_access_type: str,
    source_kind: str,
    current_phase_allowed: bool,
    approval_status: str,
    terms_review_status: str,
    robots_review_status: str = "not_applicable",
    license_status: str = "unknown",
    source_access_note: str = "",
    future_paid_candidate: bool = False,
    requires_budget_approval: bool = False,
    paid_or_freemium: bool = False,
    requires_api_key: bool = False,
    requires_auth: bool = False,
    automation_allowed: bool = True,
    structured_data_available: bool = True,
    structured_seed_supported: bool = False,
    manual_import_supported: bool = False,
    crawl_supported: bool = False,
    live_download_supported: bool = True,
    no_call_supported: bool = True,
    metadata_only_supported: bool = True,
    raw_html_required: bool = False,
    spoofing_required: bool = False,
    browser_impersonation_used: bool = False,
    expected_formats: list[str] | None = None,
    expected_granularity: str = "game",
    expected_join_keys: list[str] | None = None,
    likely_supported_features: list[str] | None = None,
    blocked_features: list[str] | None = None,
    blockers: list[str] | None = None,
    expected_fields: list[str] | None = None,
    safety_notes: str = "",
) -> dict[str, Any]:
    return {
        "source_id": source_id,
        "source_name": source_name,
        "source_family": source_family,
        "module": MLB_MODULE,
        "data_category": data_category,
        "source_access_type": source_access_type,
        "source_kind": source_kind,
        "current_phase_allowed": bool(current_phase_allowed),
        "future_paid_candidate": bool(future_paid_candidate),
        "requires_budget_approval": bool(requires_budget_approval),
        "approval_status": approval_status,
        "enabled": False,
        "no_call_supported": bool(no_call_supported),
        "metadata_only_supported": bool(metadata_only_supported),
        "crawl_supported": bool(crawl_supported),
        "live_download_supported": bool(live_download_supported),
        "requires_api_key": bool(requires_api_key),
        "requires_auth": bool(requires_auth),
        "terms_review_status": terms_review_status,
        "robots_review_status": robots_review_status,
        "license_status": license_status,
        "paid_or_freemium": bool(paid_or_freemium),
        "automation_allowed": bool(automation_allowed),
        "structured_data_available": bool(structured_data_available),
        "structured_seed_supported": bool(structured_seed_supported),
        "manual_import_supported": bool(manual_import_supported),
        "raw_html_required": bool(raw_html_required),
        "raw_html_persisted": False,
        "spoofing_required": bool(spoofing_required),
        "browser_impersonation_used": bool(browser_impersonation_used),
        "raw_payload_included": False,
        "secrets_included": False,
        "source_access_note": source_access_note,
        "expected_formats": list(expected_formats or ["json", "csv", "csv.gz"]),
        "expected_granularity": expected_granularity,
        "expected_join_keys": list(expected_join_keys or []),
        "likely_supported_features": list(likely_supported_features or []),
        "blocked_features": list(blocked_features or []),
        "blockers": list(blockers or []),
        "expected_fields": list(expected_fields or []),
        "safety_notes": safety_notes,
    }


def mlb_open_data_sources() -> list[dict[str, Any]]:
    return [
        _source(
            source_id="retrosheet_schedules_results",
            source_name="Retrosheet schedules/results",
            source_family="retrosheet_open_dataset",
            data_category="schedules_results",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv", "csv.gz"],
            expected_granularity="game",
            expected_join_keys=["game_id", "season", "event_date", "home_team", "away_team"],
            likely_supported_features=["schedule_results", "postseason_labels", "team_identity"],
            expected_fields=["game_id", "season", "event_date", "home_team", "away_team", "home_score", "away_score", "winner", "final_result", "game_type"],
            safety_notes="open historical game-level source; disabled by default",
        ),
        _source(
            source_id="retrosheet_game_logs",
            source_name="Retrosheet game logs",
            source_family="retrosheet_open_dataset",
            data_category="game_logs",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="game",
            expected_join_keys=["game_id", "event_date", "season"],
            likely_supported_features=["schedule_results", "stadiums", "umpires_officials"],
            expected_fields=["game_id", "season", "event_date", "home_team", "away_team", "attendance", "venue", "home_score", "away_score"],
        ),
        _source(
            source_id="retrosheet_play_by_play_events",
            source_name="Retrosheet play-by-play events",
            source_family="retrosheet_open_dataset",
            data_category="play_by_play_events",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="play",
            expected_join_keys=["game_id", "play_id", "inning"],
            likely_supported_features=["play_by_play_efficiency", "postseason_labels"],
            expected_fields=["game_id", "play_id", "inning", "batting_team", "fielding_team", "batter_id", "pitcher_id", "event_type", "runs_scored"],
        ),
        _source(
            source_id="pitch_by_pitch_research_lane",
            source_name="Statcast pitch-by-pitch research lane",
            source_family="statcast_public_data",
            data_category="pitch_by_pitch",
            source_access_type="research_required",
            source_kind="research_lane",
            current_phase_allowed=False,
            approval_status="research_required",
            terms_review_status="research_required",
            robots_review_status="review_required",
            license_status="unknown",
            structured_data_available=False,
            crawl_supported=False,
            live_download_supported=False,
            expected_granularity="pitch",
            expected_join_keys=["game_pk", "pitch_number", "batter", "pitcher"],
            likely_supported_features=["pitch_by_pitch", "statcast_quality"],
            blocked_features=["pitch_by_pitch", "statcast_quality"],
            blockers=["terms_unclear_research_required"],
            expected_fields=["game_pk", "at_bat_number", "pitch_number", "pitcher", "batter", "pitch_type", "release_speed", "plate_x", "plate_z", "description"],
            safety_notes="not enabled until a safe, no-scrape access path is verified",
        ),
        _source(
            source_id="batting_stats_lahman",
            source_name="Lahman batting stats",
            source_family="lahman_database",
            data_category="batting_stats",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="player_season_stint",
            expected_join_keys=["playerID", "yearID", "teamID"],
            likely_supported_features=["batting_profile", "team_identity", "people_identifiers"],
            expected_fields=["playerID", "yearID", "stint", "teamID", "AB", "H", "HR", "RBI", "BB", "SO"],
        ),
        _source(
            source_id="pitching_stats_lahman",
            source_name="Lahman pitching stats",
            source_family="lahman_database",
            data_category="pitching_stats",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="player_season_stint",
            expected_join_keys=["playerID", "yearID", "teamID"],
            likely_supported_features=["pitching_profile", "starting_pitchers", "bullpen_usage"],
            expected_fields=["playerID", "yearID", "stint", "teamID", "W", "L", "ERA", "G", "GS", "IPouts", "SO", "BB", "HR"],
        ),
        _source(
            source_id="fielding_stats_lahman",
            source_name="Lahman fielding stats",
            source_family="lahman_database",
            data_category="fielding_stats",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="player_season_position",
            expected_join_keys=["playerID", "yearID", "teamID", "pos"],
            likely_supported_features=["fielding_profile", "defensive_positions"],
            expected_fields=["playerID", "yearID", "teamID", "pos", "G", "GS", "InnOuts", "PO", "A", "E"],
        ),
        _source(
            source_id="team_stats_lahman",
            source_name="Lahman team stats",
            source_family="lahman_database",
            data_category="team_stats",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="team_season",
            expected_join_keys=["yearID", "teamID"],
            likely_supported_features=["team_game_run_profile", "standings_context", "franchises"],
            expected_fields=["yearID", "teamID", "W", "L", "R", "RA", "HR", "BB", "SO"],
        ),
        _source(
            source_id="player_master_lahman",
            source_name="Lahman player master",
            source_family="lahman_database",
            data_category="player_master",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="player_identity",
            expected_join_keys=["playerID"],
            likely_supported_features=["people_identifiers", "team_identity"],
            expected_fields=["playerID", "birthYear", "birthMonth", "birthDay", "nameFirst", "nameLast", "debut", "finalGame"],
        ),
        _source(
            source_id="rosters_mlb_stats_api",
            source_name="MLB Stats API rosters/players",
            source_family="mlb_stats_api",
            data_category="rosters",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="player_team_roster",
            expected_join_keys=["team_id", "player_id", "season"],
            likely_supported_features=["roster_continuity", "player_availability", "team_identity"],
            expected_fields=["team_id", "player_id", "season", "status", "jersey_number", "position", "full_name", "bat_side", "pitch_hand"],
        ),
        _source(
            source_id="transactions_mlb_stats_api",
            source_name="MLB Stats API transactions",
            source_family="mlb_stats_api",
            data_category="transactions",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="transaction",
            expected_join_keys=["transaction_id", "player_id", "team_id"],
            likely_supported_features=["transactions", "roster_continuity"],
            expected_fields=["transaction_id", "date", "player_id", "team_id", "type", "description"],
        ),
        _source(
            source_id="injuries_mlb_stats_api",
            source_name="MLB Stats API injuries",
            source_family="mlb_stats_api",
            data_category="injuries",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="player_team_day",
            expected_join_keys=["player_id", "team_id", "report_date"],
            likely_supported_features=["player_availability", "lineup_stability"],
            expected_fields=["player_id", "team_id", "report_date", "status", "injury_note", "expected_return"],
        ),
        _source(
            source_id="lineups_mlb_stats_api",
            source_name="MLB Stats API lineups",
            source_family="mlb_stats_api",
            data_category="lineups",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="game_lineup",
            expected_join_keys=["game_pk", "team_id", "player_id"],
            likely_supported_features=["lineup_stability", "starting_pitchers"],
            expected_fields=["game_pk", "team_id", "player_id", "batting_order", "position", "status"],
        ),
        _source(
            source_id="probable_pitchers_mlb_stats_api",
            source_name="MLB Stats API probable pitchers",
            source_family="mlb_stats_api",
            data_category="probable_pitchers",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="game_team_probable_pitcher",
            expected_join_keys=["game_pk", "team_id", "player_id"],
            likely_supported_features=["probable_pitchers", "starting_pitchers"],
            expected_fields=["game_pk", "team_id", "player_id", "probable", "hand", "game_date"],
        ),
        _source(
            source_id="starting_pitchers_mlb_stats_api",
            source_name="MLB Stats API starting pitchers",
            source_family="mlb_stats_api",
            data_category="starting_pitchers",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="game_team_starting_pitcher",
            expected_join_keys=["game_pk", "team_id", "player_id"],
            likely_supported_features=["starting_pitchers", "pitching_profile"],
            expected_fields=["game_pk", "team_id", "player_id", "start_flag", "innings_pitched", "pitch_count"],
        ),
        _source(
            source_id="bullpen_usage_mlb_stats_api",
            source_name="MLB Stats API bullpen usage",
            source_family="mlb_stats_api",
            data_category="bullpen_usage",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="game_team_player_relief",
            expected_join_keys=["game_pk", "team_id", "player_id"],
            likely_supported_features=["bullpen_usage", "pitching_profile"],
            expected_fields=["game_pk", "team_id", "player_id", "relief_flag", "pitch_count", "innings_pitched", "save_opportunity"],
        ),
        _source(
            source_id="defensive_positions_mlb_stats_api",
            source_name="MLB Stats API defensive positions",
            source_family="mlb_stats_api",
            data_category="defensive_positions",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="game_inning_position",
            expected_join_keys=["game_pk", "inning", "team_id", "player_id"],
            likely_supported_features=["defense_alignment", "fielding_profile"],
            expected_fields=["game_pk", "inning", "team_id", "player_id", "position", "fielding_position"],
        ),
        _source(
            source_id="park_factors_lahman",
            source_name="Lahman park factors",
            source_family="lahman_database",
            data_category="park_factors",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="park_season",
            expected_join_keys=["park_id", "yearID"],
            likely_supported_features=["park_factor", "stadium_weather"],
            expected_fields=["park_id", "park_name", "yearID", "runs_factor", "hr_factor", "latitude", "longitude"],
        ),
        _source(
            source_id="stadiums_lahman",
            source_name="Lahman stadiums",
            source_family="lahman_database",
            data_category="stadiums",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="venue_identity",
            expected_join_keys=["park_id"],
            likely_supported_features=["stadium_weather", "team_identity"],
            expected_fields=["park_id", "park_name", "city", "state", "latitude", "longitude", "roof_type"],
        ),
        _source(
            source_id="weather_mlb_stats_api",
            source_name="MLB Stats API weather",
            source_family="mlb_stats_api",
            data_category="weather",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="game_weather",
            expected_join_keys=["game_pk", "game_date"],
            likely_supported_features=["stadium_weather", "park_factor"],
            expected_fields=["game_pk", "game_date", "temperature", "wind_speed", "wind_direction", "humidity", "precipitation"],
        ),
        _source(
            source_id="umpires_officials_mlb_stats_api",
            source_name="MLB Stats API umpires/officials",
            source_family="mlb_stats_api",
            data_category="umpires_officials",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="game_official",
            expected_join_keys=["game_pk", "official_id"],
            likely_supported_features=["umpire_officials"],
            expected_fields=["game_pk", "official_id", "umpire_name", "position", "crew"],
        ),
        _source(
            source_id="postseason_labels_retrosheet",
            source_name="Retrosheet postseason labels",
            source_family="retrosheet_open_dataset",
            data_category="postseason_labels",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="game_postseason_label",
            expected_join_keys=["game_id", "season", "game_type"],
            likely_supported_features=["postseason_context"],
            expected_fields=["game_id", "season", "game_type", "playoff_round", "series_label", "postseason_flag"],
        ),
        _source(
            source_id="standings_mlb_stats_api",
            source_name="MLB Stats API standings",
            source_family="mlb_stats_api",
            data_category="standings",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="team_season_standings",
            expected_join_keys=["season", "team_id", "league_id"],
            likely_supported_features=["standings_context", "team_game_run_profile"],
            expected_fields=["season", "team_id", "wins", "losses", "division_rank", "wild_card_rank", "runs_scored", "runs_allowed"],
        ),
        _source(
            source_id="awards_allstar_lahman",
            source_name="Lahman awards/all-star",
            source_family="lahman_database",
            data_category="awards_allstar",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="player_award_year",
            expected_join_keys=["playerID", "yearID", "awardID"],
            likely_supported_features=["awards_allstar", "people_identifiers"],
            expected_fields=["playerID", "yearID", "awardID", "all_star_flag", "teamID", "lgID"],
        ),
        _source(
            source_id="draft_lahman",
            source_name="Lahman draft",
            source_family="lahman_database",
            data_category="draft",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="player_draft_pick",
            expected_join_keys=["playerID", "yearID", "teamID"],
            likely_supported_features=["draft", "franchises"],
            expected_fields=["playerID", "yearID", "round", "pick", "teamID", "school", "signed_flag"],
        ),
        _source(
            source_id="minor_league_links_chadwick",
            source_name="Chadwick minor league links",
            source_family="chadwick_register",
            data_category="minor_league_links",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="player_minor_league_link",
            expected_join_keys=["playerID", "season"],
            likely_supported_features=["minor_league_links", "people_identifiers"],
            expected_fields=["playerID", "season", "minor_league_team", "affiliate", "level"],
        ),
        _source(
            source_id="statcast_batted_ball_research_lane",
            source_name="Statcast batted-ball research lane",
            source_family="statcast_public_data",
            data_category="statcast_batted_ball",
            source_access_type="research_required",
            source_kind="research_lane",
            current_phase_allowed=False,
            approval_status="research_required",
            terms_review_status="research_required",
            robots_review_status="review_required",
            structured_data_available=False,
            live_download_supported=False,
            expected_granularity="batted_ball",
            expected_join_keys=["game_pk", "pitch_number", "batter"],
            likely_supported_features=["batted_ball_quality_candidates", "statcast_quality"],
            blocked_features=["batted_ball_quality_candidates", "statcast_quality"],
            blockers=["terms_unclear_research_required"],
            expected_fields=["game_pk", "batter", "launch_speed", "launch_angle", "bb_type", "hit_distance_sc", "hc_x", "hc_y"],
            safety_notes="blocked until a safe non-scraping feed is verified",
        ),
        _source(
            source_id="market_odds_blocked",
            source_name="MLB market odds blocked lane",
            source_family="market_odds_blocked",
            data_category="market_odds",
            source_access_type="research_required",
            source_kind="research_lane",
            current_phase_allowed=False,
            approval_status="blocked",
            terms_review_status="research_required",
            robots_review_status="not_applicable",
            license_status="unknown",
            future_paid_candidate=True,
            requires_budget_approval=True,
            paid_or_freemium=True,
            automation_allowed=False,
            structured_data_available=False,
            live_download_supported=False,
            expected_granularity="game_market_line",
            expected_join_keys=["game_id", "season"],
            likely_supported_features=["market_odds"],
            blocked_features=["market_odds"],
            blockers=["paid_or_budget_required"],
            expected_fields=["game_id", "date", "moneyline", "spread_line", "total_line", "closing_line"],
            safety_notes="no-spend posture keeps this lane blocked",
        ),
        _source(
            source_id="managers_coaches_mlb_stats_api",
            source_name="MLB Stats API managers/coaches",
            source_family="mlb_stats_api",
            data_category="managers_coaches",
            source_access_type="open_public",
            source_kind="open_public_api",
            current_phase_allowed=True,
            approval_status="approved_open_public",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["json"],
            expected_granularity="team_season_staff",
            expected_join_keys=["team_id", "season", "staff_name"],
            likely_supported_features=["managers_coaches", "team_identity"],
            expected_fields=["team_id", "season", "manager_name", "role", "start_date", "end_date"],
        ),
        _source(
            source_id="franchises_lahman",
            source_name="Lahman franchises",
            source_family="lahman_database",
            data_category="franchises",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="franchise_identity",
            expected_join_keys=["franchID"],
            likely_supported_features=["franchises", "team_identity"],
            expected_fields=["franchID", "team_name", "active", "first_year", "last_year", "city", "nickname"],
        ),
        _source(
            source_id="people_identifiers_chadwick",
            source_name="Chadwick people identifiers",
            source_family="chadwick_register",
            data_category="people_identifiers",
            source_access_type="open_dataset",
            source_kind="open_data_dataset",
            current_phase_allowed=True,
            approval_status="approved_open_historical",
            terms_review_status="reviewed_open_allowed",
            license_status="open_verified",
            expected_formats=["csv"],
            expected_granularity="person_identifier",
            expected_join_keys=["key_mlbam", "key_retro", "key_bbref"],
            likely_supported_features=["people_identifiers", "minor_league_links"],
            expected_fields=["key_mlbam", "key_retro", "key_bbref", "key_fangraphs", "name_first", "name_last"],
        ),
        _source(
            source_id="structured_wiki_seed",
            source_name="Wikidata/Wikipedia structured seed",
            source_family="wikidata_wikipedia_seed",
            data_category="structured_wiki_seed",
            source_access_type="structured_open_data",
            source_kind="structured_open_data",
            current_phase_allowed=True,
            approval_status="approved_open_structured",
            terms_review_status="reviewed_open_allowed",
            license_status="cc0",
            structured_seed_supported=True,
            expected_formats=["json", "sparql_json"],
            expected_granularity="entity_seed",
            expected_join_keys=["wikidata_qid", "wikipedia_title"],
            likely_supported_features=["team_identity", "franchises", "stadiums", "managers_coaches", "people_identifiers"],
            expected_fields=["wikidata_qid", "wikipedia_title", "label", "description", "official_website", "latitude", "longitude", "inception", "dissolution"],
            safety_notes="structured seed requires explicit AllowStructuredSeed and compact normalized rows only",
        ),
        _source(
            source_id="official_public_web_research",
            source_name="Official MLB/team public web research",
            source_family="official_public_web",
            data_category="official_public_web_research",
            source_access_type="public_web",
            source_kind="html_pages",
            current_phase_allowed=False,
            approval_status="blocked",
            terms_review_status="terms_unclear",
            robots_review_status="review_required",
            license_status="unknown",
            raw_html_required=True,
            crawl_supported=True,
            structured_data_available=False,
            expected_granularity="page_fact",
            expected_join_keys=["page_url"],
            likely_supported_features=["managers_coaches", "stadiums"],
            blocked_features=["official_public_web_research"],
            blockers=["html_scraping_terms_unclear"],
            expected_fields=["page_url", "page_title", "press_release_date", "team_name", "manager_name", "ballpark_name"],
            safety_notes="crawler gates may be added later, but this lane stays blocked until robots/terms are clear",
        ),
        _source(
            source_id="manual_csv_import",
            source_name="Manual MLB CSV import",
            source_family="manual_csv_import",
            data_category="manual_csv_import",
            source_access_type="manual_import",
            source_kind="manual_csv",
            current_phase_allowed=True,
            approval_status="approved_manual_import",
            terms_review_status="user_supplied",
            license_status="user_declared",
            manual_import_supported=True,
            expected_formats=["csv"],
            expected_granularity="user_supplied_row",
            expected_join_keys=["source_label", "season"],
            likely_supported_features=["managers_coaches", "injuries", "lineups", "stadiums"],
            expected_fields=["source_label", "source_license", "season", "team", "event_date", "player_id", "manager_name", "ballpark_name", "injury_status", "lineup_slot"],
            safety_notes="explicit source_license required for every import",
        ),
    ]


def source_by_id(source_id: str) -> dict[str, Any] | None:
    for source in mlb_open_data_sources():
        if source["source_id"] == source_id:
            return source
    return None


def build_mlb_open_data_source_report(*, base_data_dir: str | Path | None = None) -> dict[str, Any]:
    sources = mlb_open_data_sources()
    categories_present = sorted({str(source["data_category"]) for source in sources})
    missing_categories = [category for category in REQUIRED_DATA_CATEGORIES if category not in categories_present]
    enabled_count = sum(1 for source in sources if source.get("enabled"))
    paid_enabled = sum(
        1
        for source in sources
        if source.get("enabled") and (source.get("future_paid_candidate") or source.get("requires_budget_approval") or source.get("paid_or_freemium"))
    )
    approval_counts = Counter(str(source.get("approval_status") or "unknown") for source in sources)
    approved = [source["source_id"] for source in sources if source.get("current_phase_allowed") and not source.get("requires_budget_approval") and not source.get("future_paid_candidate")]
    structured_seed_sources = [source["source_id"] for source in sources if source.get("structured_seed_supported")]
    manual_import_sources = [source["source_id"] for source in sources if source.get("manual_import_supported")]
    terms_review = [source["source_id"] for source in sources if str(source.get("terms_review_status") or "").endswith("required") or source.get("approval_status") in {"blocked", "research_required"}]
    api_key_sources = [source["source_id"] for source in sources if source.get("requires_api_key")]
    budget_sources = [source["source_id"] for source in sources if source.get("requires_budget_approval") or source.get("future_paid_candidate")]
    blocked_or_research = [source["source_id"] for source in sources if not source.get("current_phase_allowed")]
    ok = enabled_count == 0 and paid_enabled == 0 and not missing_categories
    return mlb_safe_payload(
        {
            "ok": ok,
            "status": "ok" if ok else "blocked",
            "schema_version": MLB_OPEN_DATA_SOURCE_SCHEMA_VERSION,
            "created_at": utc_now_iso(),
            "run_id": sanitize_filename(f"mlb_open_data_sources_{utc_now_iso().replace(':', '-')}_{uuid4().hex[:8]}"),
            "module": MLB_MODULE,
            "runtime_data_dir": str(base_data_dir) if base_data_dir is not None else None,
            "sources_registered": len(sources),
            "required_categories": REQUIRED_DATA_CATEGORIES,
            "categories_present": categories_present,
            "missing_required_categories": missing_categories,
            "enabled_source_count": enabled_count,
            "paid_source_enabled_count": paid_enabled,
            "approval_status_counts": dict(sorted(approval_counts.items())),
            "approved_free_open_sources": approved,
            "structured_seed_sources": structured_seed_sources,
            "manual_import_sources": manual_import_sources,
            "research_or_blocked_sources": blocked_or_research,
            "terms_review_required_sources": terms_review,
            "api_key_required_sources": api_key_sources,
            "budget_approval_required_sources": budget_sources,
            "blocked_feature_families_tracked": BLOCKED_FEATURE_FAMILIES,
            "sources": sources,
            "downloads_attempted": 0,
            "downloads_succeeded": 0,
            "provider_calls_attempted": 0,
            "provider_calls_succeeded": 0,
            "provider_calls_failed": 0,
            "recommended_next_action": "run metadata checks, then explicit AllowStructuredSeed or AllowDownload for approved safe lanes",
        }
    )


def render_mlb_open_data_source_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# MLB Open Data Sources",
        "",
        f"1. sources_registered: {report.get('sources_registered')}",
        f"2. categories_present: {', '.join(report.get('categories_present') or [])}",
        f"3. missing_required_categories: {', '.join(report.get('missing_required_categories') or []) if report.get('missing_required_categories') else 'none'}",
        f"4. enabled_source_count: {report.get('enabled_source_count')}",
        f"5. paid_source_enabled_count: {report.get('paid_source_enabled_count')}",
        f"6. approved_free_open_sources: {', '.join(report.get('approved_free_open_sources') or []) if report.get('approved_free_open_sources') else 'none'}",
        f"7. structured_seed_sources: {', '.join(report.get('structured_seed_sources') or []) if report.get('structured_seed_sources') else 'none'}",
        f"8. manual_import_sources: {', '.join(report.get('manual_import_sources') or []) if report.get('manual_import_sources') else 'none'}",
        f"9. research_or_blocked_sources: {', '.join(report.get('research_or_blocked_sources') or []) if report.get('research_or_blocked_sources') else 'none'}",
        f"10. terms_review_required_sources: {', '.join(report.get('terms_review_required_sources') or []) if report.get('terms_review_required_sources') else 'none'}",
        "11. safety: provider_calls_attempted=0; downloads_attempted=0; provider_write=false; execution_allowed=false; raw_payload_included=false; secrets_included=false",
        "",
        "## Sources",
    ]
    for source in report.get("sources") or []:
        lines.append(
            f"- {source.get('source_id')}: category={source.get('data_category')}; allowed={str(source.get('current_phase_allowed')).lower()}; enabled=false; access={source.get('source_access_type')}; blockers={', '.join(source.get('blockers') or []) or 'none'}"
        )
    return "\n".join(lines) + "\n"


def write_mlb_open_data_source_report(report: dict[str, Any], *, base_data_dir: str | Path | None = None) -> dict[str, str]:
    root = mlb_report_root(base_data_dir=base_data_dir, subdir="sources")
    created = str(report.get("created_at") or utc_now_iso())
    day = created[:10]
    run_id = sanitize_filename(str(report.get("run_id") or f"mlb_open_data_sources_{created}_{uuid4().hex[:8]}"))
    latest_json = root / "latest.json"
    latest_md = root / "latest.md"
    item_json = root / "items" / f"{run_id}.json"
    item_md = root / "items" / f"{run_id}.md"
    daily_json = root / "daily" / f"{day}.json"
    daily_md = root / "daily" / f"{day}.md"
    paths = {
        "latest_json_path": mlb_rel(latest_json, base_data_dir),
        "latest_markdown_path": mlb_rel(latest_md, base_data_dir),
        "item_json_path": mlb_rel(item_json, base_data_dir),
        "item_markdown_path": mlb_rel(item_md, base_data_dir),
        "daily_json_path": mlb_rel(daily_json, base_data_dir),
        "daily_markdown_path": mlb_rel(daily_md, base_data_dir),
    }
    payload = mlb_safe_payload({**report, **paths})
    markdown = render_mlb_open_data_source_markdown(payload)
    mlb_atomic_write_json(latest_json, payload)
    mlb_atomic_write_text(latest_md, markdown)
    mlb_atomic_write_json(item_json, payload)
    mlb_atomic_write_text(item_md, markdown)
    mlb_atomic_write_json(daily_json, payload)
    mlb_atomic_write_text(daily_md, markdown)
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--persist", action="store_true")
    args = parser.parse_args(argv)
    report = build_mlb_open_data_source_report()
    paths: dict[str, str] = {}
    if args.persist:
        paths = write_mlb_open_data_source_report(report)
        report.update(paths)
    print(
        json.dumps(
            {
                "ok": bool(report.get("ok")),
                "status": report.get("status"),
                "run_id": report.get("run_id"),
                "sources_registered": report.get("sources_registered"),
                "categories_present": report.get("categories_present"),
                "missing_required_categories": report.get("missing_required_categories"),
                "enabled_source_count": 0,
                "paid_source_enabled_count": 0,
                "provider_calls_attempted": 0,
                "downloads_attempted": 0,
                "provider_write": False,
                "execution_allowed": False,
                "raw_payload_included": False,
                "secrets_included": False,
                "latest_json_path": paths.get("latest_json_path"),
                "latest_markdown_path": paths.get("latest_markdown_path"),
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0 if report.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(main())
