from __future__ import annotations

from collections.abc import Iterable

from automation_scheduler.backtest_dataset_builder import (
    PAPER_ONLY_FIXTURE_OPTIONAL_FIELDS,
    PAPER_ONLY_FIXTURE_REQUIRED_FIELDS,
)
from automation_scheduler.streamlit_dashboard_data import READINESS_DISPLAY_FIELDS
from automation_scheduler.technical_signal_fields import (
    TECHNICAL_SIGNAL_FIELDS,
    TECHNICAL_SIGNAL_FIELDS_BY_MARKET,
    technical_fields_for_market,
)


def _dedupe(items: Iterable[str]) -> list[str]:
    return list(dict.fromkeys(item for item in items if item))


UNIVERSAL_ROW_IDENTITY_FIELDS = [
    "fixture_id",
    "sport_or_market",
    "market_type",
    "asset_class",
    "event_id",
    "event_name",
    "event_date",
    "timestamp",
    "prediction_target",
    "selection",
    "source_type",
    "execution_mode",
    "data_source_name",
    "rows_tested",
    "rows_valid",
    "rows_invalid",
    "missing_field_reasons",
    "warning_reasons",
]

PAPER_FIXTURE_FIELD_GROUPS = {
    "paper_fixture_fields": _dedupe(
        [
            *PAPER_ONLY_FIXTURE_REQUIRED_FIELDS,
            *PAPER_ONLY_FIXTURE_OPTIONAL_FIELDS,
        ]
    )
}

REVIEW_OUTPUT_FIELD_GROUPS = {
    "universal_row_identity_fields": UNIVERSAL_ROW_IDENTITY_FIELDS,
    "readiness_output_fields": [
        "validation_result",
        "evaluation_result",
        "readiness_payload",
        "readiness_rows",
        "validation_status",
        "threshold_review_only",
        "validity_is_backend_gate",
        "low_sample_size_does_not_hide_valid_results",
        "quality_not_automatically_labeled",
        "prediction_testing_started",
        "live_connectors_enabled",
        "api_calls_enabled",
        "database_writes_enabled",
    ],
    "evaluation_output_fields": [
        "rows_tested",
        "rows_valid",
        "rows_invalid",
        "missing_field_reasons",
        "warning_reasons",
        "evaluations",
        "evaluations_count",
        "paper_result_counts",
        "total_paper_ev",
        "total_paper_stake_units",
    ],
    "pipeline_output_fields": [
        "validation_result",
        "evaluation_result",
        "readiness_payload",
        "readiness_rows",
        "rows_tested",
        "rows_valid",
        "rows_invalid",
        "missing_field_reasons",
        "warning_reasons",
        "evaluations_count",
        "paper_result_counts",
        "total_paper_ev",
        "total_paper_stake_units",
        "validation_status",
        "threshold_review_only",
        "validity_is_backend_gate",
        "low_sample_size_does_not_hide_valid_results",
        "quality_not_automatically_labeled",
        "prediction_testing_started",
        "live_connectors_enabled",
        "api_calls_enabled",
        "database_writes_enabled",
    ],
    "universal_math_output_fields": [
        "implied_probability",
        "fair_odds",
        "break_even_probability",
        "no_vig_probability",
        "edge",
        "edge_percent",
        "expected_value",
        "ev",
        "kelly_fraction",
        "kelly_stake",
        "bankroll_cap",
        "recommended_stake",
        "confidence",
        "confidence_score",
        "no_bet_flags",
        "risk_flags",
    ],
    "paper_arbitrage_output_fields": [
        "paper_arbitrage_percentage",
        "paper_arbitrage_window",
        "paper_arbitrage_timeframe",
        "paper_arbitrage_start_time",
        "paper_arbitrage_end_time",
        "paper_arbitrage_basis",
        "paper_arbitrage_opportunity_count",
        "paper_arbitrage_best_percentage",
        "paper_arbitrage_average_percentage",
        "paper_arbitrage_liquidity_adjusted_percentage",
        "paper_arbitrage_after_spread_percentage",
        "paper_arbitrage_after_fees_percentage",
        "paper_arbitrage_review_note",
    ],
    "backtest_clv_output_fields": [
        "final_result",
        "profit_loss",
        "pnl",
        "roi",
        "yield",
        "profit_factor",
        "closing_line",
        "closing_price",
        "clv",
        "clv_percent",
        "closing_line_value",
        "closing_line_value_pct",
        "paper_profit_loss",
        "paper_stake",
    ],
}

UNIVERSAL_MATH_OUTPUT_FIELDS = REVIEW_OUTPUT_FIELD_GROUPS["universal_math_output_fields"]

PAPER_EVALUATION_OUTPUT_FIELDS = REVIEW_OUTPUT_FIELD_GROUPS["evaluation_output_fields"] + [
    "paper_edge",
    "paper_ev",
    "paper_stake_units",
    "paper_result",
]

PAPER_ARBITRAGE_OUTPUT_FIELDS = REVIEW_OUTPUT_FIELD_GROUPS["paper_arbitrage_output_fields"]

TECHNICAL_SIGNAL_EXCLUDED_UNIVERSAL_MATH_FIELDS = [
    "ev",
    "expected_value",
    "edge",
    "arbitrage",
    "kelly",
    "fair_odds",
    "implied_probability",
    "bankroll",
    "confidence",
    "no_bet",
    "no-bet",
    "paper_arbitrage_percentage",
]

SPORTS_MODEL_INPUT_FIELD_GROUPS = {
    "odds_fields": [
        "sport",
        "league",
        "event_id",
        "event_name",
        "event_date",
        "start_time",
        "market",
        "selection",
        "line",
        "total_line",
        "spread_line",
        "moneyline",
        "team_total",
        "player_prop",
        "alternate_line",
        "book",
        "sportsbook",
        "book_count",
        "consensus_line",
        "opening_line",
        "current_line",
        "closing_line",
        "limits",
        "odds_american",
        "market_odds_american",
        "implied_probability",
        "model_probability",
        "expected_value",
        "stake_units",
        "bankroll_snapshot",
    ],
    "market_fields": [
        "sport_or_market",
        "market_type",
        "asset_class",
        "teams",
        "home_team",
        "away_team",
        "matchup",
        "home_away",
        "team_context",
        "player_context",
    ],
    "line_movement_fields": [
        "line_open",
        "line_current",
        "line_change",
        "market_odds_american",
        "opening_line",
        "current_line",
        "closing_line",
    ],
    "volatility_fields": [
        "implied_volatility",
        "volatility_rank",
        "volatility_regime",
    ],
    "team_context_fields": [
        "teams",
        "home_team",
        "away_team",
        "team_context",
        "coach_context",
        "motivation_context",
        "news_context",
    ],
    "player_context_fields": [
        "player_context",
        "player_name",
        "player_team",
        "player_prop",
        "player_value",
        "player_form",
    ],
    "injury_availability_fields": [
        "injuries",
        "injury_status",
        "injury_count",
        "availability",
        "depth_chart",
    ],
    "rest_schedule_fields": [
        "rest_days",
        "back_to_back",
        "travel_distance",
        "schedule_spot",
    ],
    "weather_environment_fields": [
        "weather",
        "temperature",
        "wind_speed",
        "environment",
    ],
    "matchup_fields": [
        "matchup",
        "matchup_position",
        "matchup_type",
    ],
    "form_fields": [
        "team_form",
        "player_form",
        "recent_form",
        "last_5_games",
    ],
    "sport_specific_fields": [
        "sport_specific_context",
        "sport_specific_factors",
        "sport_specific_notes",
    ],
    "technical_signal_fields": technical_fields_for_market("sports_odds"),
    "paper_fixture_fields": [
        *PAPER_ONLY_FIXTURE_REQUIRED_FIELDS,
        *PAPER_ONLY_FIXTURE_OPTIONAL_FIELDS,
    ],
}

SPORTS_MODEL_INPUT_FIELD_GROUPS_BY_SPORT = {
    "basketball_nba": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "spread_line",
            "moneyline",
            "total_line",
            "team_total",
            "player_prop",
            "player_name",
            "player_team",
            "minutes_projection",
            "usage_rate",
            "pace",
            "offensive_rating",
            "defensive_rating",
            "rebound_rate",
            "assist_rate",
            "three_point_rate",
            "injury_status",
            "rest_days",
            "back_to_back",
            "travel_distance",
            "matchup_position",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "basketball_wnba": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "spread_line",
            "moneyline",
            "total_line",
            "team_total",
            "player_prop",
            "player_name",
            "player_team",
            "minutes_projection",
            "usage_rate",
            "pace",
            "offensive_rating",
            "defensive_rating",
            "rebound_rate",
            "assist_rate",
            "three_point_rate",
            "injury_status",
            "rest_days",
            "back_to_back",
            "travel_distance",
            "matchup_position",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "basketball_ncaab": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "spread_line",
            "moneyline",
            "total_line",
            "team_total",
            "player_prop",
            "player_name",
            "player_team",
            "minutes_projection",
            "usage_rate",
            "pace",
            "offensive_rating",
            "defensive_rating",
            "rebound_rate",
            "assist_rate",
            "three_point_rate",
            "injury_status",
            "rest_days",
            "back_to_back",
            "travel_distance",
            "matchup_position",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "basketball_ncaaw": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "spread_line",
            "moneyline",
            "total_line",
            "team_total",
            "player_prop",
            "player_name",
            "player_team",
            "minutes_projection",
            "usage_rate",
            "pace",
            "offensive_rating",
            "defensive_rating",
            "rebound_rate",
            "assist_rate",
            "three_point_rate",
            "injury_status",
            "rest_days",
            "back_to_back",
            "travel_distance",
            "matchup_position",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "americanfootball_nfl": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "spread_line",
            "moneyline",
            "total_line",
            "team_total",
            "player_prop",
            "quarterback_status",
            "offensive_line_status",
            "skill_player_availability",
            "defensive_injuries",
            "weather",
            "wind_speed",
            "temperature",
            "surface",
            "rest_days",
            "travel_distance",
            "offensive_efficiency",
            "defensive_efficiency",
            "turnover_margin",
            "explosive_play_rate",
            "red_zone_rate",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "americanfootball_ncaaf": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "spread_line",
            "moneyline",
            "total_line",
            "team_total",
            "player_prop",
            "quarterback_status",
            "offensive_line_status",
            "skill_player_availability",
            "defensive_injuries",
            "weather",
            "wind_speed",
            "temperature",
            "surface",
            "rest_days",
            "travel_distance",
            "offensive_efficiency",
            "defensive_efficiency",
            "turnover_margin",
            "explosive_play_rate",
            "red_zone_rate",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "baseball_mlb": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "moneyline",
            "run_line",
            "total_line",
            "team_total",
            "player_prop",
            "starting_pitcher",
            "starting_pitcher_hand",
            "bullpen_usage",
            "bullpen_rest",
            "lineup_confirmed",
            "batting_order",
            "handedness_split",
            "park_factor",
            "weather",
            "wind_speed",
            "temperature",
            "umpire_context",
            "team_form",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "icehockey_nhl": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "moneyline",
            "puck_line",
            "total_line",
            "team_total",
            "player_prop",
            "starting_goalie",
            "goalie_confirmed",
            "goalie_save_percentage",
            "team_rest",
            "back_to_back",
            "travel_distance",
            "shots_for",
            "shots_against",
            "expected_goals_for",
            "expected_goals_against",
            "power_play_rate",
            "penalty_kill_rate",
            "line_combinations",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "soccer": {
        "sport_specific_fields": [
            "sport",
            "league",
            "home_team",
            "away_team",
            "moneyline",
            "draw_line",
            "double_chance",
            "draw_no_bet",
            "spread_line",
            "total_goals",
            "both_teams_to_score",
            "player_prop",
            "expected_goals",
            "expected_lineup",
            "formation",
            "injuries",
            "suspensions",
            "rest_days",
            "travel_distance",
            "home_away",
            "team_form",
            "table_position",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "tennis": {
        "sport_specific_fields": [
            "sport",
            "league",
            "player_a",
            "player_b",
            "moneyline",
            "game_spread",
            "set_spread",
            "total_games",
            "surface",
            "ranking",
            "elo_rating",
            "serve_hold_rate",
            "break_rate",
            "return_points_won",
            "fatigue",
            "recent_matches",
            "injury_status",
            "head_to_head",
            "handedness",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "ufc_mma": {
        "sport_specific_fields": [
            "sport",
            "league",
            "fighter_a",
            "fighter_b",
            "moneyline",
            "method_prop",
            "round_prop",
            "distance_prop",
            "weight_class",
            "stance",
            "reach",
            "height",
            "age",
            "camp",
            "layoff_days",
            "recent_fight_history",
            "striking_accuracy",
            "striking_defense",
            "takedown_accuracy",
            "takedown_defense",
            "submission_rate",
            "knockdown_rate",
            "weight_cut_context",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "boxing": {
        "sport_specific_fields": [
            "sport",
            "league",
            "fighter_a",
            "fighter_b",
            "moneyline",
            "method_prop",
            "round_prop",
            "distance_prop",
            "weight_class",
            "stance",
            "reach",
            "height",
            "age",
            "camp",
            "layoff_days",
            "recent_fight_history",
            "striking_accuracy",
            "striking_defense",
            "takedown_accuracy",
            "takedown_defense",
            "submission_rate",
            "knockdown_rate",
            "weight_cut_context",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
    "golf": {
        "sport_specific_fields": [
            "sport",
            "league",
            "player",
            "tournament",
            "course",
            "outright_price",
            "top_5_price",
            "top_10_price",
            "top_20_price",
            "matchup_price",
            "strokes_gained_off_tee",
            "strokes_gained_approach",
            "strokes_gained_around_green",
            "strokes_gained_putting",
            "driving_distance",
            "driving_accuracy",
            "greens_in_regulation",
            "course_fit",
            "weather",
            "tee_time",
            "closing_line",
            "consensus_line",
            "book_count",
        ],
    },
}

def _base_market_fields() -> list[str]:
    return [
        "symbol",
        "ticker",
        "asset_name",
        "exchange",
        "sector",
        "industry",
        "timestamp",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "last_price",
        "bid",
        "ask",
        "bid_size",
        "ask_size",
        "spread",
        "previous_close",
        "market_cap",
        "float",
        "shares_outstanding",
    ]


STOCK_MODEL_INPUT_FIELD_GROUPS = {
    "quote_fields": _base_market_fields(),
    "line_data_fields": [
        "price_line",
        "opening_price",
        "current_price",
        "closing_price",
        "pre_market_price",
        "after_hours_price",
        "daily_high",
        "daily_low",
        "support_level",
        "resistance_level",
        "moving_average_line",
        "trend_line",
        "breakout_level",
        "breakdown_level",
        "price_gap",
    ],
    "price_action_fields": [
        "opening_price",
        "current_price",
        "closing_price",
        "pre_market_price",
        "after_hours_price",
        "daily_high",
        "daily_low",
        "price_gap",
    ],
    "volume_liquidity_fields": [
        "volume",
        "average_volume",
        "liquidity_score",
    ],
    "volatility_fields": [
        "implied_volatility",
        "historical_volatility",
        "atr",
        "beta",
    ],
    "options_chain_fields": [
        "expiration_date",
        "strike",
        "option_type",
        "call_put",
        "bid",
        "ask",
        "mid",
        "last",
        "volume",
        "open_interest",
        "implied_volatility",
        "delta",
        "gamma",
        "theta",
        "vega",
        "rho",
        "moneyness",
        "days_to_expiration",
        "put_call_ratio",
        "skew",
        "term_structure",
    ],
    "earnings_calendar_fields": [
        "earnings_date",
        "earnings_surprise",
        "guidance",
        "earnings_call_text",
        "ETF_market_data",
        "insider_transactions",
        "institutional_ownership",
    ],
    "macro_context_fields": [
        "macro_context",
        "interest_rate_context",
        "inflation_context",
        "paper_only_portfolio_simulation",
    ],
    "sector_context_fields": [
        "sector_context",
        "sector",
        "industry",
    ],
    "fundamentals_fields": [
        "revenue",
        "earnings",
        "eps",
        "pe_ratio",
        "forward_pe",
        "peg_ratio",
        "price_to_sales",
        "price_to_book",
        "free_cash_flow",
        "debt_to_equity",
        "gross_margin",
        "operating_margin",
        "net_margin",
        "analyst_rating",
        "price_target",
        "earnings_date",
        "earnings_surprise",
        "guidance",
        "revenue",
        "ETF_market_data",
        "position_sizing_simulation",
        "options_context",
        "put_call_ratio",
        "term_structure",
    ],
    "technical_indicator_fields": technical_fields_for_market("stocks"),
    "technical_signal_fields": technical_fields_for_market("stocks"),
    "risk_fields": [
        "beta",
        "drawdown",
        "risk_score",
        "position_size",
        "stop_loss",
        "take_profit",
    ],
    "paper_fixture_fields": PAPER_FIXTURE_FIELD_GROUPS["paper_fixture_fields"],
}

CRYPTO_MODEL_INPUT_FIELD_GROUPS = {
    "quote_fields": [
        "symbol",
        "asset_name",
        "exchange",
        "pair",
        "base_asset",
        "quote_asset",
        "timestamp",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "last_price",
        "bid",
        "ask",
        "spread",
        "market_cap",
        "circulating_supply",
    ],
    "orderbook_fields": [
        "order_book_depth",
        "bid",
        "ask",
        "bid_size",
        "ask_size",
        "spread",
        "market_depth",
        "liquidity_depth",
        "open_interest",
    ],
    "chain_fields": [
        "active_addresses",
        "transaction_count",
        "exchange_inflows",
        "exchange_outflows",
        "wallet_concentration",
        "network_fees",
        "gas_fees",
        "hash_rate",
        "staking_rate",
        "stablecoin_flows",
        "whale_activity_proxy",
    ],
    "funding_fields": [
        "funding_rates",
        "open_interest",
        "exchange_inflows",
        "exchange_outflows",
    ],
    "liquidity_fields": [
        "dex_liquidity",
        "liquidity_depth",
        "volume_liquidity",
        "order_book_depth",
    ],
    "volatility_fields": [
        "implied_volatility",
        "historical_volatility",
        "regime_detection",
    ],
    "macro_context_fields": [
        "risk_asset_correlation",
        "regime_detection",
        "macro_regime",
        "paper_only_strategy_replay",
    ],
    "sentiment_fields": [
        "social_sentiment",
        "news_sentiment",
        "fear_greed_index",
    ],
    "technical_indicator_fields": technical_fields_for_market("crypto"),
    "technical_signal_fields": TECHNICAL_SIGNAL_FIELDS,
    "risk_fields": [
        "volatility_regime",
        "drawdown",
        "risk_score",
        "position_size",
    ],
    "paper_fixture_fields": PAPER_FIXTURE_FIELD_GROUPS["paper_fixture_fields"],
}

PREDICTION_MARKET_MODEL_INPUT_FIELD_GROUPS = {
    "contract_fields": [
        "contract_id",
        "market_id",
        "event_id",
        "event_name",
        "market_title",
        "contract_title",
        "category",
        "event_metadata",
        "yes_contract",
        "no_contract",
        "outcome_options",
        "source_url",
        "oracle_source",
    ],
    "market_fields": [
        "category",
        "event_metadata",
        "timestamp",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "yes_price",
        "no_price",
        "mid_price",
        "bid",
        "ask",
        "spread",
        "implied_probability",
        "market_probability",
        "model_probability",
        "price_probability_fields",
    ],
    "orderbook_fields": [
        "orderbook_depth",
        "best_bid",
        "best_ask",
        "bid_size",
        "ask_size",
        "open_interest",
        "liquidity",
        "liquidity_score",
        "market_depth",
        "order_flow",
    ],
    "price_probability_fields": [
        "implied_probability",
        "market_probability",
        "model_probability",
        "price_probability_fields",
    ],
    "liquidity_fields": [
        "liquidity",
        "liquidity_score",
        "market_depth",
    ],
    "line_movement_fields": [
        "timestamp",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "ema_12",
        "ema_26",
        "macd",
        "macd_signal_line",
        "macd_histogram",
        "macd_divergence",
        "rsi",
        "adx",
        "vwap",
        "market_breadth",
    ],
    "settlement_fields": [
        "settlement_rules",
        "settlement_date",
        "settlement_source",
        "outcome_known",
        "result_label",
    ],
    "event_context_fields": [
        "event_id",
        "event_name",
        "category",
        "event_metadata",
    ],
    "resolution_criteria_fields": [
        "resolution_criteria",
        "oracle_source",
        "source_url",
    ],
    "volatility_fields": [
        "implied_volatility",
        "volatility_regime",
        "regime_detection",
    ],
    "technical_signal_fields": technical_fields_for_market("prediction_markets"),
    "arbitrage_fields": [
        "cross_market_match",
        "equivalent_contract",
        "sportsbook_reference",
        "stock_reference",
        "crypto_reference",
        "yes_no_sum",
        "arbitrage_gap",
        "two_way_arbitrage",
        "three_way_arbitrage",
        "liquidity_adjusted_edge",
        "settlement_risk",
    ],
    "risk_fields": [
        "volatility_regime",
        "liquidity_risk",
        "settlement_risk",
        "position_size",
        "bankroll_snapshot",
    ],
    "paper_fixture_fields": PAPER_FIXTURE_FIELD_GROUPS["paper_fixture_fields"],
}

ZERO_DTE_MODEL_INPUT_FIELD_GROUPS = {
    "underlying_identity_fields": [
        "underlying_symbol",
        "underlying_price",
        "trade_date",
        "timestamp",
        "market_type",
        "asset_class",
    ],
    "underlying_quote_fields": [
        "underlying_open",
        "underlying_high",
        "underlying_low",
        "underlying_close",
        "underlying_volume",
        "vwap",
    ],
    "underlying_line_data_fields": [
        "support_level",
        "resistance_level",
        "opening_price",
        "current_price",
        "closing_price",
        "price_gap",
        "trend_line",
        "breakout_level",
        "breakdown_level",
    ],
    "underlying_price_action_fields": [
        "underlying_open",
        "underlying_high",
        "underlying_low",
        "underlying_close",
        "underlying_volume",
        "price_gap",
    ],
    "technical_signal_fields": technical_fields_for_market("0dte_options"),
    "options_contract_fields": [
        "expiration_date",
        "days_to_expiration",
        "minutes_to_expiration",
        "strike",
        "option_type",
        "call_put",
        "premium",
        "risk_free_rate",
    ],
    "options_quote_fields": [
        "bid",
        "ask",
        "mid",
        "mark",
        "last_price",
        "volume",
        "open_interest",
    ],
    "greeks_fields": [
        "implied_volatility",
        "delta",
        "gamma",
        "theta",
        "vega",
        "rho",
        "moneyness",
        "intrinsic_value",
        "extrinsic_value",
    ],
    "expiration_fields": [
        "expiration_date",
        "days_to_expiration",
        "minutes_to_expiration",
    ],
    "volatility_fields": [
        "implied_volatility",
        "historical_volatility",
        "volatility_regime",
    ],
    "liquidity_spread_fields": [
        "spread",
        "spread_percent",
        "liquidity",
        "liquidity_score",
    ],
    "risk_fields": [
        "risk_free_rate",
        "bankroll_snapshot",
        "stake_units",
        "position_size",
    ],
    "macro_event_fields": [
        "macro_context",
        "fed_event_context",
        "market_regime",
    ],
    "earnings_event_fields": [
        "earnings_context",
        "earnings_date",
        "earnings_surprise",
    ],
    "intraday_context_fields": [
        "timestamp",
        "opening_price",
        "current_price",
        "closing_price",
        "trend_line",
    ],
    "paper_fixture_fields": PAPER_FIXTURE_FIELD_GROUPS["paper_fixture_fields"],
}

MODEL_DATA_FIELD_GROUPS_BY_MODE = {
    "one_sport": {
        **SPORTS_MODEL_INPUT_FIELD_GROUPS,
        **REVIEW_OUTPUT_FIELD_GROUPS,
        **PAPER_FIXTURE_FIELD_GROUPS,
    },
    "one_stock_market": {
        **STOCK_MODEL_INPUT_FIELD_GROUPS,
        **REVIEW_OUTPUT_FIELD_GROUPS,
        **PAPER_FIXTURE_FIELD_GROUPS,
    },
    "one_crypto_market": {
        **CRYPTO_MODEL_INPUT_FIELD_GROUPS,
        **REVIEW_OUTPUT_FIELD_GROUPS,
        **PAPER_FIXTURE_FIELD_GROUPS,
    },
    "one_prediction_market": {
        **PREDICTION_MARKET_MODEL_INPUT_FIELD_GROUPS,
        **REVIEW_OUTPUT_FIELD_GROUPS,
        **PAPER_FIXTURE_FIELD_GROUPS,
    },
    "one_0dte_options_trade": {
        **ZERO_DTE_MODEL_INPUT_FIELD_GROUPS,
        **REVIEW_OUTPUT_FIELD_GROUPS,
        **PAPER_FIXTURE_FIELD_GROUPS,
    },
}

MODEL_DATA_FIELD_CATALOG_SOURCE_FILES = [
    "automation_scheduler/technical_signal_fields.py",
    "automation_scheduler/model_data_field_catalog.py",
    "automation_scheduler/data_source_registry.py",
    "streamlit_app.py",
    "quant_engine.py",
    "risk_engine.py",
]


def field_groups_for_model_mode(mode: str) -> dict[str, list[str]]:
    groups = MODEL_DATA_FIELD_GROUPS_BY_MODE.get(mode, MODEL_DATA_FIELD_GROUPS_BY_MODE["one_sport"])
    return {group_name: list(fields) for group_name, fields in groups.items()}


def fields_for_model_mode(mode: str) -> list[str]:
    groups = field_groups_for_model_mode(mode)
    return _dedupe(field for fields in groups.values() for field in fields)


def fields_for_sport(sport_key: str) -> list[str]:
    sport_groups = SPORTS_MODEL_INPUT_FIELD_GROUPS_BY_SPORT.get(sport_key, {})
    combined = [
        *fields_for_model_mode("one_sport"),
        *(
            field
            for fields in sport_groups.values()
            for field in fields
        ),
    ]
    return _dedupe(combined)
