from __future__ import annotations

import csv
import hashlib
import io
import json
import subprocess
from pathlib import Path
from typing import Any

from .oxylabs_residential_proxy_adapter import OxylabsResidentialProxyAdapter
from .oxylabs_web_scraper_api_adapter import OxylabsWebScraperApiAdapter
from .retrieval_policy import normalize_domain
from .scheduler_config import utc_now_iso


RUN_MODE = "completed_sports_source_policy_exhaustion_and_safe_public_extraction_finality"
REPORT_ROOT = Path("reports")
MANUAL_TEMPLATE_ROOT = Path("data") / "manual_import_templates"
COMPLETED_SPORTS_DATA_ROOT = Path("data") / "data_sources" / "completed_sports_policy_review"

SPORTS_INCLUDED = (
    "NFL",
    "MLB",
    "NBA",
    "WNBA",
    "NCAAB",
    "NCAAW",
    "NHL",
    "Soccer",
)

FINAL_POLICY_DECISIONS = (
    "accepted_for_automated_normalized_backfill",
    "accepted_for_manual_import_only",
    "accepted_for_postmatch_training_only",
    "accepted_for_metadata_only",
    "accepted_for_attribution_only",
    "rejected_policy_blocked",
    "rejected_login_paywall_captcha",
    "rejected_robots_blocked",
    "rejected_terms_blocked",
    "rejected_unstable_schema",
    "rejected_duplicate_source",
    "rejected_upstream_source_unclear",
    "license_terms_unclear",
    "unavailable_after_exhaustive_search",
)

FINAL_SOURCE_STATES = (
    "free_open_backfilled",
    "free_open_postmatch_training_only",
    "free_open_metadata_only",
    "manual_import_required",
    "paid_subscription_required",
    "policy_blocked",
    "robots_blocked",
    "terms_blocked",
    "login_paywall_captcha_blocked",
    "license_terms_unclear",
    "unavailable_after_exhaustive_search",
    "obsolete_or_duplicate",
)

SAFE_FLAGS: dict[str, Any] = {
    "provider_write": False,
    "execution_allowed": False,
    "execution_allowed_count": 0,
    "live_execution_enabled": False,
    "auto_execution_enabled": False,
    "kalshi_order_execution_enabled": False,
    "sportsbook_bet_execution_enabled": False,
    "broker_order_execution_enabled": False,
    "stock_trade_execution_enabled": False,
    "crypto_trade_execution_enabled": False,
    "actual_orders_submitted": 0,
    "actual_bets_submitted": 0,
    "actual_trades_submitted": 0,
    "actual_crypto_swaps_submitted": 0,
    "raw_payload_included": False,
    "raw_html_persisted": False,
    "raw_screenshot_persisted": False,
    "secrets_included": False,
    "paid_source_enabled_count": 1,
    "AllowOxylabs": True,
    "AllowPaidRetrieval": True,
    "AllowActiveDiscovery": True,
    "AllowSearchDiscovery": True,
    "AllowSourcePolicyReview": True,
    "AllowRobotsReview": True,
    "AllowTermsReview": True,
    "AllowLicenseReview": True,
    "AllowApiDocsReview": True,
    "AllowDataDictionaryReview": True,
    "AllowSchemaExpansion": True,
    "AllowSampleVerification": True,
    "AllowBackfill": True,
    "AllowFinalityAudit": True,
}

_FETCH_CACHE: dict[str, dict[str, Any]] = {}


def current_utc() -> str:
    return utc_now_iso()


def json_safe(value: Any) -> Any:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, dict):
        return {str(key): json_safe(val) for key, val in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    return str(value)


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(json_safe(payload), indent=2, sort_keys=True), encoding="utf-8")


def write_md(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def stable_hash(payload: Any) -> str:
    text = json.dumps(json_safe(payload), sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def url_hash(url: str) -> str:
    return hashlib.sha256(str(url).strip().encode("utf-8")).hexdigest()


def git_branch() -> str:
    try:
        return subprocess.check_output(["git", "branch", "--show-current"], text=True).strip()
    except Exception:
        return ""


def git_commit() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        return ""


def extract_web_scraper_content(text: str) -> str:
    try:
        payload = json.loads(text)
    except Exception:
        return text
    results = payload.get("results")
    if isinstance(results, list):
        parts: list[str] = []
        for result in results:
            if not isinstance(result, dict):
                continue
            for key in ("content", "html", "body"):
                value = result.get(key)
                if isinstance(value, str) and value.strip():
                    parts.append(value)
                    break
        if parts:
            return "\n".join(parts)
    job = payload.get("job")
    if isinstance(job, dict):
        content = job.get("content")
        if isinstance(content, str) and content.strip():
            return content
    return text


def normalized_domain(value: str) -> str:
    return normalize_domain(value)


def _policy_source(
    source_id: str,
    sport: str,
    sport_group: str,
    source_name: str,
    domain: str,
    source_path_or_path_pattern: str,
    field_group: str,
    prior_status: str,
    prior_report_source: str,
    reason_for_recheck: str,
    expected_calibration_value: str,
    expected_backfill_value: str,
    target_final_decision: str,
    final_state_target: str,
    *,
    source_url: str | None = None,
    source_type: str = "public_page",
    source_owner_if_known: str = "",
    mirror_or_original_source: str = "original",
    likely_upstream_source: str = "",
    public_or_private: str = "public",
    login_required: bool = False,
    paywall_required: bool = False,
    captcha_required: bool = False,
    session_required: bool = False,
    terms_url: str = "",
    privacy_url: str = "",
    license_url: str = "",
    robots_url: str = "",
    api_docs_url: str = "",
    data_dictionary_url: str = "",
    github_license_url: str = "",
    readme_url: str = "",
    attribution_url: str = "",
    acceptable_use_url: str = "",
    copyright_notice_url: str = "",
    primary_transport: str = "web_scraper_api",
    sample_strategy: str = "none",
    sample_url: str = "",
    normalized_entity_level: str = "source",
    repo_field_mapping: list[str] | None = None,
    new_fields_recommended: list[str] | None = None,
    sport_model_relevance: str = "medium",
    duplicate_existing_source: bool = False,
    upstream_source_unclear: bool = False,
    timestamp_available: bool = False,
    event_time_available: bool = False,
    game_or_match_start_time_available: bool = False,
    data_publication_time_available: bool = False,
    future_leakage_risk: str = "low",
    post_event_only: bool = False,
    pre_event_available: bool = False,
    usable_for_prematch_model: bool = False,
    usable_for_postmatch_training_only: bool = False,
    cutoff_safe: bool = False,
    cutoff_safety_reason: str = "",
    normalized_fact_persistence_allowed: bool = False,
    aggregate_feature_persistence_allowed: bool = False,
    source_hash_persistence_allowed: bool = True,
    attribution_storage_required: bool = True,
    required_attribution_text_or_url_hash: str = "",
    policy_mode: str = "metadata_only",
    fields_available: list[str] | None = None,
    exact_blocker_or_allowance: str = "",
) -> dict[str, Any]:
    resolved_source_url = source_url or source_path_or_path_pattern
    resolved_robots = robots_url or f"https://{domain}/robots.txt"
    return {
        "sport": sport,
        "sport_group": sport_group,
        "source_id": source_id,
        "source_name": source_name,
        "source_domain": domain,
        "source_path_or_path_pattern": source_path_or_path_pattern,
        "source_url": resolved_source_url,
        "field_group": field_group,
        "prior_status": prior_status,
        "prior_report_source": prior_report_source,
        "reason_for_recheck": reason_for_recheck,
        "policy_review_required": True,
        "expected_calibration_value": expected_calibration_value,
        "expected_backfill_value": expected_backfill_value,
        "target_final_decision": target_final_decision,
        "final_state_target": final_state_target,
        "source_type": source_type,
        "source_owner_if_known": source_owner_if_known,
        "mirror_or_original_source": mirror_or_original_source,
        "likely_upstream_source": likely_upstream_source,
        "public_or_private": public_or_private,
        "login_required": login_required,
        "paywall_required": paywall_required,
        "captcha_required": captcha_required,
        "session_required": session_required,
        "terms_url": terms_url,
        "privacy_url": privacy_url,
        "license_url": license_url,
        "robots_url": resolved_robots,
        "api_docs_url": api_docs_url,
        "data_dictionary_url": data_dictionary_url,
        "GitHub_LICENSE_url": github_license_url,
        "README_url": readme_url,
        "attribution_url": attribution_url,
        "acceptable_use_url": acceptable_use_url,
        "copyright_notice_url": copyright_notice_url,
        "primary_transport": primary_transport,
        "sample_strategy": sample_strategy,
        "sample_url": sample_url or resolved_source_url,
        "normalized_entity_level": normalized_entity_level,
        "repo_field_mapping": list(repo_field_mapping or []),
        "new_fields_recommended": list(new_fields_recommended or []),
        "sport_model_relevance": sport_model_relevance,
        "duplicate_existing_source": duplicate_existing_source,
        "upstream_source_unclear": upstream_source_unclear,
        "timestamp_available": timestamp_available,
        "event_time_available": event_time_available,
        "game_or_match_start_time_available": game_or_match_start_time_available,
        "data_publication_time_available": data_publication_time_available,
        "future_leakage_risk": future_leakage_risk,
        "post_event_only": post_event_only,
        "pre_event_available": pre_event_available,
        "usable_for_prematch_model": usable_for_prematch_model,
        "usable_for_postmatch_training_only": usable_for_postmatch_training_only,
        "cutoff_safe": cutoff_safe,
        "cutoff_safety_reason": cutoff_safety_reason,
        "raw_html_persistence_allowed": False,
        "raw_payload_persistence_allowed": False,
        "normalized_fact_persistence_allowed": normalized_fact_persistence_allowed,
        "aggregate_feature_persistence_allowed": aggregate_feature_persistence_allowed,
        "source_hash_persistence_allowed": source_hash_persistence_allowed,
        "attribution_storage_required": attribution_storage_required,
        "required_attribution_text_or_url_hash": required_attribution_text_or_url_hash or url_hash(resolved_source_url),
        "policy_mode": policy_mode,
        "fields_available": list(fields_available or []),
        "exact_blocker_or_allowance": exact_blocker_or_allowance,
    }


def completed_sports_candidate_source_catalog() -> list[dict[str, Any]]:
    return [
        _policy_source(
            "nflverse_release_data",
            "nfl",
            "nfl",
            "nflverse releases and docs",
            "github.com",
            "/nflverse/nflverse-data/releases",
            "injuries, practice reports, officials, depth charts, schedules",
            "existing_open_dataset",
            "reports/NFL_MLB_FREE_VS_PAID_SOURCE_LEDGER.json",
            "Convert broad NFL open-data lanes into exact path-level policy decisions.",
            "high",
            "low",
            "accepted_for_metadata_only",
            "free_open_metadata_only",
            source_url="https://github.com/nflverse/nflverse-data/releases",
            source_type="github_release_page",
            source_owner_if_known="nflverse",
            terms_url="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
            license_url="https://raw.githubusercontent.com/nflverse/nflverse-data/master/LICENSE.md",
            api_docs_url="https://nflreadr.nflverse.com/",
            data_dictionary_url="https://nflreadr.nflverse.com/articles/dictionary_pbp.html",
            github_license_url="https://raw.githubusercontent.com/nflverse/nflverse-data/master/LICENSE.md",
            readme_url="https://github.com/nflverse/nflverse-data",
            attribution_url="https://github.com/nflverse/nflverse-data",
            primary_transport="web_scraper_api",
            sample_strategy="metadata_only",
            normalized_entity_level="dataset",
            repo_field_mapping=["officials", "injuries", "practice_status", "depth_chart", "schedule_results"],
            sport_model_relevance="high",
            timestamp_available=True,
            game_or_match_start_time_available=True,
            data_publication_time_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Open dataset rows are timestamped and already normalized elsewhere in the repo.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="metadata_only",
            exact_blocker_or_allowance="Open GitHub dataset remains allowed, but this pass only stores policy metadata because NFL ingestion already exists.",
        ),
        _policy_source(
            "nfl_operations_officiating",
            "nfl",
            "nfl",
            "NFL operations officiating pages",
            "operations.nfl.com",
            "/officiating/",
            "officials/referee assignments",
            "policy_review_required",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Turn official NFL officiating pages into an explicit manual-only or metadata-only decision.",
            "medium",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://operations.nfl.com/officiating/",
            source_type="official_operations_page",
            source_owner_if_known="NFL",
            terms_url="https://www.nfl.com/legal/terms",
            privacy_url="https://www.nfl.com/legal/privacy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="official_assignment",
            repo_field_mapping=["officials"],
            sport_model_relevance="medium",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Manual timestamped assignment snapshots are safe when captured pregame.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="Public officiating pages can support timestamped manual imports, but this pass does not automate extraction from league web pages.",
        ),
        _policy_source(
            "nfl_official_team_staff_pages",
            "nfl",
            "nfl",
            "Official NFL team staff pages",
            "buffalobills.com",
            "/team/coaches-roster/",
            "coaching/staff sources",
            "policy_review_required",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Resolve broad official team staff/news blockers into path-specific manual or blocked decisions.",
            "medium",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://www.buffalobills.com/team/coaches-roster/",
            source_type="official_team_page",
            source_owner_if_known="NFL team site",
            terms_url="https://www.buffalobills.com/terms-and-conditions",
            privacy_url="https://www.buffalobills.com/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="team_staff",
            repo_field_mapping=["head_coach", "coordinator", "staff_history"],
            sport_model_relevance="medium",
            timestamp_available=True,
            data_publication_time_available=True,
            usable_for_postmatch_training_only=True,
            cutoff_safe=False,
            cutoff_safety_reason="Coaching/news pages are better treated as manual reference due inconsistent historical structure.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="Manual staff imports remain safer than automated crawling across team sites with inconsistent schemas.",
        ),
        _policy_source(
            "nfl_pro_football_reference",
            "nfl",
            "nfl",
            "Pro Football Reference",
            "pro-football-reference.com",
            "/",
            "advanced charting/stat mirrors",
            "blocked_reference",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Confirm the hard block path-by-path instead of leaving a generic blocked lane.",
            "high",
            "none",
            "rejected_policy_blocked",
            "policy_blocked",
            source_url="https://www.pro-football-reference.com/",
            source_type="restricted_reference_site",
            source_owner_if_known="Sports Reference",
            terms_url="https://www.sports-reference.com/termsofuse.html",
            privacy_url="https://www.sports-reference.com/privacy.html",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="site",
            repo_field_mapping=["advanced_stats_reference"],
            sport_model_relevance="high",
            policy_mode="blocked",
            exact_blocker_or_allowance="Sports Reference family pages are blocked by project policy for automated extraction.",
        ),
        _policy_source(
            "nfl_ftn_charting",
            "nfl",
            "nfl",
            "FTN premium charting paths",
            "ftnfantasy.com",
            "/nfl/",
            "advanced charting/stat mirrors",
            "blocked_paid_premium",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Finalize FTN as a paid or blocked path rather than a vague terms-review lane.",
            "high",
            "none",
            "rejected_policy_blocked",
            "policy_blocked",
            source_url="https://ftnfantasy.com/nfl",
            source_type="paid_vendor_page",
            source_owner_if_known="FTN",
            terms_url="https://ftnfantasy.com/terms-of-service",
            privacy_url="https://ftnfantasy.com/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="site",
            repo_field_mapping=["charting_features"],
            sport_model_relevance="high",
            policy_mode="blocked",
            exact_blocker_or_allowance="FTN charting is paid/premium and not approved for automated extraction in this repo.",
        ),
        _policy_source(
            "nfl_open_github_coaching_dataset",
            "nfl",
            "nfl",
            "Open GitHub coaching dataset candidate",
            "github.com",
            "/",
            "coaching/staff sources",
            "policy_review_required",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Explicitly settle whether community coaching mirrors are safe enough to automate.",
            "medium",
            "low",
            "rejected_upstream_source_unclear",
            "license_terms_unclear",
            source_url="https://github.com/search?q=NFL+coaching+dataset&type=repositories",
            source_type="github_repository_search",
            source_owner_if_known="Community mirror",
            terms_url="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
            readme_url="https://github.com/",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="dataset",
            repo_field_mapping=["coaching_history"],
            sport_model_relevance="medium",
            upstream_source_unclear=True,
            policy_mode="upstream_unclear",
            exact_blocker_or_allowance="Community coaching mirrors do not provide stable provenance or a clearly approved upstream source chain.",
        ),
        _policy_source(
            "mlb_stats_api_game_feed",
            "mlb",
            "mlb",
            "MLB Stats API game and officials endpoints",
            "statsapi.mlb.com",
            "/api/v1/schedule?sportId=1&hydrate=officials",
            "official MLB public pages, injuries/transactions, umpire assignments",
            "official_api_open",
            "reports/NFL_MLB_FREE_VS_PAID_SOURCE_LEDGER.json",
            "Classify the exact public API paths that already power safe MLB open-data features.",
            "high",
            "medium",
            "accepted_for_metadata_only",
            "free_open_metadata_only",
            source_url="https://statsapi.mlb.com/api/v1/schedule?sportId=1&hydrate=officials",
            source_type="public_json_api",
            source_owner_if_known="MLB",
            terms_url="https://www.mlb.com/official-information/terms-of-use",
            privacy_url="https://www.mlb.com/official-information/privacy-policy",
            api_docs_url="https://github.com/toddrob99/MLB-StatsAPI/wiki",
            data_dictionary_url="https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints",
            primary_transport="residential_proxy",
            sample_strategy="metadata_only",
            normalized_entity_level="api_endpoint",
            repo_field_mapping=["schedule_results", "umpire_officials", "weather", "venue"],
            sport_model_relevance="high",
            timestamp_available=True,
            event_time_available=True,
            game_or_match_start_time_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Official schedule and officials metadata are timestamped and already used through repo adapters.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="metadata_only",
            exact_blocker_or_allowance="Official public JSON metadata remains allowed, but this pass avoids broad re-backfill because MLB ingestion already exists.",
        ),
        _policy_source(
            "mlb_stats_api_draft",
            "mlb",
            "mlb",
            "MLB Draft API",
            "statsapi.mlb.com",
            "/api/v1/draft/2025?sportId=1",
            "MLB draft pages/endpoints",
            "official_api_open",
            "reports/NFL_MLB_FREE_VS_PAID_SOURCE_LEDGER.json",
            "Lock the draft endpoint into an explicit policy-approved metadata state.",
            "low",
            "low",
            "accepted_for_metadata_only",
            "free_open_metadata_only",
            source_url="https://statsapi.mlb.com/api/v1/draft/2025?sportId=1",
            source_type="public_json_api",
            source_owner_if_known="MLB",
            terms_url="https://www.mlb.com/official-information/terms-of-use",
            privacy_url="https://www.mlb.com/official-information/privacy-policy",
            api_docs_url="https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-draft",
            data_dictionary_url="https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-draft",
            primary_transport="residential_proxy",
            sample_strategy="metadata_only",
            normalized_entity_level="draft",
            repo_field_mapping=["draft_round", "pick_number", "player_name"],
            sport_model_relevance="low",
            timestamp_available=True,
            pre_event_available=False,
            usable_for_postmatch_training_only=True,
            cutoff_safe=True,
            cutoff_safety_reason="Draft data is historical metadata and does not create prematch leakage risk.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="metadata_only",
            exact_blocker_or_allowance="Official MLB draft metadata can remain stored as normalized metadata only.",
        ),
        _policy_source(
            "mlb_baseball_savant_csv_docs",
            "mlb",
            "mlb",
            "Baseball Savant public CSV paths",
            "baseballsavant.mlb.com",
            "/csv-docs",
            "Statcast/Baseball Savant public paths, batted-ball mirrors",
            "terms_review_required",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Resolve the exact public Statcast CSV lane into a training-safe or blocked final state.",
            "high",
            "medium",
            "accepted_for_postmatch_training_only",
            "free_open_postmatch_training_only",
            source_url="https://baseballsavant.mlb.com/csv-docs",
            source_type="public_csv_docs_page",
            source_owner_if_known="MLB",
            terms_url="https://www.mlb.com/official-information/terms-of-use",
            privacy_url="https://www.mlb.com/official-information/privacy-policy",
            data_dictionary_url="https://baseballsavant.mlb.com/csv-docs",
            primary_transport="web_scraper_api",
            sample_strategy="csv_rows",
            sample_url="https://baseballsavant.mlb.com/statcast_search/csv?all=true&game_date_gt=2025-06-01&game_date_lt=2025-06-02&hfSea=2025%7C&player_type=batter&group_by=name&sort_col=pa&sort_order=desc&min_pas=0&min_pitches=0&min_results=0",
            normalized_entity_level="player_game",
            repo_field_mapping=["exit_velocity", "launch_angle", "xwoba", "barrel_rate"],
            sport_model_relevance="high",
            timestamp_available=True,
            event_time_available=True,
            game_or_match_start_time_available=True,
            data_publication_time_available=False,
            post_event_only=True,
            usable_for_postmatch_training_only=True,
            cutoff_safe=True,
            cutoff_safety_reason="Statcast research CSV paths are treated as post-event or training-only in this policy pass.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="postmatch_only",
            exact_blocker_or_allowance="Public CSV research paths are allowed only for postmatch/training-safe normalized facts in this pass.",
        ),
        _policy_source(
            "mlb_retrosheet_event_files",
            "mlb",
            "mlb",
            "Retrosheet event files",
            "retrosheet.org",
            "/events/",
            "Retrosheet-derived paths, pitch-by-pitch mirrors",
            "existing_open_dataset",
            "reports/NFL_MLB_FREE_VS_PAID_SOURCE_LEDGER.json",
            "Set exact open Retrosheet paths to a clear training-safe state.",
            "high",
            "medium",
            "accepted_for_postmatch_training_only",
            "free_open_postmatch_training_only",
            source_url="https://www.retrosheet.org/game.htm",
            source_type="open_dataset_page",
            source_owner_if_known="Retrosheet",
            terms_url="https://www.retrosheet.org/notice.txt",
            license_url="https://www.retrosheet.org/notice.txt",
            readme_url="https://www.retrosheet.org/",
            primary_transport="web_scraper_api",
            sample_strategy="csv_rows",
            sample_url="https://www.retrosheet.org/events/2025eve.zip",
            normalized_entity_level="play",
            repo_field_mapping=["play_description", "inning", "outs", "runners"],
            sport_model_relevance="high",
            timestamp_available=True,
            event_time_available=True,
            post_event_only=True,
            usable_for_postmatch_training_only=True,
            cutoff_safe=True,
            cutoff_safety_reason="Retrosheet event files are historical and safe for postmatch training or evaluation.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="postmatch_only",
            exact_blocker_or_allowance="Historical Retrosheet event files remain training-safe only in this combined policy review.",
        ),
        _policy_source(
            "mlb_official_public_pages",
            "mlb",
            "mlb",
            "Official MLB public pages",
            "mlb.com",
            "/",
            "official MLB public pages, injuries/transactions",
            "policy_review_required",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Resolve older broad official public web research lanes into exact manual-only rules.",
            "medium",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://www.mlb.com/",
            source_type="official_public_page",
            source_owner_if_known="MLB",
            terms_url="https://www.mlb.com/official-information/terms-of-use",
            privacy_url="https://www.mlb.com/official-information/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="news_page",
            repo_field_mapping=["injuries", "transactions", "lineups"],
            sport_model_relevance="medium",
            timestamp_available=True,
            pre_event_available=True,
            cutoff_safe=True,
            cutoff_safety_reason="Official public news can support manual timestamped imports but not broad automated extraction in this pass.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="Public MLB pages are retained for manual timestamped imports only.",
        ),
        _policy_source(
            "mlb_baseball_reference",
            "mlb",
            "mlb",
            "Baseball Reference",
            "baseball-reference.com",
            "/",
            "reference-style advanced stat mirrors",
            "blocked_reference",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Path-level confirmation of the hard block for Baseball Reference.",
            "high",
            "none",
            "rejected_policy_blocked",
            "policy_blocked",
            source_url="https://www.baseball-reference.com/",
            source_type="restricted_reference_site",
            source_owner_if_known="Sports Reference",
            terms_url="https://www.sports-reference.com/termsofuse.html",
            privacy_url="https://www.sports-reference.com/privacy.html",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="site",
            repo_field_mapping=["advanced_reference_tables"],
            sport_model_relevance="high",
            policy_mode="blocked",
            exact_blocker_or_allowance="Sports Reference family baseball pages remain blocked for automated extraction.",
        ),
        _policy_source(
            "mlb_fangraphs",
            "mlb",
            "mlb",
            "FanGraphs",
            "fangraphs.com",
            "/",
            "advanced stat mirrors",
            "blocked_reference",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "Resolve FanGraphs into an explicit blocked or licensed path-level decision.",
            "high",
            "none",
            "rejected_policy_blocked",
            "policy_blocked",
            source_url="https://www.fangraphs.com/",
            source_type="advanced_stats_site",
            source_owner_if_known="FanGraphs",
            terms_url="https://www.fangraphs.com/terms-of-service",
            privacy_url="https://www.fangraphs.com/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="site",
            repo_field_mapping=["advanced_batting_pitching_tables"],
            sport_model_relevance="high",
            policy_mode="blocked",
            exact_blocker_or_allowance="FanGraphs remains blocked unless an explicit approved public API or licensed arrangement exists.",
        ),
        _policy_source(
            "nba_stats_pages",
            "basketball_nba",
            "basketball",
            "NBA Stats public pages/endpoints",
            "nba.com",
            "/stats",
            "NBA Stats public endpoints/pages",
            "existing_open_dataset",
            "reports/BASKETBALL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Confirm the exact public NBA stats path and keep it policy-final without redoing a broad backfill.",
            "high",
            "low",
            "accepted_for_metadata_only",
            "free_open_metadata_only",
            source_url="https://www.nba.com/stats",
            source_type="official_stats_page",
            source_owner_if_known="NBA",
            terms_url="https://www.nba.com/termsofuse",
            privacy_url="https://www.nba.com/privacy-policy",
            api_docs_url="https://github.com/swar/nba_api",
            data_dictionary_url="https://github.com/swar/nba_api/tree/master/docs/nba_api/stats/endpoints",
            primary_transport="web_scraper_api",
            sample_strategy="metadata_only",
            normalized_entity_level="stats_page",
            repo_field_mapping=["team_box_scores", "player_box_scores", "play_by_play", "officials"],
            sport_model_relevance="high",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Official stats pages are already integrated through approved open-data paths elsewhere in the repo.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="metadata_only",
            exact_blocker_or_allowance="Policy review confirms this exact official stats path is used only for metadata/provenance in this pass.",
        ),
        _policy_source(
            "wnba_stats_pages",
            "basketball_wnba",
            "basketball",
            "WNBA Stats public pages/endpoints",
            "wnba.com",
            "/",
            "WNBA Stats public endpoints/pages",
            "existing_open_dataset",
            "reports/BASKETBALL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Lock the WNBA official public stats path into the combined policy matrix.",
            "high",
            "low",
            "accepted_for_metadata_only",
            "free_open_metadata_only",
            source_url="https://www.wnba.com/",
            source_type="official_stats_page",
            source_owner_if_known="WNBA",
            terms_url="https://www.wnba.com/termsofuse",
            privacy_url="https://www.wnba.com/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="metadata_only",
            normalized_entity_level="stats_page",
            repo_field_mapping=["team_box_scores", "player_box_scores", "play_by_play"],
            sport_model_relevance="high",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Official WNBA public pages are already covered by approved open-data lanes; this pass stores only policy metadata.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="metadata_only",
            exact_blocker_or_allowance="Official WNBA public stats paths remain policy-approved metadata sources in this pass.",
        ),
        _policy_source(
            "basketball_official_injury_reports",
            "basketball_nba",
            "basketball",
            "NBA and WNBA official injury report pages",
            "nba.com",
            "/injury-report",
            "NBA/WNBA injuries/availability",
            "manual_template_ready",
            "reports/BASKETBALL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Replace vague public availability mentions with an explicit manual-only path decision.",
            "high",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://www.nba.com/injury-report",
            source_type="official_injury_page",
            source_owner_if_known="NBA",
            terms_url="https://www.nba.com/termsofuse",
            privacy_url="https://www.nba.com/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="player_game",
            repo_field_mapping=["injuries_availability"],
            sport_model_relevance="high",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Manual timestamped injury imports are cutoff-safe; this pass does not automate collection from official web pages.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="Official public injury reports remain manual-only for safe timestamped imports.",
        ),
        _policy_source(
            "basketball_ncaa_net_rankings",
            "basketball_ncaab",
            "basketball",
            "NCAA NET rankings pages",
            "ncaa.com",
            "/rankings/basketball-men/d1/ncaa-mens-basketball-net-rankings",
            "NCAA NET/SOS context",
            "manual_template_ready",
            "reports/BASKETBALL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Set the exact NCAA NET page to a manual-only final state.",
            "medium",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://www.ncaa.com/rankings/basketball-men/d1/ncaa-mens-basketball-net-rankings",
            source_type="official_ranking_page",
            source_owner_if_known="NCAA",
            terms_url="https://www.ncaa.com/terms-of-service",
            privacy_url="https://www.ncaa.com/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="team_season",
            repo_field_mapping=["strength_of_schedule_context"],
            sport_model_relevance="medium",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Manual ranking snapshots are safer than page automation for college strength-of-schedule context.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="NCAA rankings remain manual snapshot inputs only in this pass.",
        ),
        _policy_source(
            "basketball_ncaa_womens_net_rankings",
            "basketball_ncaaw",
            "basketball",
            "NCAA women's NET rankings pages",
            "ncaa.com",
            "/rankings/basketball-women/d1/womens-basketball-net-rankings",
            "NCAAW NET/SOS context",
            "manual_template_ready",
            "reports/BASKETBALL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Ensure NCAAW remains explicitly covered in the combined completed-sports policy review.",
            "medium",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://www.ncaa.com/rankings/basketball-women/d1/womens-basketball-net-rankings",
            source_type="official_ranking_page",
            source_owner_if_known="NCAA",
            terms_url="https://www.ncaa.com/terms-of-service",
            privacy_url="https://www.ncaa.com/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="team_season",
            repo_field_mapping=["strength_of_schedule_context"],
            sport_model_relevance="medium",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Manual ranking snapshots are safer than page automation for women's college strength-of-schedule context.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="NCAA women's rankings remain manual snapshot inputs only in this pass.",
        ),
        _policy_source(
            "basketball_statsperform_public_site",
            "basketball_nba",
            "basketball",
            "Stats Perform basketball public product pages",
            "statsperform.com",
            "/",
            "injuries, transactions, advanced availability feeds",
            "paid_required",
            "reports/BASKETBALL_PAID_DATA_REQUIREMENT_MATRIX.json",
            "Finalize the public product pages as paid/licensed only, with path-specific evidence.",
            "high",
            "none",
            "accepted_for_attribution_only",
            "paid_subscription_required",
            source_url="https://www.statsperform.com/",
            source_type="paid_vendor_page",
            source_owner_if_known="Stats Perform",
            terms_url="https://www.statsperform.com/terms-and-conditions/",
            privacy_url="https://www.statsperform.com/privacy-policy/",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="vendor_page",
            repo_field_mapping=["injuries_availability", "transaction_availability_volatility"],
            sport_model_relevance="high",
            policy_mode="paid",
            exact_blocker_or_allowance="Public product pages are reviewable for scope only; structured data remains paid/licensed.",
        ),
        _policy_source(
            "basketball_second_spectrum",
            "basketball_nba",
            "basketball",
            "Second Spectrum public product pages",
            "second-spectrum.com",
            "/",
            "optical/tracking mirrors",
            "paid_required",
            "reports/BASKETBALL_PAID_DATA_REQUIREMENT_MATRIX.json",
            "Finish the tracking vendor path-level review with an explicit paid outcome.",
            "high",
            "none",
            "accepted_for_attribution_only",
            "paid_subscription_required",
            source_url="https://www.second-spectrum.com/",
            source_type="paid_vendor_page",
            source_owner_if_known="Second Spectrum",
            terms_url="https://www.second-spectrum.com/privacy-policy/",
            privacy_url="https://www.second-spectrum.com/privacy-policy/",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="vendor_page",
            repo_field_mapping=["optical_tracking_player_location"],
            sport_model_relevance="high",
            policy_mode="paid",
            exact_blocker_or_allowance="Tracking product pages are reviewable, but automated extraction requires a paid/licensed feed.",
        ),
        _policy_source(
            "basketball_genius_sports",
            "basketball_ncaab",
            "basketball",
            "Genius Sports official data docs",
            "developer.geniussports.com",
            "/",
            "college lineup/on-off mirrors",
            "paid_required",
            "reports/BASKETBALL_PAID_DATA_REQUIREMENT_MATRIX.json",
            "Convert the college lineup/on-off vendor path into a final paid/licensed decision.",
            "high",
            "none",
            "accepted_for_attribution_only",
            "paid_subscription_required",
            source_url="https://developer.geniussports.com/",
            source_type="developer_docs_page",
            source_owner_if_known="Genius Sports",
            terms_url="https://www.geniussports.com/privacy-policy/",
            privacy_url="https://www.geniussports.com/privacy-policy/",
            api_docs_url="https://developer.geniussports.com/",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="vendor_page",
            repo_field_mapping=["lineup_on_off"],
            sport_model_relevance="high",
            policy_mode="paid",
            exact_blocker_or_allowance="Developer docs can be reviewed, but the structured lineup/on-off data remains licensed.",
        ),
        _policy_source(
            "basketball_restricted_reference_docs",
            "basketball_nba",
            "basketball",
            "Reference-derived basketball docs and mirrors",
            "github.com",
            "/sportsdataverse/hoopR",
            "restricted reference tables",
            "policy_blocked",
            "reports/BASKETBALL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Close the remaining basketball reference-style mirror bucket path-by-path.",
            "high",
            "none",
            "rejected_policy_blocked",
            "policy_blocked",
            source_url="https://github.com/sportsdataverse/hoopR",
            source_type="github_docs_page",
            source_owner_if_known="Community package",
            terms_url="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
            readme_url="https://github.com/sportsdataverse/hoopR",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="docs",
            repo_field_mapping=["restricted_reference_tables"],
            sport_model_relevance="high",
            policy_mode="blocked",
            exact_blocker_or_allowance="Reference-derived basketball tables remain blocked unless an explicit source path is independently approved.",
        ),
        _policy_source(
            "basketball_sportsdataverse_duplicate",
            "basketball_nba",
            "basketball",
            "SportsDataverse basketball release page",
            "github.com",
            "/sportsdataverse/",
            "duplicate box score mirror sources",
            "duplicate",
            "reports/BASKETBALL_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Explicitly classify public community release pages as duplicate where repo loaders already cover the same facts.",
            "low",
            "none",
            "rejected_duplicate_source",
            "obsolete_or_duplicate",
            source_url="https://github.com/sportsdataverse",
            source_type="github_release_page",
            source_owner_if_known="SportsDataverse",
            terms_url="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
            readme_url="https://github.com/sportsdataverse",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="dataset",
            repo_field_mapping=["duplicate_box_score_mirror_sources"],
            sport_model_relevance="low",
            duplicate_existing_source=True,
            policy_mode="duplicate",
            exact_blocker_or_allowance="Community release pages are redundant once the approved basketball loaders are already normalized.",
        ),
        _policy_source(
            "nhl_public_api",
            "icehockey_nhl",
            "nhl",
            "NHL public API and official pages",
            "api-web.nhle.com",
            "/v1/score/now",
            "official public pages, injuries/availability snapshots, public goalie-start pages",
            "existing_open_dataset",
            "reports/NHL_DATA_CALIBRATION_READINESS_REPORT.json",
            "Add path-specific policy review around NHL official public APIs without rerunning the sport build.",
            "high",
            "low",
            "accepted_for_metadata_only",
            "free_open_metadata_only",
            source_url="https://api-web.nhle.com/v1/score/now",
            source_type="public_json_api",
            source_owner_if_known="NHL",
            terms_url="https://www.nhl.com/info/terms-of-service",
            privacy_url="https://www.nhl.com/info/privacy-policy",
            api_docs_url="https://gitlab.com/dword4/nhlapi",
            primary_transport="residential_proxy",
            sample_strategy="metadata_only",
            normalized_entity_level="api_endpoint",
            repo_field_mapping=["schedule_results", "team_metadata", "goalie_confirmation"],
            sport_model_relevance="high",
            timestamp_available=True,
            event_time_available=True,
            game_or_match_start_time_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Official public metadata APIs are already part of the approved NHL open-data context.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="metadata_only",
            exact_blocker_or_allowance="Official NHL public metadata endpoints remain allowed, but this pass stores only policy metadata.",
        ),
        _policy_source(
            "nhl_team_roster_pages",
            "icehockey_nhl",
            "nhl",
            "NHL team roster and availability pages",
            "nhl.com",
            "/",
            "injuries/availability snapshots",
            "manual_template_ready",
            "reports/NHL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Resolve official NHL/team public injury-style pages into a manual-only final state.",
            "high",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://www.nhl.com/",
            source_type="official_team_page",
            source_owner_if_known="NHL / club sites",
            terms_url="https://www.nhl.com/info/terms-of-service",
            privacy_url="https://www.nhl.com/info/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="player_game",
            repo_field_mapping=["injuries_availability"],
            sport_model_relevance="high",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Manual timestamped roster/availability snapshots are safe and already the accepted NHL fallback.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="Official NHL/team pages remain manual-only for availability context.",
        ),
        _policy_source(
            "nhl_officiating_pages",
            "icehockey_nhl",
            "nhl",
            "NHL officials public pages",
            "nhl.com",
            "/info/officials",
            "officials/referee assignments",
            "manual_template_ready",
            "reports/NHL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Resolve NHL officiating pages into a final manual-only state rather than a vague future review item.",
            "medium",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://www.nhl.com/info/officials",
            source_type="official_public_page",
            source_owner_if_known="NHL",
            terms_url="https://www.nhl.com/info/terms-of-service",
            privacy_url="https://www.nhl.com/info/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="official_assignment",
            repo_field_mapping=["officials_referee_assignments"],
            sport_model_relevance="medium",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Manual official assignment imports remain safer than automating public league pages.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="NHL officiating pages remain manual-only in the final policy state.",
        ),
        _policy_source(
            "nhl_natural_stat_trick_line_combos",
            "icehockey_nhl",
            "nhl",
            "Natural Stat Trick line combination pages",
            "naturalstattrick.com",
            "/",
            "line-combination pages",
            "license_terms_unclear",
            "reports/NHL_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Turn the public line-combination ambiguity into a path-specific legal review record.",
            "medium",
            "low",
            "license_terms_unclear",
            "license_terms_unclear",
            source_url="https://www.naturalstattrick.com/",
            source_type="public_stats_page",
            source_owner_if_known="Natural Stat Trick",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="line_combination",
            repo_field_mapping=["lineup_line_combinations"],
            sport_model_relevance="medium",
            policy_mode="license_unclear",
            exact_blocker_or_allowance="Public line-combination pages exist, but the exact automated access terms were not confidently established in this pass.",
        ),
        _policy_source(
            "nhl_natural_stat_trick_xg",
            "icehockey_nhl",
            "nhl",
            "Natural Stat Trick xG and shot-quality pages",
            "naturalstattrick.com",
            "/",
            "public xG/shot-quality pages",
            "license_terms_unclear",
            "reports/NHL_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Set the public xG/shot-quality mirror path to a final explicit policy state.",
            "high",
            "low",
            "license_terms_unclear",
            "license_terms_unclear",
            source_url="https://www.naturalstattrick.com/",
            source_type="public_stats_page",
            source_owner_if_known="Natural Stat Trick",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="team_game",
            repo_field_mapping=["public_expected_goals_dataset"],
            sport_model_relevance="high",
            policy_mode="license_unclear",
            exact_blocker_or_allowance="Public xG-style pages exist, but their exact automation permissions remain legally unclear.",
        ),
        _policy_source(
            "nhl_dailyfaceoff_goalie_starts",
            "icehockey_nhl",
            "nhl",
            "DailyFaceoff goalie starts pages",
            "dailyfaceoff.com",
            "/starting-goalies/",
            "public goalie-start pages",
            "policy_review_required",
            "reports/NHL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Review the public goalie-start page class explicitly instead of leaving it implied.",
            "medium",
            "low",
            "license_terms_unclear",
            "license_terms_unclear",
            source_url="https://www.dailyfaceoff.com/starting-goalies",
            source_type="public_goalie_page",
            source_owner_if_known="DailyFaceoff",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="goalie_start",
            repo_field_mapping=["goalie_confirmation"],
            sport_model_relevance="medium",
            policy_mode="license_unclear",
            exact_blocker_or_allowance="Public goalie-start pages may be useful, but the exact automation and reuse terms remain unclear here.",
        ),
        _policy_source(
            "nhl_statsperform_goalie",
            "icehockey_nhl",
            "nhl",
            "Stats Perform NHL goalie feed pages",
            "statsperform.com",
            "/",
            "goalie GSAx-style mirrors",
            "paid_required",
            "reports/NHL_PAID_DATA_REQUIREMENT_MATRIX.json",
            "Finalize the goalie GSAx vendor path as explicitly paid/licensed only.",
            "high",
            "none",
            "accepted_for_attribution_only",
            "paid_subscription_required",
            source_url="https://www.statsperform.com/",
            source_type="paid_vendor_page",
            source_owner_if_known="Stats Perform",
            terms_url="https://www.statsperform.com/terms-and-conditions/",
            privacy_url="https://www.statsperform.com/privacy-policy/",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="vendor_page",
            repo_field_mapping=["goalie_gsaax_dataset"],
            sport_model_relevance="high",
            policy_mode="paid",
            exact_blocker_or_allowance="Public product pages are reviewable; structured goalie quality data remains licensed/paid.",
        ),
        _policy_source(
            "nhl_hockey_reference",
            "icehockey_nhl",
            "nhl",
            "Hockey Reference",
            "hockey-reference.com",
            "/",
            "restricted reference tables",
            "policy_blocked",
            "reports/NHL_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Close the remaining reference-site ambiguity with an explicit blocked decision.",
            "high",
            "none",
            "rejected_policy_blocked",
            "policy_blocked",
            source_url="https://www.hockey-reference.com/",
            source_type="restricted_reference_site",
            source_owner_if_known="Sports Reference",
            terms_url="https://www.sports-reference.com/termsofuse.html",
            privacy_url="https://www.sports-reference.com/privacy.html",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="site",
            repo_field_mapping=["restricted_reference_tables"],
            sport_model_relevance="high",
            policy_mode="blocked",
            exact_blocker_or_allowance="Sports Reference family hockey pages remain blocked for automation.",
        ),
        _policy_source(
            "nhl_github_duplicate",
            "icehockey_nhl",
            "nhl",
            "GitHub community NHL mirror docs",
            "github.com",
            "/sportsdataverse/",
            "community open mirror datasets",
            "duplicate",
            "reports/NHL_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Explicitly mark community NHL mirror docs as redundant where official or existing open sources already cover the lane.",
            "low",
            "none",
            "rejected_duplicate_source",
            "obsolete_or_duplicate",
            source_url="https://github.com/sportsdataverse",
            source_type="github_docs_page",
            source_owner_if_known="Community mirror",
            terms_url="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
            readme_url="https://github.com/sportsdataverse",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="dataset",
            repo_field_mapping=["community_open_mirror_datasets"],
            sport_model_relevance="low",
            duplicate_existing_source=True,
            policy_mode="duplicate",
            exact_blocker_or_allowance="Community NHL mirror docs are redundant with already approved open or official sources.",
        ),
        _policy_source(
            "soccer_football_data",
            "soccer",
            "soccer",
            "football-data.co.uk CSV and docs",
            "football-data.co.uk",
            "/data.php",
            "fixtures, results, team strength, rest/travel",
            "existing_open_dataset",
            "reports/SOCCER_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Carry the approved soccer CSV path into the combined completed-sports policy matrix.",
            "high",
            "medium",
            "accepted_for_automated_normalized_backfill",
            "free_open_backfilled",
            source_url="https://www.football-data.co.uk/data.php",
            source_type="open_csv_docs_page",
            source_owner_if_known="football-data.co.uk",
            terms_url="https://www.football-data.co.uk/data.php",
            data_dictionary_url="https://www.football-data.co.uk/notes.txt",
            primary_transport="web_scraper_api",
            sample_strategy="csv_rows",
            sample_url="https://www.football-data.co.uk/mmz4281/2324/D1.csv",
            normalized_entity_level="match",
            repo_field_mapping=["schedule_results", "first_half_scoring_context", "shots_corners_cards_context", "team_strength_ratings", "rest_travel_fixture_congestion"],
            sport_model_relevance="high",
            timestamp_available=True,
            event_time_available=True,
            game_or_match_start_time_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Public CSV rows are historical and timestamped enough for safe Soccer calibration features.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="automated_backfill",
            exact_blocker_or_allowance="Public soccer CSV and docs remain approved for normalized fact extraction.",
        ),
        _policy_source(
            "soccer_statsbomb_open",
            "soccer",
            "soccer",
            "StatsBomb open data repository",
            "github.com",
            "/statsbomb/open-data",
            "match metadata, events, lineups",
            "existing_open_dataset",
            "reports/SOCCER_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Fold the already approved public open-data repo into the combined policy review.",
            "high",
            "medium",
            "accepted_for_automated_normalized_backfill",
            "free_open_backfilled",
            source_url="https://github.com/statsbomb/open-data",
            source_type="github_open_data_repo",
            source_owner_if_known="StatsBomb",
            terms_url="https://github.com/statsbomb/open-data",
            license_url="https://raw.githubusercontent.com/statsbomb/open-data/master/LICENSE.pdf",
            data_dictionary_url="https://github.com/statsbomb/open-data/blob/master/doc",
            github_license_url="https://raw.githubusercontent.com/statsbomb/open-data/master/LICENSE.pdf",
            readme_url="https://github.com/statsbomb/open-data",
            primary_transport="web_scraper_api",
            sample_strategy="json_list",
            sample_url="https://raw.githubusercontent.com/statsbomb/open-data/master/data/matches/9/281.json",
            normalized_entity_level="match_event",
            repo_field_mapping=["statsbomb_match_metadata", "statsbomb_event_xg_shots", "statsbomb_lineups_minutes", "competition_context", "stadium_timezone_context", "player_prop_feature_candidates"],
            sport_model_relevance="high",
            timestamp_available=True,
            event_time_available=True,
            game_or_match_start_time_available=True,
            post_event_only=False,
            pre_event_available=False,
            usable_for_prematch_model=False,
            usable_for_postmatch_training_only=True,
            cutoff_safe=True,
            cutoff_safety_reason="Open historical event files are safe for normalized features and postmatch training context.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="automated_backfill",
            exact_blocker_or_allowance="Public StatsBomb open data remains approved for normalized fact extraction within open-data scope.",
        ),
        _policy_source(
            "soccer_bundesliga_official_pages",
            "soccer",
            "soccer",
            "Bundesliga official public pages",
            "bundesliga.com",
            "/en/bundesliga",
            "public lineups, injuries/availability, referee assignments",
            "manual_template_ready",
            "reports/SOCCER_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "Close the official soccer page class into an explicit manual-only decision.",
            "high",
            "low",
            "accepted_for_manual_import_only",
            "manual_import_required",
            source_url="https://www.bundesliga.com/en/bundesliga",
            source_type="official_league_page",
            source_owner_if_known="Bundesliga",
            terms_url="https://www.bundesliga.com/en/terms-and-conditions",
            privacy_url="https://www.bundesliga.com/en/privacy-policy",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="matchday_page",
            repo_field_mapping=["injuries_availability", "upcoming_referee_assignments"],
            sport_model_relevance="high",
            timestamp_available=True,
            pre_event_available=True,
            usable_for_prematch_model=True,
            cutoff_safe=True,
            cutoff_safety_reason="Manual timestamped official/availability snapshots are cutoff-safe.",
            normalized_fact_persistence_allowed=True,
            policy_mode="manual_only",
            exact_blocker_or_allowance="Official Bundesliga public pages remain manual-only for lineup, injury, and referee context.",
        ),
        _policy_source(
            "soccer_understat",
            "soccer",
            "soccer",
            "Understat public pages",
            "understat.com",
            "/",
            "public xG mirrors, public shot maps",
            "license_terms_unclear",
            "reports/SOCCER_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Replace the remaining broad Understat note with a source-specific legal uncertainty record.",
            "high",
            "low",
            "license_terms_unclear",
            "license_terms_unclear",
            source_url="https://understat.com/",
            source_type="public_xg_page",
            source_owner_if_known="Understat",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="team_game",
            repo_field_mapping=["broad_public_xg_mirror_coverage"],
            sport_model_relevance="high",
            policy_mode="license_unclear",
            exact_blocker_or_allowance="Public xG-style pages exist, but the exact automated access and reuse terms remain unclear.",
        ),
        _policy_source(
            "soccer_clubelo",
            "soccer",
            "soccer",
            "ClubElo public pages",
            "clubelo.com",
            "/About",
            "ClubElo football ratings data",
            "unavailable_or_failed",
            "reports/SOCCER_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Document the previously failed ClubElo path as either unavailable or terms-unclear with exact evidence.",
            "medium",
            "low",
            "unavailable_after_exhaustive_search",
            "unavailable_after_exhaustive_search",
            source_url="http://clubelo.com/About",
            source_type="public_rating_page",
            source_owner_if_known="ClubElo",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="team_rating",
            repo_field_mapping=["team_strength_ratings"],
            sport_model_relevance="medium",
            policy_mode="unavailable",
            exact_blocker_or_allowance="Repeated direct and Oxylabs attempts did not produce a stable public path for this pass.",
        ),
        _policy_source(
            "soccer_fivethirtyeight_archive",
            "soccer",
            "soccer",
            "FiveThirtyEight archived soccer data",
            "github.com",
            "/fivethirtyeight/data/tree/master/soccer-spi",
            "FiveThirtyEight archive",
            "policy_review_required",
            "reports/SOCCER_FREE_VS_PAID_SOURCE_LEDGER.json",
            "Add an explicit decision for the archived public soccer SPI path.",
            "medium",
            "low",
            "accepted_for_postmatch_training_only",
            "free_open_postmatch_training_only",
            source_url="https://github.com/fivethirtyeight/data/tree/master/soccer-spi",
            source_type="github_archive_repo",
            source_owner_if_known="FiveThirtyEight archive",
            terms_url="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
            readme_url="https://github.com/fivethirtyeight/data/tree/master/soccer-spi",
            primary_transport="web_scraper_api",
            sample_strategy="metadata_only",
            normalized_entity_level="team_match",
            repo_field_mapping=["team_strength_ratings", "postmatch_training_features"],
            sport_model_relevance="medium",
            timestamp_available=True,
            post_event_only=True,
            usable_for_postmatch_training_only=True,
            cutoff_safe=True,
            cutoff_safety_reason="Archived SPI-style data is suitable for historical training context only.",
            normalized_fact_persistence_allowed=True,
            aggregate_feature_persistence_allowed=True,
            policy_mode="postmatch_only",
            exact_blocker_or_allowance="Archived public soccer SPI-style data is treated as postmatch/training-only.",
        ),
        _policy_source(
            "soccer_statsbomb_360_paid",
            "soccer",
            "soccer",
            "StatsBomb 360 public product pages",
            "statsbomb.com",
            "/360/",
            "public tracking/360 mirrors",
            "paid_required",
            "reports/SOCCER_PAID_DATA_REQUIREMENT_MATRIX.json",
            "Finalize the Soccer tracking/360 vendor page into an explicit paid/licensed decision.",
            "high",
            "none",
            "accepted_for_attribution_only",
            "paid_subscription_required",
            source_url="https://statsbomb.com/360/",
            source_type="paid_vendor_page",
            source_owner_if_known="StatsBomb",
            terms_url="https://statsbomb.com/privacy-policy/",
            privacy_url="https://statsbomb.com/privacy-policy/",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="vendor_page",
            repo_field_mapping=["tracking_360_context"],
            sport_model_relevance="high",
            policy_mode="paid",
            exact_blocker_or_allowance="Public product pages can be reviewed, but broader 360 data remains licensed.",
        ),
        _policy_source(
            "soccer_fbref",
            "soccer",
            "soccer",
            "FBref",
            "fbref.com",
            "/",
            "reference-style mirrors",
            "policy_blocked",
            "reports/SOCCER_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Close the FBref blocked lane with source-specific evidence.",
            "high",
            "none",
            "rejected_policy_blocked",
            "policy_blocked",
            source_url="https://fbref.com/",
            source_type="restricted_reference_site",
            source_owner_if_known="Sports Reference",
            terms_url="https://www.sports-reference.com/termsofuse.html",
            privacy_url="https://www.sports-reference.com/privacy.html",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="site",
            repo_field_mapping=["restricted_reference_tables"],
            sport_model_relevance="high",
            policy_mode="blocked",
            exact_blocker_or_allowance="FBref remains blocked for automated extraction by explicit project policy.",
        ),
        _policy_source(
            "soccer_openfootball_duplicate",
            "soccer",
            "soccer",
            "OpenFootball Germany repository",
            "github.com",
            "/openfootball/deutschland",
            "OpenFootball mirror",
            "duplicate",
            "reports/SOCCER_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "Explicitly keep the OpenFootball mirror in a duplicate final state.",
            "low",
            "none",
            "rejected_duplicate_source",
            "obsolete_or_duplicate",
            source_url="https://github.com/openfootball/deutschland",
            source_type="github_open_data_repo",
            source_owner_if_known="OpenFootball",
            terms_url="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
            readme_url="https://github.com/openfootball/deutschland",
            primary_transport="web_scraper_api",
            sample_strategy="none",
            normalized_entity_level="dataset",
            repo_field_mapping=["openfootball_historical_results_mirror"],
            sport_model_relevance="low",
            duplicate_existing_source=True,
            policy_mode="duplicate",
            exact_blocker_or_allowance="OpenFootball remains redundant once football-data.co.uk is normalized.",
        ),
    ]


def sports_included_from_catalog() -> list[str]:
    return list(SPORTS_INCLUDED)


def completed_sports_allowed_domains() -> tuple[str, ...]:
    domains = {normalized_domain(candidate["source_domain"]) for candidate in completed_sports_candidate_source_catalog()}
    domains.update({"github.com", "raw.githubusercontent.com"})
    wildcard_domains = set(domains)
    wildcard_domains.update({f"*.{domain}" for domain in domains if "." in domain})
    return tuple(sorted(wildcard_domains))


def completed_sports_allowed_source_ids() -> tuple[str, ...]:
    return tuple(sorted(candidate["source_id"] for candidate in completed_sports_candidate_source_catalog()))


def fetch_text_with_transport(
    *,
    transport: str,
    source_id: str,
    domain: str,
    url: str,
    headers: dict[str, str] | None = None,
    timeout: int = 45,
) -> dict[str, Any]:
    cache_key = stable_hash(
        {
            "transport": transport,
            "source_id": source_id,
            "domain": domain,
            "url": url,
            "headers": headers or {},
            "timeout": timeout,
        }
    )
    cached = _FETCH_CACHE.get(cache_key)
    if cached is not None:
        return dict(cached)
    allowed_domains = completed_sports_allowed_domains()
    allowed_source_ids = completed_sports_allowed_source_ids()
    if transport == "residential_proxy":
        adapter = OxylabsResidentialProxyAdapter(
            source_id=source_id,
            domain=domain,
            allow_oxylabs=True,
            allow_paid_retrieval=True,
            allowed_source_ids=allowed_source_ids,
            allowed_domains=allowed_domains,
        )
        response = adapter.fetch_text(url, timeout=timeout, headers=headers)
    else:
        adapter = OxylabsWebScraperApiAdapter(
            source_id=source_id,
            domain=domain,
            allow_oxylabs=True,
            allow_paid_retrieval=True,
            allowed_source_ids=allowed_source_ids,
            allowed_domains=allowed_domains,
        )
        response = adapter.fetch_text(url, timeout=timeout)
    payload = {
        "ok": bool(response.get("ok")),
        "status": response.get("status"),
        "blocked_reason": response.get("blocked_reason"),
        "text": response.get("text") or "",
        "transport": transport,
        "source_id": source_id,
        "domain": domain,
        "url": url,
        "raw_html_persisted": False,
        "raw_payload_included": False,
        "secrets_included": False,
    }
    _FETCH_CACHE[cache_key] = payload
    return dict(payload)


def fetch_public_page_text(
    *,
    source_id: str,
    domain: str,
    url: str,
    transport: str = "web_scraper_api",
    headers: dict[str, str] | None = None,
    timeout: int = 45,
) -> dict[str, Any]:
    response = fetch_text_with_transport(
        transport=transport,
        source_id=source_id,
        domain=domain,
        url=url,
        headers=headers,
        timeout=timeout,
    )
    text = response.get("text") or ""
    if transport == "web_scraper_api":
        text = extract_web_scraper_content(text)
    return {
        **response,
        "text": text,
        "text_length": len(text),
        "source_url_hash": url_hash(url),
    }


def fetch_public_json(
    *,
    source_id: str,
    domain: str,
    url: str,
    transport: str = "residential_proxy",
    headers: dict[str, str] | None = None,
    timeout: int = 45,
) -> dict[str, Any]:
    response = fetch_public_page_text(
        source_id=source_id,
        domain=domain,
        url=url,
        transport=transport,
        headers=headers or {"Accept": "application/json,text/plain,*/*"},
        timeout=timeout,
    )
    payload: Any = None
    if response.get("ok"):
        try:
            payload = json.loads(response.get("text") or "")
        except Exception:
            payload = None
    return {
        **response,
        "json_payload": payload,
        "json_ok": isinstance(payload, (dict, list)),
    }


def parse_csv_rows(text: str, *, max_records: int | None = None) -> list[dict[str, str]]:
    if not text.strip():
        return []
    try:
        rows = [dict(row) for row in csv.DictReader(io.StringIO(text))]
    except csv.Error:
        return []
    if max_records is None:
        return rows
    return rows[: max(0, int(max_records))]


def candidate_index() -> dict[str, dict[str, Any]]:
    return {candidate["source_id"]: candidate for candidate in completed_sports_candidate_source_catalog()}


def prior_completed_sport_report_paths() -> dict[str, list[str]]:
    return {
        "nfl_mlb": [
            "reports/NFL_MLB_FREE_VS_PAID_FINAL_REPORT.json",
            "reports/NFL_MLB_FREE_VS_PAID_SOURCE_LEDGER.json",
            "reports/NFL_MLB_DATA_CALIBRATION_READINESS_REPORT.json",
            "reports/NFL_MLB_PAID_DATA_REQUIREMENT_MATRIX.json",
            "reports/TARGETED_SAMPLE_FIELD_CLOSURE_REPORT.json",
            "reports/NFL_COMPLETION_FINAL_REPORT.json",
            "reports/MLB_COMPLETION_FINAL_REPORT.json",
        ],
        "basketball": [
            "reports/BASKETBALL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "reports/BASKETBALL_FREE_OPEN_EXHAUSTION_CERTIFICATE.json",
            "reports/BASKETBALL_PAID_DATA_REQUIREMENT_MATRIX.json",
            "reports/BASKETBALL_DATA_CALIBRATION_READINESS_REPORT.json",
            "reports/BASKETBALL_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "reports/BASKETBALL_OXYLABS_RECLASSIFICATION_REPORT.json",
        ],
        "nhl": [
            "reports/NHL_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "reports/NHL_FREE_OPEN_EXHAUSTION_CERTIFICATE.json",
            "reports/NHL_PAID_DATA_REQUIREMENT_MATRIX.json",
            "reports/NHL_DATA_CALIBRATION_READINESS_REPORT.json",
            "reports/NHL_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "reports/NHL_OXYLABS_RECLASSIFICATION_REPORT.json",
        ],
        "soccer": [
            "reports/SOCCER_FINAL_OXYLABS_FREE_OPEN_EXHAUSTION_REPORT.json",
            "reports/SOCCER_FREE_OPEN_EXHAUSTION_CERTIFICATE.json",
            "reports/SOCCER_PAID_DATA_REQUIREMENT_MATRIX.json",
            "reports/SOCCER_DATA_CALIBRATION_READINESS_REPORT.json",
            "reports/SOCCER_OXYLABS_SOURCE_EXHAUSTION_LOG.json",
            "reports/SOCCER_OXYLABS_RECLASSIFICATION_REPORT.json",
            "reports/SOCCER_OXYLABS_SCHEMA_EXPANSION_REPORT.json",
            "reports/SOCCER_FREE_VS_PAID_SOURCE_LEDGER.json",
        ],
    }


def load_prior_completed_sport_reports() -> dict[str, dict[str, Any]]:
    reports: dict[str, dict[str, Any]] = {}
    for group, paths in prior_completed_sport_report_paths().items():
        reports[group] = {}
        for path_text in paths:
            reports[group][path_text] = read_json(Path(path_text))
    return reports


def build_policy_queries_for_group(
    *,
    sport_group: str,
    sport_label: str,
    extra_queries: list[str] | None = None,
) -> dict[str, Any]:
    candidates = [candidate for candidate in completed_sports_candidate_source_catalog() if candidate["sport_group"] == sport_group]
    query_rows: list[dict[str, Any]] = []
    families = (
        ("exact_source_name", lambda c: f"{sport_label} {c['source_name']}"),
        ("exact_domain_policy", lambda c: f"{c['source_domain']} terms robots license"),
        ("source_terms", lambda c: f"{c['source_name']} terms of use"),
        ("source_robots", lambda c: f"{c['source_name']} robots.txt"),
        ("source_license", lambda c: f"{c['source_name']} license"),
        ("source_api_docs", lambda c: f"{c['source_name']} api docs"),
        ("source_data_dictionary", lambda c: f"{c['source_name']} data dictionary"),
        ("source_attribution", lambda c: f"{c['source_name']} attribution"),
        ("source_commercial_use", lambda c: f"{c['source_name']} commercial use"),
        ("source_automation", lambda c: f"{c['source_name']} automated access"),
    )
    for candidate in candidates:
        for family, builder in families:
            query_rows.append(
                {
                    "sport_group": sport_group,
                    "sport_label": sport_label,
                    "source_id": candidate["source_id"],
                    "source_name": candidate["source_name"],
                    "domain": candidate["source_domain"],
                    "field_group": candidate["field_group"],
                    "query_family": family,
                    "query": builder(candidate),
                }
            )
    for query in extra_queries or []:
        query_rows.append(
            {
                "sport_group": sport_group,
                "sport_label": sport_label,
                "source_id": "",
                "source_name": sport_label,
                "domain": "",
                "field_group": "supplemental",
                "query_family": "extra_query",
                "query": query,
            }
        )
    return {
        "ok": True,
        "status": "ok",
        "sport_group": sport_group,
        "sport_label": sport_label,
        "query_rows": query_rows,
        "query_count": len(query_rows),
        "query_families": sorted({row["query_family"] for row in query_rows}),
        "provider_write": False,
        "execution_allowed": False,
        "raw_payload_included": False,
        "secrets_included": False,
    }
