from __future__ import annotations

from typing import Any, Mapping

from .security_policy import locked_safety_flags


MATURITY_STATUSES = {
    "inactive",
    "research_only",
    "calibration_only",
    "active_review",
    "active_ranking",
    "execution_eligible_future",
    "disabled",
    "demoted",
    "blocked_insufficient_data",
    "blocked_missing_dependency",
    "blocked_safety_review",
}

STRATEGY_FAMILIES = {
    "deterministic_rule_scoring",
    "candlestick_liquidity",
    "low_float_momentum",
    "balance_sheet_risk",
    "prediction_market_liquidity",
    "settlement_uncertainty",
    "sportsbook_game_script",
    "sports_prop_correlation",
    "basketball_player_impact",
    "manifold_nearest_neighbor",
    "markov_chain",
    "hmm_regime",
    "monte_carlo_risk",
    "graph_relationship",
    "causal_scaffold",
    "conformal_uncertainty",
    "information_theory",
    "topological_red_team",
    "extreme_randomness_red_team",
    "xgboost",
    "lightgbm",
    "tabular_foundation_research",
    "mdp_review_policy",
    "deepseek_red_team",
    "openai_optional_red_team",
}


def _strategy(
    strategy_id: str,
    strategy_name: str,
    strategy_family: str,
    *,
    asset_types_supported: list[str],
    market_types_supported: list[str],
    allowed_contexts: list[str] | None = None,
    forbidden_contexts: list[str] | None = None,
    maturity_status: str = "research_only",
    enabled: bool = True,
    affects_review_queue: bool = False,
    affects_ranking: bool = False,
    affects_execution: bool = False,
    required_inputs: list[str] | None = None,
    optional_inputs: list[str] | None = None,
    minimum_sample_size: int = 30,
    current_sample_size: int = 0,
    outcome_coverage: float = 0.0,
    calibration_status: str = "insufficient_data",
    performance_status: str = "unknown",
    promotion_status: str = "not_ready",
    demotion_status: str = "none",
    blocked_reason: str | None = None,
    safety_review_status: str = "locked_read_only",
) -> dict[str, Any]:
    maturity = maturity_status if maturity_status in MATURITY_STATUSES else "blocked_safety_review"
    if strategy_family not in STRATEGY_FAMILIES:
        maturity = "blocked_missing_dependency"
    record = {
        "strategy_id": strategy_id,
        "strategy_name": strategy_name,
        "strategy_family": strategy_family,
        "asset_types_supported": asset_types_supported,
        "market_types_supported": market_types_supported,
        "allowed_contexts": allowed_contexts or [],
        "forbidden_contexts": forbidden_contexts or [],
        "maturity_status": maturity,
        "enabled": bool(enabled),
        "affects_review_queue": bool(affects_review_queue),
        "affects_ranking": bool(affects_ranking),
        "affects_execution": False,
        "required_inputs": required_inputs or [],
        "optional_inputs": optional_inputs or [],
        "minimum_sample_size": int(minimum_sample_size),
        "current_sample_size": int(current_sample_size),
        "outcome_coverage": float(outcome_coverage or 0.0),
        "calibration_status": calibration_status,
        "performance_status": performance_status,
        "promotion_status": promotion_status,
        "demotion_status": demotion_status,
        "blocked_reason": blocked_reason,
        "safety_review_status": safety_review_status,
        "future_execution_eligible": False,
        "currently_executable": False,
        **locked_safety_flags(),
    }
    record["provider_write"] = False
    record["execution_allowed"] = False
    record["live_execution_enabled"] = False
    record["auto_execution"] = False
    return record


def get_default_strategy_registry() -> dict[str, dict[str, Any]]:
    strategies = [
        _strategy(
            "rule_scoring",
            "Deterministic Rule Scoring",
            "deterministic_rule_scoring",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook", "bond_rate", "major_asset"],
            market_types_supported=["*"],
            maturity_status="active_review",
            affects_review_queue=True,
            required_inputs=[],
            optional_inputs=["opportunity_score", "confidence_score"],
            current_sample_size=100,
            outcome_coverage=0.1,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "candlestick_liquidity",
            "Candlestick Liquidity",
            "candlestick_liquidity",
            asset_types_supported=["stock", "crypto"],
            market_types_supported=["equity", "stock", "crypto", "crypto_spot", "small_account_pattern"],
            allowed_contexts=["data_resolution:minute_or_better", "liquidity_tier:adequate"],
            forbidden_contexts=["asset_type:bond_rate", "asset_type:sportsbook"],
            maturity_status="active_review",
            affects_review_queue=True,
            affects_ranking=True,
            required_inputs=["price", "volume"],
            optional_inputs=["candles", "vwap", "relative_volume", "spread_score"],
            current_sample_size=40,
            outcome_coverage=0.25,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "low_float_momentum",
            "Low Float Momentum",
            "low_float_momentum",
            asset_types_supported=["stock"],
            market_types_supported=["equity", "stock", "small_account_pattern"],
            allowed_contexts=["asset_type:stock"],
            maturity_status="active_review",
            affects_review_queue=True,
            affects_ranking=True,
            required_inputs=["price", "float_shares", "relative_volume"],
            optional_inputs=["catalyst_detected", "dollar_volume", "intraday_percent_change"],
            current_sample_size=35,
            outcome_coverage=0.2,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "balance_sheet_risk",
            "Balance Sheet Risk",
            "balance_sheet_risk",
            asset_types_supported=["stock"],
            market_types_supported=["equity", "stock", "small_account_pattern"],
            maturity_status="active_review",
            affects_review_queue=True,
            affects_ranking=True,
            required_inputs=[],
            optional_inputs=["balance_sheet", "cash", "debt", "current_ratio"],
            minimum_sample_size=20,
            current_sample_size=20,
            outcome_coverage=0.12,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "prediction_market_liquidity",
            "Prediction Market Liquidity",
            "prediction_market_liquidity",
            asset_types_supported=["prediction_market"],
            market_types_supported=["prediction_market", "kalshi"],
            maturity_status="active_ranking",
            affects_review_queue=True,
            affects_ranking=True,
            required_inputs=["yes_bid", "yes_ask"],
            optional_inputs=["volume", "open_interest", "spread_score"],
            current_sample_size=60,
            outcome_coverage=0.4,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "settlement_uncertainty",
            "Settlement Uncertainty",
            "settlement_uncertainty",
            asset_types_supported=["prediction_market", "sportsbook"],
            market_types_supported=["prediction_market", "kalshi", "sportsbook", "sports_player_props"],
            maturity_status="active_review",
            affects_review_queue=True,
            affects_ranking=True,
            required_inputs=[],
            optional_inputs=["settlement_rule_status", "close_time", "outcome_status"],
            current_sample_size=38,
            outcome_coverage=0.3,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "sportsbook_game_script",
            "Sportsbook Game Script",
            "sportsbook_game_script",
            asset_types_supported=["sportsbook"],
            market_types_supported=["sports_player_props", "sports_pregame_main", "sports_totals", "sportsbook"],
            maturity_status="active_review",
            affects_review_queue=True,
            affects_ranking=True,
            required_inputs=["sport"],
            optional_inputs=["league", "pace", "total", "spread", "injury_status"],
            current_sample_size=30,
            outcome_coverage=0.18,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "sports_prop_correlation",
            "Sports Prop Correlation",
            "sports_prop_correlation",
            asset_types_supported=["sportsbook"],
            market_types_supported=["sports_player_props", "sportsbook"],
            maturity_status="calibration_only",
            affects_review_queue=True,
            required_inputs=["sport"],
            optional_inputs=["correlation_score", "teammate_usage", "lineup_context"],
            minimum_sample_size=50,
            current_sample_size=12,
            blocked_reason="needs_more_labeled_prop_outcomes",
        ),
        _strategy(
            "basketball_player_impact",
            "Basketball Player Impact",
            "basketball_player_impact",
            asset_types_supported=["sportsbook"],
            market_types_supported=["sports_player_props", "sportsbook"],
            allowed_contexts=["sport:basketball", "league:nba", "league:wnba", "league:ncaab"],
            maturity_status="calibration_only",
            affects_review_queue=True,
            required_inputs=["sport"],
            optional_inputs=["usage_rate", "minutes_projection", "lineup_status"],
            minimum_sample_size=75,
            current_sample_size=20,
            blocked_reason="basketball_impact_needs_more_outcomes",
        ),
        _strategy(
            "manifold_nearest_neighbor",
            "Manifold Nearest Neighbor",
            "manifold_nearest_neighbor",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook", "bond_rate", "major_asset"],
            market_types_supported=["*"],
            maturity_status="active_review",
            affects_review_queue=True,
            affects_ranking=True,
            required_inputs=[],
            optional_inputs=["manifold_cluster_id", "nearest_historical_neighbors", "out_of_distribution_risk"],
            current_sample_size=45,
            outcome_coverage=0.25,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "markov_chain",
            "Markov Chain State Transition",
            "markov_chain",
            asset_types_supported=["stock", "crypto", "sportsbook", "prediction_market"],
            market_types_supported=["*"],
            maturity_status="calibration_only",
            affects_review_queue=True,
            required_inputs=["state_sequence"],
            optional_inputs=["transition_matrix", "state_probability"],
            minimum_sample_size=100,
            blocked_reason="state_transition_history_missing",
        ),
        _strategy(
            "hmm_regime",
            "HMM Regime",
            "hmm_regime",
            asset_types_supported=["stock", "crypto", "bond_rate", "major_asset"],
            market_types_supported=["*"],
            maturity_status="calibration_only",
            affects_review_queue=True,
            required_inputs=["regime_features"],
            optional_inputs=["hidden_regime", "volatility_regime"],
            minimum_sample_size=120,
            blocked_reason="hidden_regime_training_data_missing",
        ),
        _strategy(
            "monte_carlo_risk",
            "Monte Carlo Risk",
            "monte_carlo_risk",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook", "bond_rate", "major_asset"],
            market_types_supported=["*"],
            maturity_status="active_review",
            affects_review_queue=True,
            affects_ranking=True,
            required_inputs=[],
            optional_inputs=["risk_score", "volatility", "max_loss"],
            current_sample_size=50,
            outcome_coverage=0.2,
            calibration_status="partial_calibration",
        ),
        _strategy(
            "graph_relationship",
            "Graph Relationship",
            "graph_relationship",
            asset_types_supported=["prediction_market", "sportsbook", "stock"],
            market_types_supported=["prediction_market", "sports_player_props", "sportsbook", "equity"],
            maturity_status="calibration_only",
            affects_review_queue=True,
            required_inputs=["relationship_graph"],
            optional_inputs=["correlation_edges", "dependency_edges"],
            minimum_sample_size=100,
            blocked_reason="relationship_graph_missing",
        ),
        _strategy(
            "causal_scaffold",
            "Causal Scaffold",
            "causal_scaffold",
            asset_types_supported=["sportsbook", "stock", "prediction_market"],
            market_types_supported=["*"],
            maturity_status="calibration_only",
            affects_review_queue=True,
            required_inputs=["causal_features"],
            optional_inputs=["instrumental_variables", "confounder_controls"],
            minimum_sample_size=150,
            blocked_reason="causal_identification_not_established",
        ),
        _strategy(
            "conformal_uncertainty",
            "Conformal Uncertainty",
            "conformal_uncertainty",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook"],
            market_types_supported=["*"],
            maturity_status="blocked_insufficient_data",
            affects_review_queue=True,
            required_inputs=["labeled_outcomes"],
            optional_inputs=["prediction_intervals", "coverage_target"],
            minimum_sample_size=200,
            blocked_reason="needs_labeled_outcome_coverage",
        ),
        _strategy(
            "information_theory",
            "Information Theory Diagnostics",
            "information_theory",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook"],
            market_types_supported=["*"],
            maturity_status="research_only",
            required_inputs=[],
            optional_inputs=["entropy", "mutual_information"],
        ),
        _strategy(
            "topological_red_team",
            "Topological Red Team",
            "topological_red_team",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook"],
            market_types_supported=["*"],
            maturity_status="research_only",
            required_inputs=[],
            optional_inputs=["topological_anomaly_score"],
        ),
        _strategy(
            "extreme_randomness_red_team",
            "Extreme Randomness Red Team",
            "extreme_randomness_red_team",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook"],
            market_types_supported=["*"],
            maturity_status="research_only",
            required_inputs=[],
            optional_inputs=["randomness_score"],
        ),
        _strategy(
            "xgboost",
            "XGBoost Research",
            "xgboost",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook"],
            market_types_supported=["*"],
            maturity_status="blocked_missing_dependency",
            required_inputs=["labeled_outcomes"],
            minimum_sample_size=1000,
            blocked_reason="heavy_ml_dependency_not_enabled_no_spend_phase",
        ),
        _strategy(
            "lightgbm",
            "LightGBM Research",
            "lightgbm",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook"],
            market_types_supported=["*"],
            maturity_status="blocked_missing_dependency",
            required_inputs=["labeled_outcomes"],
            minimum_sample_size=1000,
            blocked_reason="heavy_ml_dependency_not_enabled_no_spend_phase",
        ),
        _strategy(
            "tabular_foundation_research",
            "Tabular Foundation Research",
            "tabular_foundation_research",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook"],
            market_types_supported=["*"],
            maturity_status="research_only",
            required_inputs=["labeled_outcomes"],
            minimum_sample_size=5000,
        ),
        _strategy(
            "mdp_review_policy",
            "MDP Review Policy",
            "mdp_review_policy",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook"],
            market_types_supported=["*"],
            maturity_status="calibration_only",
            affects_review_queue=True,
            required_inputs=["state_sequence"],
            minimum_sample_size=250,
            blocked_reason="policy_transition_evidence_missing",
        ),
        _strategy(
            "deepseek_red_team",
            "DeepSeek Red Team",
            "deepseek_red_team",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook", "bond_rate", "major_asset"],
            market_types_supported=["*"],
            maturity_status="active_review",
            affects_review_queue=True,
            affects_ranking=False,
            required_inputs=[],
            optional_inputs=["compact_redacted_summary"],
            minimum_sample_size=0,
            current_sample_size=0,
            calibration_status="review_only_ai",
            safety_review_status="ai_read_only",
        ),
        _strategy(
            "openai_optional_red_team",
            "OpenAI Optional Red Team",
            "openai_optional_red_team",
            asset_types_supported=["stock", "crypto", "prediction_market", "sportsbook", "bond_rate", "major_asset"],
            market_types_supported=["*"],
            maturity_status="inactive",
            affects_review_queue=True,
            required_inputs=[],
            optional_inputs=["compact_redacted_summary"],
            minimum_sample_size=0,
            calibration_status="disabled_by_default",
            safety_review_status="ai_read_only_optional",
        ),
    ]
    return {row["strategy_id"]: row for row in strategies}


def get_strategy_registry(overrides: Mapping[str, Mapping[str, Any]] | None = None) -> dict[str, dict[str, Any]]:
    registry = get_default_strategy_registry()
    for strategy_id, patch in dict(overrides or {}).items():
        if strategy_id in registry and isinstance(patch, Mapping):
            registry[strategy_id] = normalize_strategy_record({**registry[strategy_id], **dict(patch)})
    return registry


def normalize_strategy_record(record: Mapping[str, Any]) -> dict[str, Any]:
    row = dict(record)
    row["maturity_status"] = row.get("maturity_status") if row.get("maturity_status") in MATURITY_STATUSES else "blocked_safety_review"
    row["provider_write"] = False
    row["execution_allowed"] = False
    row["live_execution_enabled"] = False
    row["auto_execution"] = False
    row["auto_execution_enabled"] = False
    row["affects_execution"] = False
    row["future_execution_eligible"] = False
    row["currently_executable"] = False
    for key, value in locked_safety_flags().items():
        if key in {
            "provider_write",
            "execution_allowed",
            "live_execution_enabled",
            "auto_execution",
            "auto_execution_enabled",
            "human_approval_required",
            "owner_approval_required",
        }:
            row[key] = value
    return row


def compact_strategy_registry(registry: Mapping[str, Mapping[str, Any]] | None = None) -> dict[str, Any]:
    reg = registry if registry is not None else get_strategy_registry()
    strategies = [normalize_strategy_record(row) for row in reg.values()]
    return {
        "ok": True,
        "status": "strategy_registry",
        "total_strategies": len(strategies),
        "strategies": sorted(strategies, key=lambda row: row["strategy_id"]),
        **locked_safety_flags(),
    }
