from __future__ import annotations

from pathlib import Path
from typing import Any

from .tennis_api_docs_parser import evaluate_tennis_api_docs
from .tennis_license_parser import evaluate_tennis_license
from .tennis_policy_classifier import classify_tennis_source
from .tennis_robots_checker import evaluate_tennis_robots
from .tennis_terms_parser import evaluate_tennis_terms
from .tennis_oxylabs_common import (
    ATP_README_URL,
    MATCH_CHARTING_README_URL,
    REPORT_ROOT,
    RUN_MODE,
    WTA_README_URL,
    current_utc,
    fetch_public_page_text,
    stable_hash,
    url_hash,
    write_json,
    write_md,
)


def _candidate(
    source_id: str,
    field_group: str,
    source_name: str,
    source_domain: str,
    source_url: str,
    *,
    source_type: str,
    policy_mode: str,
    prior_status: str,
    reason_for_recheck: str,
    expected_calibration_value: str,
    expected_backfill_value: str,
    target_final_decision: str,
    final_state_target: str,
    source_path_or_path_pattern: str | None = None,
    terms_url: str = "",
    license_url: str = "",
    robots_url: str = "",
    api_docs_url: str = "",
    data_dictionary_url: str = "",
    github_license_url: str = "",
    readme_url: str = "",
    attribution_url: str = "",
    acceptable_use_url: str = "",
    primary_transport: str = "web_scraper_api",
    sample_strategy: str = "none",
    sample_url: str = "",
    normalized_entity_level: str = "source",
    repo_field_mapping: list[str] | None = None,
    new_fields_recommended: list[str] | None = None,
    sport_model_relevance: str = "medium",
    duplicate_existing_source: bool = False,
    upstream_source_unclear: bool = False,
    login_required: bool = False,
    paywall_required: bool = False,
    captcha_required: bool = False,
    session_required: bool = False,
    timestamp_available: bool = True,
    event_time_available: bool = True,
    game_or_match_start_time_available: bool = True,
    data_publication_time_available: bool = True,
    future_leakage_risk: str = "low_if_joined_by_match_start",
    post_event_only: bool = False,
    pre_event_available: bool = True,
    usable_for_prematch_model: bool = True,
    usable_for_postmatch_training_only: bool = False,
    cutoff_safe: bool = True,
    cutoff_safety_reason: str = "join using tourney_date and match identity before market close",
    normalized_fact_persistence_allowed: bool = False,
    aggregate_feature_persistence_allowed: bool = False,
    exact_blocker_or_allowance: str = "",
) -> dict[str, Any]:
    return {
        "sport": "tennis",
        "sport_group": "tennis",
        "field_group": field_group,
        "source_id": source_id,
        "source_name": source_name,
        "source_domain": source_domain,
        "source_url": source_url,
        "source_path_or_path_pattern": source_path_or_path_pattern or source_url,
        "source_type": source_type,
        "source_owner_if_known": source_name,
        "mirror_or_original_source": "original",
        "likely_upstream_source": source_name,
        "public_or_private": "public",
        "policy_mode": policy_mode,
        "prior_status": prior_status,
        "prior_report_source": "first_tennis_finality_pass",
        "reason_for_recheck": reason_for_recheck,
        "policy_review_required": True,
        "expected_calibration_value": expected_calibration_value,
        "expected_backfill_value": expected_backfill_value,
        "target_final_decision": target_final_decision,
        "final_state_target": final_state_target,
        "login_required": login_required,
        "paywall_required": paywall_required,
        "captcha_required": captcha_required,
        "session_required": session_required,
        "terms_url": terms_url,
        "privacy_url": "",
        "license_url": license_url,
        "robots_url": robots_url,
        "api_docs_url": api_docs_url,
        "data_dictionary_url": data_dictionary_url,
        "GitHub_LICENSE_url": github_license_url,
        "README_url": readme_url,
        "attribution_url": attribution_url,
        "acceptable_use_url": acceptable_use_url,
        "copyright_notice_url": "",
        "primary_transport": primary_transport,
        "sample_strategy": sample_strategy,
        "sample_url": sample_url,
        "normalized_entity_level": normalized_entity_level,
        "repo_field_mapping": list(repo_field_mapping or []),
        "new_fields_recommended": list(new_fields_recommended or []),
        "sport_model_relevance": sport_model_relevance,
        "duplicate_existing_source": duplicate_existing_source,
        "upstream_source_unclear": upstream_source_unclear,
        "timestamp_available": timestamp_available,
        "event_time_available": event_time_available,
        "game_or_match_start_time_available": game_or_match_start_time_available,
        "data_publication_time_available": data_publication_time_available,
        "future_leakage_risk": future_leakage_risk,
        "post_event_only": post_event_only,
        "pre_event_available": pre_event_available,
        "usable_for_prematch_model": usable_for_prematch_model,
        "usable_for_postmatch_training_only": usable_for_postmatch_training_only,
        "cutoff_safe": cutoff_safe,
        "cutoff_safety_reason": cutoff_safety_reason,
        "normalized_fact_persistence_allowed": normalized_fact_persistence_allowed,
        "aggregate_feature_persistence_allowed": aggregate_feature_persistence_allowed,
        "source_hash_persistence_allowed": True,
        "fields_available": list(repo_field_mapping or []),
        "attribution_storage_required": bool(attribution_url),
        "required_attribution_text_or_url_hash": url_hash(attribution_url or source_url),
        "exact_blocker_or_allowance": exact_blocker_or_allowance,
    }


def tennis_candidate_source_catalog() -> list[dict[str, Any]]:
    return [
        _candidate(
            "tennis_jeff_sackmann_atp_matches",
            "ATP historical results, rankings, and serve-return fields",
            "Jeff Sackmann ATP Tennis Rankings, Results, and Stats",
            "github.com",
            "https://github.com/JeffSackmann/tennis_atp",
            source_type="open_csv_docs_page",
            policy_mode="license_unclear",
            prior_status="free_open_loader_needed",
            reason_for_recheck="core ATP historical lane candidate for results, rankings, and serve-return statistics",
            expected_calibration_value="very_high",
            expected_backfill_value="very_high",
            target_final_decision="license_terms_unclear",
            final_state_target="license_terms_unclear",
            terms_url="https://github.com/JeffSackmann/tennis_atp",
            license_url=ATP_README_URL,
            robots_url="https://github.com/robots.txt",
            data_dictionary_url=ATP_README_URL,
            readme_url=ATP_README_URL,
            attribution_url="https://github.com/JeffSackmann/tennis_atp",
            primary_transport="web_scraper_api",
            sample_strategy="csv_rows",
            sample_url="https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2025.csv",
            normalized_entity_level="match",
            repo_field_mapping=["tourney_id", "tourney_name", "surface", "draw_size", "tourney_level", "tourney_date", "match_num", "winner_id", "winner_name", "loser_id", "loser_name", "score", "best_of", "round", "minutes", "winner_rank", "loser_rank"],
            new_fields_recommended=["recent_match_minutes", "rest_days", "fatigue_proxy", "serve_return_edge"],
            exact_blocker_or_allowance="Repo README states CC BY-NC-SA / non-commercial-only use; explicit legal acceptance is required before automated backfill in this project.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_jeff_sackmann_wta_matches",
            "WTA historical results, rankings, and serve-return fields",
            "Jeff Sackmann WTA Tennis Rankings, Results, and Stats",
            "github.com",
            "https://github.com/JeffSackmann/tennis_wta",
            source_type="open_csv_docs_page",
            policy_mode="license_unclear",
            prior_status="free_open_loader_needed",
            reason_for_recheck="core WTA historical lane candidate for results, rankings, and serve-return statistics",
            expected_calibration_value="very_high",
            expected_backfill_value="very_high",
            target_final_decision="license_terms_unclear",
            final_state_target="license_terms_unclear",
            terms_url="https://github.com/JeffSackmann/tennis_wta",
            license_url=WTA_README_URL,
            robots_url="https://github.com/robots.txt",
            data_dictionary_url=WTA_README_URL,
            readme_url=WTA_README_URL,
            attribution_url="https://github.com/JeffSackmann/tennis_wta",
            primary_transport="web_scraper_api",
            sample_strategy="csv_rows",
            sample_url="https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master/wta_matches_2025.csv",
            normalized_entity_level="match",
            repo_field_mapping=["tourney_id", "tourney_name", "surface", "draw_size", "tourney_level", "tourney_date", "match_num", "winner_id", "winner_name", "loser_id", "loser_name", "score", "best_of", "round", "minutes", "winner_rank", "loser_rank"],
            new_fields_recommended=["recent_match_minutes", "rest_days", "fatigue_proxy", "serve_return_edge"],
            exact_blocker_or_allowance="Repo README states CC BY-NC-SA / non-commercial-only use; explicit legal acceptance is required before automated backfill in this project.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_match_charting_project_repo",
            "point-by-point and charting detail",
            "Match Charting Project",
            "github.com",
            "https://github.com/JeffSackmann/tennis_MatchChartingProject",
            source_type="open_github_docs_page",
            policy_mode="license_unclear",
            prior_status="free_open_sample_required",
            reason_for_recheck="candidate source for point-level, rally, and placement context",
            expected_calibration_value="high",
            expected_backfill_value="high",
            target_final_decision="license_terms_unclear",
            final_state_target="license_terms_unclear",
            terms_url="https://github.com/JeffSackmann/tennis_MatchChartingProject",
            license_url=MATCH_CHARTING_README_URL,
            robots_url="https://github.com/robots.txt",
            data_dictionary_url=MATCH_CHARTING_README_URL,
            readme_url=MATCH_CHARTING_README_URL,
            attribution_url="https://github.com/JeffSackmann/tennis_MatchChartingProject",
            sample_strategy="none",
            sample_url=MATCH_CHARTING_README_URL,
            normalized_entity_level="point_sequence",
            repo_field_mapping=["match_id", "serve_direction_preference", "return_position_proxy", "rally_length_profile"],
            new_fields_recommended=["rally_length_profile", "serve_direction_preference", "return_position_proxy"],
            usable_for_prematch_model=False,
            usable_for_postmatch_training_only=True,
            post_event_only=True,
            exact_blocker_or_allowance="Public charting repo is visible, but permitted downstream automation and commercialization scope remain unclear for this project.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_wikidata_player_entities",
            "player metadata and structured entities",
            "Wikidata Tennis Entities",
            "wikidata.org",
            "https://www.wikidata.org/wiki/Wikidata:Main_Page",
            source_type="structured_open_supplemental",
            policy_mode="metadata_only",
            prior_status="free_open_partial",
            reason_for_recheck="metadata-only source for player identity, country, and handedness supplementation",
            expected_calibration_value="low",
            expected_backfill_value="low",
            target_final_decision="accepted_for_metadata_only",
            final_state_target="free_open_metadata_only",
            terms_url="https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Terms_of_Use",
            license_url="https://www.wikidata.org/wiki/Wikidata:Licensing",
            robots_url="https://www.wikidata.org/robots.txt",
            api_docs_url="https://www.wikidata.org/w/api.php",
            data_dictionary_url="https://www.wikidata.org/wiki/Wikidata:Data_access",
            attribution_url="https://www.wikidata.org/wiki/Wikidata:Licensing",
            sample_strategy="none",
            normalized_entity_level="player",
            repo_field_mapping=["player_name", "player_country", "handedness_metadata", "birth_year_metadata"],
            exact_blocker_or_allowance="Metadata-only supplemental use with attribution retained is allowed in this pass.",
            normalized_fact_persistence_allowed=True,
        ),
        _candidate(
            "tennis_wikipedia_tennis_supplemental",
            "supplemental public metadata tables",
            "Wikipedia Tennis Supplemental Tables",
            "wikipedia.org",
            "https://en.wikipedia.org/wiki/ATP_Tour",
            source_type="structured_open_supplemental",
            policy_mode="metadata_only",
            prior_status="free_open_partial",
            reason_for_recheck="supplemental public metadata source for tour and player context",
            expected_calibration_value="low",
            expected_backfill_value="low",
            target_final_decision="accepted_for_metadata_only",
            final_state_target="free_open_metadata_only",
            terms_url="https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Terms_of_Use",
            license_url="https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License",
            robots_url="https://en.wikipedia.org/robots.txt",
            attribution_url="https://en.wikipedia.org/wiki/ATP_Tour",
            sample_strategy="none",
            normalized_entity_level="player_or_tour",
            repo_field_mapping=["tour_name", "player_country", "metadata_note"],
            exact_blocker_or_allowance="Supplemental metadata-only use with attribution retained is allowed in this pass.",
            normalized_fact_persistence_allowed=True,
        ),
        _candidate(
            "tennis_atp_official_rankings",
            "official ATP rankings and stats pages",
            "ATP Tour Official Rankings and Stats Pages",
            "atptour.com",
            "https://www.atptour.com/en/rankings/singles",
            source_type="official_rankings_page",
            policy_mode="blocked",
            prior_status="needs_manual_review",
            reason_for_recheck="official source family had to be checked even if it was likely to stay blocked",
            expected_calibration_value="high",
            expected_backfill_value="high",
            target_final_decision="rejected_policy_blocked",
            final_state_target="policy_blocked",
            terms_url="https://www.atptour.com/en/terms-and-conditions",
            license_url="https://www.atptour.com/en/terms-and-conditions",
            robots_url="https://www.atptour.com/robots.txt",
            attribution_url="https://www.atptour.com/en/rankings/singles",
            exact_blocker_or_allowance="ATP terms reserve scores, rankings, and statistics content and only allow personal non-commercial copying; no compliant automated path was approved here.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_wta_official_rankings",
            "official WTA rankings and stats pages",
            "WTA Official Rankings and Stats Pages",
            "wtatennis.com",
            "https://www.wtatennis.com/rankings/singles",
            source_type="official_rankings_page",
            policy_mode="blocked",
            prior_status="needs_manual_review",
            reason_for_recheck="official source family had to be checked even if it was likely to stay blocked",
            expected_calibration_value="high",
            expected_backfill_value="high",
            target_final_decision="rejected_policy_blocked",
            final_state_target="policy_blocked",
            terms_url="https://www.wtatennis.com/terms-and-conditions",
            license_url="https://www.wtatennis.com/terms-and-conditions",
            robots_url="https://www.wtatennis.com/robots.txt",
            attribution_url="https://www.wtatennis.com/rankings/singles",
            exact_blocker_or_allowance="WTA terms apply across WTA-controlled sites; no compliant automated extraction path was approved here.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_grand_slam_draw_pages",
            "official Grand Slam draw, schedule, and officials pages",
            "Official Grand Slam Draw and Event Pages",
            "wimbledon.com",
            "https://www.wimbledon.com/en_GB/scores/draws/index.html",
            source_type="official_event_page",
            policy_mode="manual_only",
            prior_status="free_open_manual_import_needed",
            reason_for_recheck="public event pages were checked for draw, officials, and context coverage",
            expected_calibration_value="moderate",
            expected_backfill_value="moderate",
            target_final_decision="accepted_for_manual_import_only",
            final_state_target="manual_import_required",
            terms_url="https://www.wimbledon.com/index.html",
            robots_url="https://www.wimbledon.com/robots.txt",
            attribution_url="https://www.wimbledon.com/en_GB/scores/draws/index.html",
            exact_blocker_or_allowance="Public event pages can support timestamped manual capture, but not automated normalized backfill in this pass.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_itf_withdrawal_news",
            "official withdrawal, injury, and availability news pages",
            "ITF / Tournament Withdrawal and News Pages",
            "itftennis.com",
            "https://www.itftennis.com/en/news-and-media/articles/",
            source_type="official_news_page",
            policy_mode="manual_only",
            prior_status="free_open_manual_import_needed",
            reason_for_recheck="availability lane needed explicit policy review and final state",
            expected_calibration_value="high",
            expected_backfill_value="high",
            target_final_decision="accepted_for_manual_import_only",
            final_state_target="manual_import_required",
            terms_url="https://www.itftennis.com/en/about-us/privacy-and-terms/",
            robots_url="https://www.itftennis.com/robots.txt",
            attribution_url="https://www.itftennis.com/en/news-and-media/articles/",
            exact_blocker_or_allowance="Availability and withdrawal pages remain manual-only because timestamp validation is required.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_tennis_data_uk_history",
            "tennis-data.co.uk historical odds and market files",
            "tennis-data.co.uk Historical Files",
            "tennis-data.co.uk",
            "https://www.tennis-data.co.uk/2025/2025.php",
            source_type="open_csv_docs_page",
            policy_mode="license_unclear",
            prior_status="license_terms_unclear",
            reason_for_recheck="historical market context and odds anchor candidate",
            expected_calibration_value="very_high",
            expected_backfill_value="high",
            target_final_decision="license_terms_unclear",
            final_state_target="license_terms_unclear",
            terms_url="https://www.tennis-data.co.uk/2025/2025.php",
            robots_url="https://www.tennis-data.co.uk/robots.txt",
            attribution_url="https://www.tennis-data.co.uk/2025/2025.php",
            exact_blocker_or_allowance="Historical odds files are visible, but reuse/license scope for automated integration remains unclear.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_kaggle_dataset_catalog",
            "Kaggle tennis dataset catalog",
            "Kaggle Tennis Dataset Catalog",
            "kaggle.com",
            "https://www.kaggle.com/datasets?search=tennis",
            source_type="dataset_catalog_page",
            policy_mode="blocked",
            prior_status="user_approved_paid_transport_needed",
            reason_for_recheck="catalog family had to be checked and finalized",
            expected_calibration_value="low",
            expected_backfill_value="low",
            target_final_decision="rejected_login_paywall_captcha",
            final_state_target="login_paywall_captcha_blocked",
            login_required=True,
            terms_url="https://www.kaggle.com/terms",
            robots_url="https://www.kaggle.com/robots.txt",
            exact_blocker_or_allowance="Catalog requires interactive account handling and cannot be treated as a compliant free/open automated source.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_tennis_abstract",
            "Tennis Abstract reference pages",
            "Tennis Abstract",
            "tennisabstract.com",
            "https://www.tennisabstract.com/",
            source_type="restricted_reference_site",
            policy_mode="blocked",
            prior_status="policy_blocked",
            reason_for_recheck="user explicitly called out Tennis Abstract as requiring exact-path approval before any use",
            expected_calibration_value="high",
            expected_backfill_value="moderate",
            target_final_decision="rejected_policy_blocked",
            final_state_target="policy_blocked",
            terms_url="https://www.tennisabstract.com/",
            robots_url="https://www.tennisabstract.com/robots.txt",
            exact_blocker_or_allowance="No exact-path approval was established for Tennis Abstract in this pass, so automation remains blocked.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_ultimate_tennis_statistics",
            "Ultimate Tennis Statistics reference pages",
            "Ultimate Tennis Statistics",
            "ultimatetennisstatistics.com",
            "https://www.ultimatetennisstatistics.com/",
            source_type="restricted_reference_site",
            policy_mode="blocked",
            prior_status="policy_blocked",
            reason_for_recheck="user explicitly called out Ultimate Tennis Statistics as requiring exact-path approval before any use",
            expected_calibration_value="high",
            expected_backfill_value="moderate",
            target_final_decision="rejected_policy_blocked",
            final_state_target="policy_blocked",
            terms_url="https://www.ultimatetennisstatistics.com/",
            robots_url="https://www.ultimatetennisstatistics.com/robots.txt",
            exact_blocker_or_allowance="No exact-path approval was established for Ultimate Tennis Statistics in this pass, so automation remains blocked.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_paid_tracking_vendor",
            "paid tracking and point-level vendor pages",
            "Paid Tracking / Point-Level Vendor Page",
            "statsperform.com",
            "https://www.statsperform.com/our-data/",
            source_type="paid_vendor_page",
            policy_mode="paid",
            prior_status="paid_data_subscription_required",
            reason_for_recheck="must prove paid lane stayed paid after exhausting free/open alternatives",
            expected_calibration_value="very_high",
            expected_backfill_value="very_high",
            target_final_decision="rejected_terms_blocked",
            final_state_target="paid_subscription_required",
            terms_url="https://www.statsperform.com/privacy-policy/",
            robots_url="https://www.statsperform.com/robots.txt",
            exact_blocker_or_allowance="Broader point-tracking, shot-pattern, and player-prop context remains a paid vendor lane.",
            normalized_fact_persistence_allowed=False,
        ),
        _candidate(
            "tennis_github_duplicate_mirror",
            "duplicate GitHub mirror of Jeff Sackmann data",
            "GitHub Duplicate Mirror of Jeff Sackmann Tennis Data",
            "github.com",
            "https://github.com/mare-imbrium/tennis-atp",
            source_type="community_duplicate_source",
            policy_mode="duplicate",
            prior_status="obsolete_or_duplicate",
            reason_for_recheck="duplicate mirror family still needed an explicit final decision",
            expected_calibration_value="none",
            expected_backfill_value="none",
            target_final_decision="rejected_duplicate_source",
            final_state_target="obsolete_or_duplicate",
            terms_url="https://github.com/mare-imbrium/tennis-atp",
            robots_url="https://github.com/robots.txt",
            exact_blocker_or_allowance="Mirror duplicates the upstream source already reviewed and adds no independent rights or coverage.",
            duplicate_existing_source=True,
            normalized_fact_persistence_allowed=False,
        ),
    ]


def build_tennis_candidate_source_policy_inventory(*, candidate_rows: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    candidate_rows = candidate_rows or tennis_candidate_source_catalog()
    inventory_rows = [
        {
            "sport": "Tennis",
            "source_family": candidate["source_type"],
            "source_name": candidate["source_name"],
            "domain": candidate["source_domain"],
            "source_path_or_path_pattern": candidate["source_path_or_path_pattern"],
            "field_group": candidate["field_group"],
            "prior_status": candidate["prior_status"],
            "prior_report_source": candidate["prior_report_source"],
            "reason_for_recheck": candidate["reason_for_recheck"],
            "policy_review_required": candidate["policy_review_required"],
            "expected_calibration_value": candidate["expected_calibration_value"],
            "expected_backfill_value": candidate["expected_backfill_value"],
            "target_final_decision": candidate["target_final_decision"],
            "source_id": candidate["source_id"],
        }
        for candidate in candidate_rows
    ]
    return {
        "ok": True,
        "status": "ok",
        "report_name": "TENNIS_CANDIDATE_SOURCE_POLICY_INVENTORY",
        "schema_version": "tennis_candidate_source_policy_inventory_v1",
        "created_at": current_utc(),
        "run_mode": RUN_MODE,
        "candidate_source_rows": inventory_rows,
        "candidate_source_count": len(inventory_rows),
        "provider_write": False,
        "execution_allowed": False,
        "raw_payload_included": False,
        "raw_html_persisted": False,
        "secrets_included": False,
        "paid_source_enabled_count": 1,
    }


def write_tennis_candidate_source_policy_inventory(report: dict[str, Any], *, output_dir: str | Path | None = None) -> dict[str, str]:
    root = Path(output_dir or REPORT_ROOT)
    json_path = root / "TENNIS_CANDIDATE_SOURCE_POLICY_INVENTORY.json"
    md_path = root / "TENNIS_CANDIDATE_SOURCE_POLICY_INVENTORY.md"
    write_json(json_path, report)
    lines = [
        "# Tennis Candidate Source Policy Inventory",
        "",
        f"1. candidate_source_count: {report.get('candidate_source_count')}",
        "",
        "## Sources",
    ]
    for row in report.get("candidate_source_rows") or []:
        lines.append(f"- {row.get('source_name')} -> {row.get('target_final_decision')}")
    write_md(md_path, "\n".join(lines) + "\n")
    return {"latest_json_path": str(json_path).replace("\\", "/"), "latest_markdown_path": str(md_path).replace("\\", "/")}


def build_tennis_source_policy_matrix(*, candidate_rows: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    candidate_rows = candidate_rows or tennis_candidate_source_catalog()
    rows: list[dict[str, Any]] = []
    for candidate in candidate_rows:
        source_page = fetch_public_page_text(
            source_id=candidate["source_id"],
            domain=candidate["source_domain"],
            url=candidate["source_url"],
            transport=str(candidate.get("primary_transport") or "web_scraper_api"),
            timeout=45,
        )
        robots_review = evaluate_tennis_robots(candidate)
        terms_review = evaluate_tennis_terms(candidate)
        license_review = evaluate_tennis_license(candidate)
        api_docs_review = evaluate_tennis_api_docs(candidate)
        matrix_row = classify_tennis_source(
            candidate,
            source_page=source_page,
            robots_review=robots_review,
            terms_review=terms_review,
            license_review=license_review,
            api_docs_review=api_docs_review,
        )
        transports = {
            str(source_page.get("transport") or ""),
            str(robots_review.get("oxylabs_transport_used") or ""),
            str(terms_review.get("oxylabs_transport_used") or ""),
            str(license_review.get("oxylabs_transport_used") or ""),
            str(api_docs_review.get("oxylabs_transport_used") or ""),
        }
        transports.discard("")
        transports.discard("hard_blocked")
        if transports == {"residential_proxy", "web_scraper_api"}:
            matrix_row["oxylabs_transport_used"] = "both"
        elif transports:
            matrix_row["oxylabs_transport_used"] = sorted(transports)[0]
        matrix_row.update(
            {
                "source_id": candidate["source_id"],
                "field_group": candidate["field_group"],
                "prior_status": candidate["prior_status"],
                "reason_for_recheck": candidate["reason_for_recheck"],
                "expected_calibration_value": candidate["expected_calibration_value"],
                "expected_backfill_value": candidate["expected_backfill_value"],
                "target_final_decision": candidate["target_final_decision"],
                "source_path_hash": stable_hash(candidate["source_path_or_path_pattern"]),
                "normalized_records_found": 0,
                "normalized_records_added": 0,
            }
        )
        rows.append(matrix_row)
    return {
        "ok": True,
        "status": "ok",
        "report_name": "TENNIS_SOURCE_POLICY_MATRIX",
        "schema_version": "tennis_source_policy_matrix_v1",
        "created_at": current_utc(),
        "run_mode": RUN_MODE,
        "policy_matrix_rows": rows,
        "policy_matrix_row_count": len(rows),
        "candidate_paths_policy_reviewed_count": len(rows),
        "policy_pages_checked": len(rows),
        "robots_checked": sum(1 for row in rows if row.get("robots_checked")),
        "terms_checked": sum(1 for row in rows if row.get("terms_checked")),
        "licenses_checked": sum(1 for row in rows if row.get("license_checked")),
        "api_docs_checked": sum(1 for row in rows if row.get("api_docs_checked")),
        "data_dictionaries_checked": sum(1 for row in rows if row.get("data_dictionary_checked")),
        "accepted_for_automated_normalized_backfill_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_automated_normalized_backfill"),
        "accepted_for_postmatch_training_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_postmatch_training_only"),
        "accepted_for_manual_import_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_manual_import_only"),
        "accepted_for_metadata_only_count": sum(1 for row in rows if row["path_level_decision"] == "accepted_for_metadata_only"),
        "rejected_policy_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_policy_blocked"),
        "rejected_robots_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_robots_blocked"),
        "rejected_terms_blocked_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_terms_blocked"),
        "rejected_login_paywall_captcha_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_login_paywall_captcha"),
        "license_terms_unclear_count": sum(1 for row in rows if row["path_level_decision"] == "license_terms_unclear"),
        "unavailable_after_exhaustive_search_count": sum(1 for row in rows if row["path_level_decision"] == "unavailable_after_exhaustive_search"),
        "obsolete_or_duplicate_count": sum(1 for row in rows if row["path_level_decision"] == "rejected_duplicate_source"),
        "provider_write": False,
        "execution_allowed": False,
        "raw_payload_included": False,
        "raw_html_persisted": False,
        "raw_screenshot_persisted": False,
        "secrets_included": False,
        "paid_source_enabled_count": 1,
    }


def write_tennis_source_policy_matrix(report: dict[str, Any], *, output_dir: str | Path | None = None) -> dict[str, str]:
    root = Path(output_dir or REPORT_ROOT)
    json_path = root / "TENNIS_SOURCE_POLICY_MATRIX.json"
    md_path = root / "TENNIS_SOURCE_POLICY_MATRIX.md"
    write_json(json_path, report)
    lines = [
        "# Tennis Source Policy Matrix",
        "",
        f"1. policy_matrix_row_count: {report.get('policy_matrix_row_count')}",
        f"2. accepted_for_manual_import_only_count: {report.get('accepted_for_manual_import_only_count')}",
        f"3. accepted_for_metadata_only_count: {report.get('accepted_for_metadata_only_count')}",
        f"4. rejected_policy_blocked_count: {report.get('rejected_policy_blocked_count')}",
        f"5. license_terms_unclear_count: {report.get('license_terms_unclear_count')}",
        "",
        "## Sources",
    ]
    for row in report.get("policy_matrix_rows") or []:
        lines.append(f"- {row.get('source_name')} final={row.get('final_state')} decision={row.get('path_level_decision')}")
    write_md(md_path, "\n".join(lines) + "\n")
    return {"latest_json_path": str(json_path).replace("\\", "/"), "latest_markdown_path": str(md_path).replace("\\", "/")}


def write_tennis_source_policy_review_docs(report: dict[str, Any], *, docs_dir: str | Path | None = None) -> dict[str, str]:
    root = Path(docs_dir or "docs")
    path = root / "TENNIS_SOURCE_POLICY_REVIEW.md"
    lines = [
        "# Tennis Source Policy Review",
        "",
        "This document records the final source-policy state for the Tennis free/open exhaustion pass.",
        "",
        "## Final Source States",
        "",
    ]
    for row in report.get("policy_matrix_rows") or []:
        lines.append(
            f"- {row.get('source_name')}: final_state={row.get('final_state')} decision={row.get('path_level_decision')} blocker_or_allowance={row.get('exact_blocker_or_allowance')}"
        )
    write_md(path, "\n".join(lines) + "\n")
    return {"source_policy_review_docs_path": str(path).replace("\\", "/")}
