"""Canonical disabled brokerage boundary package."""

from .accounts import (
    AccountReadiness,
    BrokerAccountDescriptor,
    DisabledAccountCreationError,
    build_account_readiness,
    create_account_disabled,
)
from .approval import (
    ApprovalDecision,
    ApprovalGateStatus,
    ApprovalMissingError,
    ApprovalRejectedError,
    ApprovalRequirement,
    ApprovalState,
    build_default_approval_requirements,
    evaluate_approval_gate,
    require_live_approval,
)
from .approval_evidence import (
    ApprovalEvidence,
    ApprovalSource,
    ApprovalValidationResult,
    build_default_approval_evidence,
    validate_approval_evidence,
)
from .activation import (
    ActivationBlockedError,
    ActivationGateResult,
    ActivationReadiness,
    ActivationRequirement,
    ActivationState,
    build_default_activation_requirements,
    build_disabled_activation_state,
    evaluate_activation_readiness,
    require_activation_ready,
)
from .adapter_readiness import (
    BrokerAccountCapability,
    BrokerAdapterReadiness,
    BrokerAssetClassSupport,
    BrokerCapabilityRequirement,
    BrokerOrderTypeSupport,
    BrokerReconciliationCapability,
    build_broker_adapter_readiness,
    validate_broker_adapter_readiness,
)
from .adapter import (
    BrokerAccountInfo,
    BrokerAdapter,
    BrokerAdapterCapabilities,
    BrokerAdapterDescriptor,
    BrokerAdapterStatus,
    BrokerOrderInfo,
    BrokerPositionInfo,
    DisabledBrokerAdapterError,
    build_adapter_capabilities,
    build_adapter_descriptor,
    build_disabled_adapter_status,
)
from .client_factory import (
    BrokerClientDescriptor,
    BrokerClientFactoryStatus,
    DisabledBrokerClientError,
    build_broker_client_descriptor,
    build_disabled_broker_client_status,
    create_broker_client_disabled,
)
from .credential_readiness import (
    CredentialReadinessResult,
    CredentialReadinessState,
    CredentialRequirement,
    build_credential_readiness_requirements,
    build_disabled_credential_readiness,
    evaluate_credential_readiness,
)
from .credentials import (
    BrokerCredentialDescriptor,
    BrokerCredentialPolicy,
    DisabledBrokerCredentialError,
    validate_broker_credentials_disabled,
)
from .contracts import (
    DisabledBrokerageError,
    DisabledExecutionError,
    ExecutionMode,
    ExecutionReadiness,
    ExecutionRequest,
    ExecutionResult,
    LedgerEvent,
    OrderRequest,
    OrderSide,
    OrderStatus,
    OrderTimeInForce,
    OrderType,
    PositionSnapshot,
)
from .execution import build_disabled_execution_result, submit_order_disabled
from .monitoring import (
    AlertingRequirement,
    HealthCheckRequirement,
    MonitoringReadiness,
    MonitoringRequirement,
    build_monitoring_readiness,
    evaluate_monitoring_readiness,
)
from .kill_switch import KillSwitchState, KillSwitchTriggeredError, build_default_kill_switch_state, require_kill_switch_clear
from .ledger import clear_ledger_events, get_ledger_events, record_ledger_event
from .deployment_readiness import (
    DeploymentReadiness,
    DeploymentRequirement,
    ProductionDeploymentBlockedError,
    build_disabled_deployment_readiness,
    evaluate_deployment_readiness,
    require_deployment_ready,
)
from .live_ledger import (
    LiveLedgerPersistenceDisabledError,
    LiveLedgerPersistencePlan,
    build_live_ledger_persistence_plan,
    persist_live_ledger_disabled,
)
from .live_reconciliation import (
    LiveReconciliationDisabledError,
    LiveReconciliationPlan,
    build_live_reconciliation_plan,
    reconcile_live_positions_disabled,
)
from .live_submit import (
    LiveSubmitDisabledError,
    LiveSubmitRequest,
    LiveSubmitResult,
    build_live_submit_request,
    submit_live_order_disabled,
)
from .sandbox_activation import (
    SandboxActivationRequest,
    SandboxActivationResult,
    SandboxActivationState,
    build_disabled_sandbox_activation,
    evaluate_sandbox_activation,
)
from .dry_run import (
    DryRunExecutionResult,
    DryRunLedgerEvent,
    DryRunOrder,
    build_dry_run_execution,
    build_dry_run_ledger_event,
    build_dry_run_order,
)
from .dry_run_ledger import (
    DryRunLedger,
    DryRunLedgerEntry,
    append_dry_run_event,
    build_dry_run_ledger,
    verify_dry_run_consistency,
)
from .sandbox_proof import (
    SandboxProofResult,
    SandboxProofStep,
    build_sandbox_proof,
    run_sandbox_proof,
)
from .submit_readiness import (
    SubmitReadinessResult,
    SubmitReadinessState,
    SubmitRequirement,
    build_disabled_submit_readiness,
    build_submit_readiness_requirements,
    evaluate_submit_readiness,
    verify_submit_path_disabled,
)
from .credential_loader import (
    CredentialActivationRequirements,
    CredentialActivationState,
    CredentialLoadRequest,
    DisabledCredentialLoadError,
    build_credential_activation_requirements,
    build_credential_load_request,
    load_credentials_disabled,
)
from .orders import build_execution_request, build_order_request
from .positions import build_position_snapshot
from .reconciliation import (
    PositionReconciliationRequest,
    PositionReconciliationResult,
    build_reconciliation_request,
    reconcile_positions_disabled,
)
from .readiness import get_execution_readiness
from .sandbox import (
    SandboxBrokerCapabilities,
    SandboxBrokerDescriptor,
    SandboxBrokerStatus,
    build_sandbox_capabilities,
    build_sandbox_descriptor,
    build_sandbox_status,
)
from .sandbox_submit import (
    DisabledSandboxSubmitError,
    SandboxSubmitRequest,
    SandboxSubmitResult,
    build_sandbox_submit_request,
    submit_sandbox_order_disabled,
)
from .rollback import RollbackPlan, build_rollback_plan
from .settlement import compare_settlement_rules
from .operator import (
    ApprovalAuditEntry,
    ApprovalAuditTrail,
    ApprovalAuditEntry as OperatorApprovalAuditEntry,
    ApprovalAuditTrail as OperatorApprovalAuditTrail,
    OperatorApprovalDecision,
    OperatorApprovalRecord,
    OperatorApprovalRequest,
    OperatorApprovalStatus,
    OperatorIdentity,
    build_default_operator,
    build_operator_request,
    evaluate_operator_approval,
    record_operator_decision,
)
from .approval_audit import (
    ApprovalAuditEvent,
    ApprovalAuditRecord,
    ApprovalAuditStatus,
    ApprovalAuditSummary,
    append_approval_event,
    build_approval_audit,
    summarize_approval_history,
)
from .sandbox_enablement import (
    SandboxEnablementRequest,
    SandboxEnablementResult,
    SandboxEnablementState,
    build_disabled_enablement,
    evaluate_enablement,
)
from .sandbox_adapter import (
    SandboxBrokerAdapter,
    SandboxBrokerCapabilities,
    SandboxBrokerResponse,
    build_sandbox_adapter,
    evaluate_sandbox_adapter,
)
from .kill_switch_policy import (
    KillSwitchDecision as KillSwitchPolicyDecision,
    KillSwitchOverride as KillSwitchPolicyOverride,
    KillSwitchPolicy,
    KillSwitchRule as KillSwitchPolicyRule,
    build_default_policy as build_default_kill_switch_policy,
    evaluate_policy as evaluate_kill_switch_policy,
)
from .deployment_policy import (
    DeploymentApproval,
    DeploymentBlocker,
    DeploymentChecklist,
    DeploymentPolicy,
    ProductionDeploymentBlockedError as DeploymentPolicyBlockedError,
    build_default_policy as build_default_deployment_policy,
    evaluate_deployment_policy,
)

__all__ = [
    "AccountReadiness",
    "ActivationBlockedError",
    "ActivationGateResult",
    "ActivationReadiness",
    "ActivationRequirement",
    "ActivationState",
    "ApprovalEvidence",
    "ApprovalDecision",
    "ApprovalGateStatus",
    "ApprovalMissingError",
    "ApprovalRejectedError",
    "ApprovalRequirement",
    "ApprovalState",
    "ApprovalSource",
    "ApprovalValidationResult",
    "BrokerAccountInfo",
    "BrokerAccountCapability",
    "BrokerAdapter",
    "BrokerAdapterCapabilities",
    "BrokerAdapterDescriptor",
    "BrokerAdapterReadiness",
    "BrokerAdapterStatus",
    "BrokerAssetClassSupport",
    "BrokerAccountDescriptor",
    "BrokerClientDescriptor",
    "BrokerClientFactoryStatus",
    "BrokerCapabilityRequirement",
    "BrokerCredentialDescriptor",
    "BrokerCredentialPolicy",
    "BrokerOrderInfo",
    "BrokerPositionInfo",
    "BrokerOrderTypeSupport",
    "BrokerReconciliationCapability",
    "CredentialReadinessResult",
    "CredentialReadinessState",
    "CredentialRequirement",
    "CredentialActivationRequirements",
    "CredentialActivationState",
    "CredentialLoadRequest",
    "DisabledAccountCreationError",
    "DisabledBrokerClientError",
    "DisabledBrokerAdapterError",
    "DisabledBrokerCredentialError",
    "DisabledBrokerageError",
    "DisabledExecutionError",
    "DisabledCredentialLoadError",
    "DisabledSandboxSubmitError",
    "DryRunExecutionResult",
    "DryRunLedger",
    "DryRunLedgerEntry",
    "DryRunLedgerEvent",
    "DryRunOrder",
    "DeploymentReadiness",
    "DeploymentRequirement",
    "ExecutionMode",
    "ExecutionReadiness",
    "ExecutionRequest",
    "ExecutionResult",
    "HealthCheckRequirement",
    "KillSwitchState",
    "KillSwitchTriggeredError",
    "LedgerEvent",
    "LiveLedgerPersistenceDisabledError",
    "LiveLedgerPersistencePlan",
    "LiveReconciliationDisabledError",
    "LiveReconciliationPlan",
    "LiveSubmitDisabledError",
    "LiveSubmitRequest",
    "LiveSubmitResult",
    "MonitoringReadiness",
    "MonitoringRequirement",
    "OrderRequest",
    "OrderSide",
    "OrderStatus",
    "OrderTimeInForce",
    "OrderType",
    "PositionReconciliationRequest",
    "PositionReconciliationResult",
    "PositionSnapshot",
    "RollbackPlan",
    "SubmitReadinessResult",
    "SubmitReadinessState",
    "SubmitRequirement",
    "SandboxBrokerCapabilities",
    "SandboxBrokerDescriptor",
    "SandboxBrokerStatus",
    "SandboxActivationRequest",
    "SandboxActivationResult",
    "SandboxActivationState",
    "SandboxSubmitRequest",
    "SandboxSubmitResult",
    "SandboxProofResult",
    "SandboxProofStep",
    "build_account_readiness",
    "append_dry_run_event",
    "build_default_approval_evidence",
    "build_broker_adapter_readiness",
    "build_adapter_capabilities",
    "build_adapter_descriptor",
    "build_broker_client_descriptor",
    "build_credential_activation_requirements",
    "build_credential_readiness_requirements",
    "build_credential_load_request",
    "build_default_activation_requirements",
    "build_default_approval_requirements",
    "build_default_kill_switch_state",
    "build_disabled_activation_state",
    "build_disabled_broker_client_status",
    "build_disabled_adapter_status",
    "build_disabled_credential_readiness",
    "build_disabled_deployment_readiness",
    "build_disabled_execution_result",
    "build_disabled_sandbox_activation",
    "build_disabled_submit_readiness",
    "build_dry_run_execution",
    "build_dry_run_ledger",
    "build_dry_run_ledger_event",
    "build_dry_run_order",
    "build_execution_request",
    "build_monitoring_readiness",
    "build_submit_readiness_requirements",
    "build_live_ledger_persistence_plan",
    "build_live_reconciliation_plan",
    "build_live_submit_request",
    "build_order_request",
    "build_position_snapshot",
    "build_sandbox_capabilities",
    "build_sandbox_descriptor",
    "build_sandbox_status",
    "build_sandbox_submit_request",
    "build_sandbox_proof",
    "build_reconciliation_request",
    "build_rollback_plan",
    "compare_settlement_rules",
    "clear_ledger_events",
    "create_account_disabled",
    "create_broker_client_disabled",
    "evaluate_activation_readiness",
    "evaluate_credential_readiness",
    "evaluate_deployment_readiness",
    "evaluate_monitoring_readiness",
    "evaluate_sandbox_activation",
    "evaluate_submit_readiness",
    "load_credentials_disabled",
    "evaluate_approval_gate",
    "get_execution_readiness",
    "get_ledger_events",
    "persist_live_ledger_disabled",
    "record_ledger_event",
    "reconcile_live_positions_disabled",
    "reconcile_positions_disabled",
    "require_kill_switch_clear",
    "require_activation_ready",
    "require_deployment_ready",
    "require_live_approval",
    "run_sandbox_proof",
    "submit_sandbox_order_disabled",
    "submit_live_order_disabled",
    "submit_order_disabled",
    "validate_approval_evidence",
    "validate_broker_adapter_readiness",
    "verify_submit_path_disabled",
    "verify_dry_run_consistency",
    "validate_broker_credentials_disabled",
    "ApprovalAuditEntry",
    "ApprovalAuditTrail",
    "ApprovalAuditRecord",
    "ApprovalAuditStatus",
    "ApprovalAuditSummary",
    "OperatorApprovalAuditEntry",
    "OperatorApprovalAuditTrail",
    "OperatorApprovalDecision",
    "OperatorApprovalRecord",
    "OperatorApprovalRequest",
    "OperatorApprovalStatus",
    "OperatorIdentity",
    "ApprovalAuditEvent",
    "SandboxEnablementRequest",
    "SandboxEnablementResult",
    "SandboxEnablementState",
    "SandboxBrokerAdapter",
    "SandboxBrokerResponse",
    "KillSwitchPolicy",
    "KillSwitchPolicyDecision",
    "KillSwitchPolicyOverride",
    "KillSwitchPolicyRule",
    "DeploymentApproval",
    "DeploymentBlocker",
    "DeploymentChecklist",
    "DeploymentPolicy",
    "DeploymentPolicyBlockedError",
    "build_default_operator",
    "build_operator_request",
    "evaluate_operator_approval",
    "record_operator_decision",
    "append_approval_event",
    "build_approval_audit",
    "summarize_approval_history",
    "build_disabled_enablement",
    "evaluate_enablement",
    "build_sandbox_adapter",
    "evaluate_sandbox_adapter",
    "build_default_kill_switch_policy",
    "evaluate_kill_switch_policy",
    "build_default_deployment_policy",
    "evaluate_deployment_policy",
]
