"""Canonical disabled brokerage boundary package."""

from .accounts import (
    AccountReadiness,
    BrokerAccountDescriptor,
    DisabledAccountCreationError,
    build_account_readiness,
    create_account_disabled,
)
from .approval import (
    ApprovalDecision,
    ApprovalGateStatus,
    ApprovalMissingError,
    ApprovalRejectedError,
    ApprovalRequirement,
    ApprovalState,
    build_default_approval_requirements,
    evaluate_approval_gate,
    require_live_approval,
)
from .adapter import (
    BrokerAccountInfo,
    BrokerAdapter,
    BrokerAdapterCapabilities,
    BrokerAdapterDescriptor,
    BrokerAdapterStatus,
    BrokerOrderInfo,
    BrokerPositionInfo,
    DisabledBrokerAdapterError,
    build_adapter_capabilities,
    build_adapter_descriptor,
    build_disabled_adapter_status,
)
from .client_factory import (
    BrokerClientDescriptor,
    BrokerClientFactoryStatus,
    DisabledBrokerClientError,
    build_broker_client_descriptor,
    build_disabled_broker_client_status,
    create_broker_client_disabled,
)
from .contracts import (
    DisabledBrokerageError,
    DisabledExecutionError,
    ExecutionMode,
    ExecutionReadiness,
    ExecutionRequest,
    ExecutionResult,
    LedgerEvent,
    OrderRequest,
    OrderSide,
    OrderStatus,
    OrderTimeInForce,
    OrderType,
    PositionSnapshot,
)
from .credentials import (
    BrokerCredentialDescriptor,
    BrokerCredentialPolicy,
    DisabledBrokerCredentialError,
    validate_broker_credentials_disabled,
)
from .execution import build_disabled_execution_result, submit_order_disabled
from .kill_switch import KillSwitchState, KillSwitchTriggeredError, build_default_kill_switch_state, require_kill_switch_clear
from .ledger import clear_ledger_events, get_ledger_events, record_ledger_event
from .live_ledger import (
    LiveLedgerPersistenceDisabledError,
    LiveLedgerPersistencePlan,
    build_live_ledger_persistence_plan,
    persist_live_ledger_disabled,
)
from .live_reconciliation import (
    LiveReconciliationDisabledError,
    LiveReconciliationPlan,
    build_live_reconciliation_plan,
    reconcile_live_positions_disabled,
)
from .live_submit import (
    LiveSubmitDisabledError,
    LiveSubmitRequest,
    LiveSubmitResult,
    build_live_submit_request,
    submit_live_order_disabled,
)
from .credential_loader import (
    CredentialActivationRequirements,
    CredentialActivationState,
    CredentialLoadRequest,
    DisabledCredentialLoadError,
    build_credential_activation_requirements,
    build_credential_load_request,
    load_credentials_disabled,
)
from .orders import build_execution_request, build_order_request
from .positions import build_position_snapshot
from .reconciliation import (
    PositionReconciliationRequest,
    PositionReconciliationResult,
    build_reconciliation_request,
    reconcile_positions_disabled,
)
from .readiness import get_execution_readiness
from .sandbox import (
    SandboxBrokerCapabilities,
    SandboxBrokerDescriptor,
    SandboxBrokerStatus,
    build_sandbox_capabilities,
    build_sandbox_descriptor,
    build_sandbox_status,
)
from .sandbox_submit import (
    DisabledSandboxSubmitError,
    SandboxSubmitRequest,
    SandboxSubmitResult,
    build_sandbox_submit_request,
    submit_sandbox_order_disabled,
)
from .rollback import RollbackPlan, build_rollback_plan
from .settlement import compare_settlement_rules

__all__ = [
    "AccountReadiness",
    "ApprovalDecision",
    "ApprovalGateStatus",
    "ApprovalMissingError",
    "ApprovalRejectedError",
    "ApprovalRequirement",
    "ApprovalState",
    "BrokerAccountInfo",
    "BrokerAdapter",
    "BrokerAdapterCapabilities",
    "BrokerAdapterDescriptor",
    "BrokerAdapterStatus",
    "BrokerAccountDescriptor",
    "BrokerClientDescriptor",
    "BrokerClientFactoryStatus",
    "BrokerCredentialDescriptor",
    "BrokerCredentialPolicy",
    "BrokerOrderInfo",
    "BrokerPositionInfo",
    "CredentialActivationRequirements",
    "CredentialActivationState",
    "CredentialLoadRequest",
    "DisabledAccountCreationError",
    "DisabledBrokerClientError",
    "DisabledBrokerAdapterError",
    "DisabledBrokerCredentialError",
    "DisabledBrokerageError",
    "DisabledExecutionError",
    "DisabledCredentialLoadError",
    "DisabledSandboxSubmitError",
    "ExecutionMode",
    "ExecutionReadiness",
    "ExecutionRequest",
    "ExecutionResult",
    "KillSwitchState",
    "KillSwitchTriggeredError",
    "LedgerEvent",
    "LiveLedgerPersistenceDisabledError",
    "LiveLedgerPersistencePlan",
    "LiveReconciliationDisabledError",
    "LiveReconciliationPlan",
    "LiveSubmitDisabledError",
    "LiveSubmitRequest",
    "LiveSubmitResult",
    "OrderRequest",
    "OrderSide",
    "OrderStatus",
    "OrderTimeInForce",
    "OrderType",
    "PositionReconciliationRequest",
    "PositionReconciliationResult",
    "PositionSnapshot",
    "RollbackPlan",
    "SandboxBrokerCapabilities",
    "SandboxBrokerDescriptor",
    "SandboxBrokerStatus",
    "SandboxSubmitRequest",
    "SandboxSubmitResult",
    "build_account_readiness",
    "build_adapter_capabilities",
    "build_adapter_descriptor",
    "build_broker_client_descriptor",
    "build_credential_activation_requirements",
    "build_credential_load_request",
    "build_default_approval_requirements",
    "build_default_kill_switch_state",
    "build_disabled_broker_client_status",
    "build_disabled_adapter_status",
    "build_disabled_execution_result",
    "build_execution_request",
    "build_live_ledger_persistence_plan",
    "build_live_reconciliation_plan",
    "build_live_submit_request",
    "build_order_request",
    "build_position_snapshot",
    "build_sandbox_capabilities",
    "build_sandbox_descriptor",
    "build_sandbox_status",
    "build_sandbox_submit_request",
    "build_reconciliation_request",
    "build_rollback_plan",
    "compare_settlement_rules",
    "clear_ledger_events",
    "create_account_disabled",
    "create_broker_client_disabled",
    "load_credentials_disabled",
    "evaluate_approval_gate",
    "get_execution_readiness",
    "get_ledger_events",
    "persist_live_ledger_disabled",
    "record_ledger_event",
    "reconcile_live_positions_disabled",
    "reconcile_positions_disabled",
    "require_kill_switch_clear",
    "require_live_approval",
    "submit_sandbox_order_disabled",
    "submit_live_order_disabled",
    "submit_order_disabled",
    "validate_broker_credentials_disabled",
]
