from __future__ import annotations

from typing import Optional


SPORT_ALIASES = {
    "mlb": "baseball_mlb",
    "baseball": "baseball_mlb",
    "major league baseball": "baseball_mlb",
    "nba": "basketball_nba",
    "basketball": "basketball_nba",
    "wnba": "basketball_wnba",
    "ncaab": "basketball_ncaab",
    "ncaaf": "americanfootball_ncaaf",
    "nfl": "americanfootball_nfl",
    "football": "americanfootball_nfl",
    "nhl": "icehockey_nhl",
    "hockey": "icehockey_nhl",
    "ahl": "icehockey_ahl",
    "ufc": "mma_mixed_martial_arts",
    "mma": "mma_mixed_martial_arts",
    "mixed_martial_arts": "mma_mixed_martial_arts",
    "mixed martial arts": "mma_mixed_martial_arts",
    "combat_sports": "mma_mixed_martial_arts",
    "combat sports": "mma_mixed_martial_arts",
    "boxing": "boxing_boxing",
    "epl": "soccer_epl",
    "premier league": "soccer_epl",
    "mls": "soccer_usa_mls",
    "serie_a": "soccer_italy_serie_a",
    "serie a": "soccer_italy_serie_a",
    "la_liga": "soccer_spain_la_liga",
    "la liga": "soccer_spain_la_liga",
    "bundesliga": "soccer_germany_bundesliga",
    "ligue_1": "soccer_france_ligue_one",
    "ligue 1": "soccer_france_ligue_one",
    "kbo": "baseball_kbo",
    "npb": "baseball_npb",
    "ipl": "cricket_ipl",
    "nrl": "rugbyleague_nrl",
    "afl": "aussierules_afl",
    "golf": "golf_masters_tournament_winner",
    "golf_pga": "golf_masters_tournament_winner",
    "pga": "golf_masters_tournament_winner",
    "pga_tour": "golf_masters_tournament_winner",
    "pga tour": "golf_masters_tournament_winner",
    "liv": "golf_masters_tournament_winner",
    "liv_golf": "golf_masters_tournament_winner",
    "liv golf": "golf_masters_tournament_winner",
    "dp_world_tour": "golf_masters_tournament_winner",
    "dp world tour": "golf_masters_tournament_winner",
    "european_tour": "golf_masters_tournament_winner",
    "european tour": "golf_masters_tournament_winner",
    "lpga": "golf_masters_tournament_winner",
}

THE_ODDS_API_SPORT_KEYS = {
    "americanfootball_cfl",
    "americanfootball_ncaaf",
    "americanfootball_ncaaf_championship_winner",
    "americanfootball_nfl",
    "americanfootball_nfl_preseason",
    "americanfootball_nfl_super_bowl_winner",
    "americanfootball_ufl",
    "aussierules_afl",
    "baseball_mlb",
    "baseball_mlb_preseason",
    "baseball_mlb_world_series_winner",
    "baseball_milb",
    "baseball_npb",
    "baseball_kbo",
    "baseball_ncaa",
    "basketball_euroleague",
    "basketball_nba",
    "basketball_nba_preseason",
    "basketball_nba_all_stars",
    "basketball_nba_summer_league",
    "basketball_nba_championship_winner",
    "basketball_wnba",
    "basketball_ncaab",
    "basketball_wncaab",
    "basketball_ncaab_championship_winner",
    "basketball_nbl",
    "boxing_boxing",
    "cricket_asia_cup",
    "cricket_big_bash",
    "cricket_caribbean_premier_league",
    "cricket_icc_trophy",
    "cricket_icc_world_cup",
    "cricket_icc_world_cup_womens",
    "cricket_international_t20",
    "cricket_ipl",
    "cricket_odi",
    "cricket_psl",
    "cricket_t20_blast",
    "cricket_t20_world_cup",
    "cricket_test_match",
    "cricket_the_hundred",
    "golf_masters_tournament_winner",
    "golf_pga_championship_winner",
    "golf_the_open_championship_winner",
    "golf_us_open_winner",
    "handball_germany_bundesliga",
    "icehockey_nhl",
    "icehockey_nhl_preseason",
    "icehockey_ahl",
    "icehockey_nhl_championship_winner",
    "icehockey_liiga",
    "icehockey_mestis",
    "icehockey_sweden_hockey_league",
    "icehockey_sweden_allsvenskan",
    "lacrosse_pll",
    "lacrosse_ncaa",
    "mma_mixed_martial_arts",
    "politics_us_presidential_election_winner",
    "rugbyleague_nrl",
    "rugbyleague_nrl_state_of_origin",
    "rugbyunion_six_nations",
    "soccer_africa_cup_of_nations",
    "soccer_argentina_primera_division",
    "soccer_australia_aleague",
    "soccer_austria_bundesliga",
    "soccer_belgium_first_div",
    "soccer_brazil_campeonato",
    "soccer_brazil_serie_b",
    "soccer_chile_campeonato",
    "soccer_china_superleague",
    "soccer_denmark_superliga",
    "soccer_efl_champ",
    "soccer_england_efl_cup",
    "soccer_england_league1",
    "soccer_england_league2",
    "soccer_epl",
    "soccer_fa_cup",
    "soccer_fifa_world_cup",
    "soccer_fifa_world_cup_qualifiers_europe",
    "soccer_fifa_world_cup_qualifiers_south_america",
    "soccer_fifa_world_cup_womens",
    "soccer_fifa_world_cup_winner",
    "soccer_fifa_club_world_cup",
    "soccer_finland_veikkausliiga",
    "soccer_france_coupe_de_france",
    "soccer_france_ligue_one",
    "soccer_france_ligue_two",
    "soccer_germany_bundesliga",
    "soccer_germany_bundesliga2",
    "soccer_germany_bundesliga_women",
    "soccer_germany_dfb_pokal",
    "soccer_germany_liga3",
    "soccer_greece_super_league",
    "soccer_italy_coppa_italia",
    "soccer_italy_serie_a",
    "soccer_italy_serie_b",
    "soccer_japan_j_league",
    "soccer_korea_kleague1",
    "soccer_league_of_ireland",
    "soccer_mexico_ligamx",
    "soccer_netherlands_eredivisie",
    "soccer_norway_eliteserien",
    "soccer_poland_ekstraklasa",
    "soccer_portugal_primeira_liga",
    "soccer_russia_premier_league",
    "soccer_spain_copa_del_rey",
    "soccer_spain_la_liga",
    "soccer_spain_segunda_division",
    "soccer_saudi_arabia_pro_league",
    "soccer_spl",
    "soccer_sweden_allsvenskan",
    "soccer_sweden_superettan",
    "soccer_switzerland_superleague",
    "soccer_turkey_super_league",
    "soccer_uefa_europa_conference_league",
    "soccer_uefa_champs_league",
    "soccer_uefa_champs_league_qualification",
    "soccer_uefa_champs_league_women",
    "soccer_uefa_europa_league",
    "soccer_uefa_european_championship",
    "soccer_uefa_euro_qualification",
    "soccer_uefa_nations_league",
    "soccer_concacaf_gold_cup",
    "soccer_concacaf_leagues_cup",
    "soccer_conmebol_copa_america",
    "soccer_conmebol_copa_libertadores",
    "soccer_conmebol_copa_sudamericana",
    "soccer_usa_mls",
    "tennis_atp_aus_open_singles",
    "tennis_atp_barcelona_open",
    "tennis_atp_canadian_open",
    "tennis_atp_china_open",
    "tennis_atp_cincinnati_open",
    "tennis_atp_dubai",
    "tennis_atp_french_open",
    "tennis_atp_indian_wells",
    "tennis_atp_italian_open",
    "tennis_atp_madrid_open",
    "tennis_atp_miami_open",
    "tennis_atp_monte_carlo_masters",
    "tennis_atp_munich",
    "tennis_atp_paris_masters",
    "tennis_atp_qatar_open",
    "tennis_atp_shanghai_masters",
    "tennis_atp_us_open",
    "tennis_atp_wimbledon",
    "tennis_wta_aus_open_singles",
    "tennis_wta_canadian_open",
    "tennis_wta_charleston_open",
    "tennis_wta_china_open",
    "tennis_wta_cincinnati_open",
    "tennis_wta_dubai",
    "tennis_wta_french_open",
    "tennis_wta_indian_wells",
    "tennis_wta_italian_open",
    "tennis_wta_madrid_open",
    "tennis_wta_miami_open",
    "tennis_wta_qatar_open",
    "tennis_wta_stuttgart_open",
    "tennis_wta_us_open",
    "tennis_wta_wimbledon",
    "tennis_wta_wuhan_open",
}

SPORT_LABELS = {
    "baseball_mlb": "MLB",
    "basketball_nba": "NBA",
    "basketball_wnba": "WNBA",
    "americanfootball_nfl": "NFL",
    "americanfootball_ncaaf": "NCAAF",
    "basketball_ncaab": "NCAAB",
    "icehockey_nhl": "NHL",
    "soccer_epl": "EPL",
    "soccer_usa_mls": "MLS",
    "mma_mixed_martial_arts": "UFC/MMA",
    "boxing_boxing": "Boxing",
    "golf_masters_tournament_winner": "Golf",
}

UNKNOWN_SPORT_EXAMPLES = ["mlb", "nba", "nfl", "nhl", "ufc", "boxing", "epl", "soccer_italy_serie_a", "baseball_mlb"]


def resolve_sport_key(sport: Optional[str], league: Optional[str]) -> tuple[Optional[str], Optional[str], Optional[dict]]:
    raw = (sport or league or "").strip()
    if not raw:
        return None, None, {
            "ok": False,
            "error_type": "SPORT_REQUIRED",
            "message": "sport or league is required",
            "examples": UNKNOWN_SPORT_EXAMPLES,
        }

    normalized = " ".join(raw.lower().replace("-", "_").split())
    sport_key = SPORT_ALIASES.get(normalized) or raw
    if sport_key not in THE_ODDS_API_SPORT_KEYS:
        return None, None, {
            "ok": False,
            "error_type": "UNKNOWN_SPORT",
            "message": "Unknown sport or league",
            "examples": UNKNOWN_SPORT_EXAMPLES,
        }
    return sport_key, SPORT_LABELS.get(sport_key, raw.upper()), None
