from __future__ import annotations


SUCCESS = "SUCCESS"
LIVE_AGENT_ERROR = "LIVE_AGENT_ERROR"
MOCK_MODE = "MOCK_MODE"
DRY_RUN = "DRY_RUN"
NO_MODEL = "NO_MODEL"
MODEL_METADATA_MISMATCH = "MODEL_METADATA_MISMATCH"
MODEL_NOT_ACTIVE = "MODEL_NOT_ACTIVE"
MODEL_REGISTRY_MISSING = "MODEL_REGISTRY_MISSING"
LIVE_FEATURES_MISSING = "LIVE_FEATURES_MISSING"
INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
NO_BET = "NO_BET"
WATCHLIST = "WATCHLIST"
MODEL_VALUE = "MODEL_VALUE"
CONFIRMED_BACKTESTED_EDGE = "CONFIRMED_BACKTESTED_EDGE"
RATE_LIMIT_PROTECTION = "RATE_LIMIT_PROTECTION"
PROVIDER_ERROR = "PROVIDER_ERROR"
AGENT_ALREADY_RUNNING = "AGENT_ALREADY_RUNNING"
AGENT_LOCK_STALE_RECOVERED = "AGENT_LOCK_STALE_RECOVERED"
RISK_BLOCKED = "RISK_BLOCKED"
EXPOSURE_LIMIT_EXCEEDED = "EXPOSURE_LIMIT_EXCEEDED"
STALE_ODDS_DROPPED = "STALE_ODDS_DROPPED"
ALERT_DEDUPED = "ALERT_DEDUPED"
INVALID_MARKET = "INVALID_MARKET"
INVALID_PROVIDER_PAYLOAD = "INVALID_PROVIDER_PAYLOAD"

ALL_STATUSES = frozenset(
    {
        SUCCESS,
        LIVE_AGENT_ERROR,
        MOCK_MODE,
        DRY_RUN,
        NO_MODEL,
        MODEL_METADATA_MISMATCH,
        MODEL_NOT_ACTIVE,
        MODEL_REGISTRY_MISSING,
        LIVE_FEATURES_MISSING,
        INSUFFICIENT_HISTORY,
        NO_BET,
        WATCHLIST,
        MODEL_VALUE,
        CONFIRMED_BACKTESTED_EDGE,
        RATE_LIMIT_PROTECTION,
        PROVIDER_ERROR,
        AGENT_ALREADY_RUNNING,
        AGENT_LOCK_STALE_RECOVERED,
        RISK_BLOCKED,
        EXPOSURE_LIMIT_EXCEEDED,
        STALE_ODDS_DROPPED,
        ALERT_DEDUPED,
        INVALID_MARKET,
        INVALID_PROVIDER_PAYLOAD,
    }
)


def is_valid_status(status: str) -> bool:
    return status in ALL_STATUSES
